Tradução: workflow-basics.qmd
cienciadedatos/pt-r4ds pull request #41
Opened 2023-09-08 01:27 UTC by nextmarte

Pontos para discussão: 

Fiquei na dúvida sobre traduzir a palavra workflow já que uma buzzword muito comum também em pt-br, como vai para revisão deixei a tradução para ver a opinião dos outros.

No item 3.3 "What’s in a name?", achei melhor não usar a tradução literal e adaptei para "A importância dos nomes" mas talvez os revisores tenham uma sugestão melhor já que essa parte trata de atribuição de nomes e typos.

Para ficar coerente com o conteúdo de alguns chunks em que traduzi o nome das variáveis, acabei traduzindo (substituindo) um print screen do ambiente global do RStudio, mas não tenho certeza se essa é a melhor forma de fazer as próximas traduções que envolvem reprodução de interface do RStudio.

2023-09-08 12:52 UTC, beatrizmilz requested changes
Oi! Fiz algumas sugestões. 
Vou escrever outro comentário com mais detalhes!

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Você agora tem alguma experiência em executar código R.
```suggestion
Você agora tem alguma experiência em executar código em R.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Antes de irmos mais longe, vamos garantir que você tenha uma base sólida na execução de código R e que conheça alguns dos recursos mais úteis do RStudio.
```suggestion
Antes de irmos mais longe, vamos garantir que você tenha uma base sólida na execução de código em R e que conheça alguns dos recursos mais úteis do RStudio.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Todos os comandos R em que você cria objetos, **comandos de atribuição**, têm a mesma forma:
```suggestion
Todos os comandos em R onde que você cria objetos, **comandos de atribuição**, têm a mesma forma:
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Isso permite que você escreva **comentários**, texto que é ignorado pelo R, mas que pode ser lido por outros humanos.
```suggestion
Isso permite que você escreva **comentários**, que são textos que são ignorados pelo R, mas que podem ser lidos por outros humanos.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Mas, à medida que o código que você está escrevendo fica mais complexo, os comentários podem economizar muito tempo seu (e de seus colaboradores) para descobrir o que foi feito no código.
```suggestion
Mas, à medida que o código que você está escrevendo fica mais complexo, os comentários podem economizar muito tempo seu (e das pessoas que colaboram com você) para descobrir o que foi feito no código.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Por exemplo, `geom_smooth()` tem um argumento chamado `span`, que controla a suavidade da curva(smoothness), com valores maiores produzindo uma curva mais suave.
```suggestion
Por exemplo, `geom_smooth()` tem um argumento chamado `span`, que controla a suavidade da curva (*smoothness*), com valores maiores produzindo uma curva mais suave.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Você pode inspecionar um objeto digitando seu nome:
Apesar de "inspect" ser a versão original, me parece meio estranho em português, não acha? 
Uma nova idéia:
```suggestion
Você pode ver o conteúdo de um objeto (chamaremos isso de inspecionar) digitando seu nome:
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Suponha que você decida alterar o valor de `span` de seu padrão de 0,75 para 0,9: é fácil para um leitor futuro entender *o que* está acontecendo, mas a menos que você anote seu pensamento em um come
```suggestion
Suponha que você decida alterar o valor de `span` de seu padrão de 0.75 para 0.9: é fácil para um leitor futuro entender *o que* está acontecendo, mas a menos que você anote seu pensamento em um comentário, ninguém entenderá o *por que* de você ter alterado o padrão.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Você pode usar outro atalho de teclado para ajudá-lo a corrigi-lo.
```suggestion
Você pode usar outro atalho de teclado para te ajudar a corrigi-lo.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Isso ilustra o contrato implícito entre você e o R: o R fará os cálculos chatos para você, mas em troca, você deve ser completamente preciso em suas instruções.
```suggestion
Isso ilustra o contrato implícito entre você e o R: o R fará os cálculos chatos para você, mas em troca, você deve ser escrever suas instruções de forma precisa.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Erros de digitação importam; o R não pode ler sua mente e dizer: "ah, você provavelmente quis dizer `r_rocks` quando digitou `r_rock`". <!-- neste trecho adaptei they para você, mas também poderiamos
```suggestion
Erros de digitação importam; o R não pode ler sua mente e dizer: "ah, você provavelmente quis dizer `r_rocks` quando digitou `r_rock`". 
```
No caso, "você" já está ótimo :D e a idéia não é usar elx e nem elu, mas seria bom eu adicionar algo sobre isso no guia para ficar mais claro.

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +A caixa alta importa; da mesma forma, o R não pode ler sua mente e dizer: "ah, você provavelmente quis dizer `r_rocks` quando digitou `R_rocks`".
```suggestion
A caixa alta (letras maiúsculas) importa; da mesma forma, o R não pode ler sua mente e dizer: "ah, você provavelmente quis dizer `r_rocks` quando digitou `R_rocks`".
```

deixei entre parêntereses pois caixa alta é correto mas acredito que é menos usado, assim fica mais facil de entender do que se trata

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Se você quiser mais ajuda, pressione F1 para obter todos os detalhes na guia de ajuda na parte inferior direita.
```suggestion
Se você quiser mais ajuda, pressione F1 para obter todos os detalhes no painel ajuda (*Help*) na parte inferior direita.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +O RStudio faz o melhor para ajudá-lo, mas ainda é possível cometer um erro e acabar com uma discrepância de aspas não fechadas.
```suggestion
O RStudio faz o melhor para te ajudar, mas ainda é possível cometer um erro e acabar com aspas não fechadas.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +O `+` indica que o R está esperando mais entrada(input); ele acha que você não terminou de digitar.
```suggestion
O `+` indica que o R está esperando mais alguma entrada (*input*); ele acha que você ainda não terminou de digitar.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Normalmente, isso significa que você esqueceu de adicionar um `"` ou um `)`. Adicione o par que está faltando ou pressione ESCAPE para abortar a expressão e tentar novamente.
```suggestion
Normalmente, isso significa que você esqueceu de adicionar um `"` ou um `)`. Adicione o par que está faltando ou pressione ESCAPE (ou ESC) para abortar a expressão e tentar novamente.
```

2023-09-08 12:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Observe que a guia de ambiente no painel superior direito exibe todos os objetos que você criou:
```suggestion
Observe que o painel ambiente (*Environment*) no painel superior direito exibe todos os objetos que você criou:
```

2023-09-08 12:54 UTC, beatrizmilz commented
> Fiquei na dúvida sobre traduzir a palavra workflow já que uma buzzword muito comum também em pt-br, como vai para revisão deixei a tradução para ver a opinião dos outros.

Acho que fluxo de trabalho funciona bem também!

> No item 3.3 "What’s in a name?", achei melhor não usar a tradução literal e adaptei para "A importância dos nomes" mas talvez os revisores tenham uma sugestão melhor já que essa parte trata de atribuição de nomes e typos.

Ficou ótimo assim. As vezes a tradução literal não faz tanto sentido mesmo. Acredito que é melhor facilitar o entendimento.

> Para ficar coerente com o conteúdo de alguns chunks em que traduzi o nome das variáveis, acabei traduzindo (substituindo) um print screen do ambiente global do RStudio, mas não tenho certeza se essa é a melhor forma de fazer as próximas traduções que envolvem reprodução de interface do RStudio.

Me parece que ficou ótimo também!

2023-09-08 13:01 UTC, beatrizmilz commented
Marcus, muito obrigada pela tradução! Ficou bem legal. 
Segue alguns apontamentos sobre as minhas sugestões.
- Algumas sugestões foram para facilitar a leitura do texto
- Sobre não marcar o gênero: preciso melhorar isso na documentação, mas a idéia não é usar elu, elx, pois isso dificulta a leitura para as pessoas que utilizam leituras de tela. Muitas vezes reescrevendo a frase já é possível tirar a marcação de gênero. Exemplos de sugestões que fiz:
   - e de seus colaboradores -> e das pessoas que colaboram com você
   - para ajudá-lo a corrigi-lo. -> para te ajudar a corrigi-lo.

   - você deve ser completamente preciso em suas instruções. -> você deve ser escrever suas instruções de forma precisa.
- Em casos de palavras em inglês, deixei em itálico
- Sobre os números: em um dos lugares você mudou o separador decimal para `,`. Acho melhor manter em `.` para facilitar o entendimento de que é assim que o R aceita. Faz sentido?
- Quando falamos dos Panels do R, sugeri deixar como "Painel tal (*nome do painel em inglês*)". Assim facilita quando a pessoa for usar o RStudio, pois estará em inglês. Ex: painel ambiente (*Environment*) 


**Caso você concorde com as sugestões, acredito que você consiga aceitá-las por aqui mesmo, não precisa editar na sua branch.**

2023-09-08 16:02 UTC, nextmarte commented
> * Sobre os números: em um dos lugares você mudou o separador decimal para `,`. Acho melhor manter em `.` para facilitar o entendimento de que é assim que o R aceita. Faz sentido?

Faz sim, vou levar isso em consideração na próxima.

2023-09-08 16:07 UTC, nextmarte commented on workflow-basics.qmd
> +Se você quiser mais ajuda, pressione F1 para obter todos os detalhes na guia de ajuda na parte inferior direita.
Isso realmente é importante, vou considerar nas próximas.

2023-09-08 16:39 UTC, beatrizmilz approved these changes

2023-09-08 16:40 UTC, beatrizmilz commented
Oi @nextmarte ! Vi que deu certo pra aceitar as sugestões.
Agora falta só mais uma pessoa revisar!

2023-09-15 22:42 UTC, beatrizmilz commented on workflow-basics.qmd
> +Suponha que você decida alterar o valor de `span` de seu padrão de 0.75 para 0.9: é fácil para um leitor futuro entender *o que* está acontecendo, mas a menos que você anote seu pensamento em um come
```suggestion
Suponha que você decida alterar o valor de `span` de seu padrão de 0.75 para 0.9: é fácil para alguém que está lendo no futuro entender *o que* está acontecendo, mas a menos que você anote seu pensamento em um comentário, ninguém entenderá o *por que* de você ter alterado o padrão.
```

2023-09-15 22:44 UTC, beatrizmilz commented on workflow-basics.qmd
> +Para inspecionar esse objeto, experimente o recurso de autocompletar do RStudio: digite "esse", pressione TAB, adicione caracteres até ter um prefixo único e pressione enter.
```suggestion
Para inspecionar esse objeto, experimente o recurso de autocompletar (*autocomplete*) do RStudio: digite "esse", pressione TAB, adicione caracteres até ter um prefixo único e pressione enter.
```

2023-09-15 22:45 UTC, beatrizmilz commented on workflow-basics.qmd
> +Uma janela pop-up mostra as possíveis conclusões.
```suggestion
Uma janela pop-up mostra as possíveis formas de completar o código.
```

2023-09-15 22:47 UTC, beatrizmilz commented on workflow-basics.qmd
> +Especifique `seq()` digitando mais (um `q`) para desambiguar ou usando as setas ↑/↓ para selecionar.
```suggestion
Especifique `seq()` digitando mais (um `q`) para especificar ou usando as setas ↑/↓ para selecionar.
```
faz sentido essa mudança? desambiguar fica tão estranho

2023-09-15 22:48 UTC, beatrizmilz commented on workflow-basics.qmd
> +Observe a dica flutuante que aparece, lembrando-o dos argumentos e propósito da função.
```suggestion
Observe a janelinha que aparece, mostrando os argumentos e o objetivo da função.
```

2023-09-15 22:50 UTC, beatrizmilz commented on workflow-basics.qmd
> +O RStudio adicionará parênteses de abertura (`(`) e fechamento (`)`) correspondentes para você automaticamente.
```suggestion
O RStudio adicionará os parênteses de abertura (`(`) e fechamento (`)`) correspondentes para você automaticamente.
```

2023-09-15 22:51 UTC, beatrizmilz commented on workflow-basics.qmd
> +Se isso acontecer, o R mostrará o caractere de continuação "+":
```suggestion
Se isso acontecer, o console do R mostrará o caractere de continuação "+":
```

2023-09-15 22:51 UTC, beatrizmilz commented on workflow-basics.qmd
> +Normalmente, isso significa que você esqueceu de adicionar um `"` ou um `)`. Adicione o par que está faltando ou pressione ESCAPE (ou ESC) para abortar a expressão e tentar novamente.
```suggestion
Normalmente, isso significa que você esqueceu de adicionar um `"` ou um `)`. Adicione o par que está faltando ou pressione ESCAPE (ou ESC) para cancelar a expressão e tentar novamente.
```

2023-09-15 22:52 UTC, beatrizmilz commented on workflow-basics.qmd
> +Nesse capítulo você aprendeu um pouco mais sobre como o código R funciona e algumas dicas para ajudá-lo a entender seu código quando você voltar a ele no futuro.
```suggestion
Nesse capítulo você aprendeu um pouco mais sobre como o código R funciona e algumas dicas para te ajudar a entender seu código quando você voltar a ele no futuro.
```

2023-09-15 22:53 UTC, beatrizmilz commented
Eu reli e percebi mais coisas que seria bom padronizar!  👀

2023-09-16 13:59 UTC, nextmarte commented on workflow-basics.qmd
> +Especifique `seq()` digitando mais (um `q`) para desambiguar ou usando as setas ↑/↓ para selecionar.
Acho que poderia ser especificar, mas desambiguar faz mais sentido aqui, outra opção que se encaixaria melhor na minha opinião seria "distinguir" , o que você acha?

2023-11-13 18:01 UTC, scopinho commented
Pessoal, posso fazer a revisão deste capítulo também.

2023-11-13 18:19 UTC, beatrizmilz commented
Ótimo @scopinho !!

2023-11-13 18:27 UTC, scopinho requested changes
Olá, sugeri pequenos ajustes. Na linha 223, não consigo alterar o código pela interface, coloquei como comentário mesmo. Avise se tiver dúvida. Parabéns pela tradução!

2023-11-13 18:27 UTC, scopinho commented on workflow-basics.qmd
> +Mas, embora você deva esperar um pouco de frustração, tenha em mente que essa experiência é típica e temporária: acontece com todo mundo, e a única maneira de superá-la é continuar tentando.
```suggestion
Mas, embora você deva esperar um pouco de frustração, tenha em mente que essa experiência é normal e temporária: acontece com todo mundo, e a única maneira de superá-la é continuar tentando.
```

2023-11-13 18:27 UTC, scopinho commented on workflow-basics.qmd
> +O *o quê* e o *como* do seu código são sempre possíveis de descobrir, mesmo que possa ser chato, lendo-o cuidadosamente.
```suggestion
O *o quê* e o *como* do seu código são sempre possíveis de descobrir lendo-os cuidadosamente, mesmo que isso possa ser chato.
```

2023-11-13 18:27 UTC, scopinho commented on workflow-basics.qmd
> +Vamos voltar aos nomes quando discutirmos o estilo de código em @sec-workflow-style.
```suggestion
Vamos voltar aos nomes quando discutirmos o estilo de código no @sec-workflow-style.
```

2023-11-13 18:27 UTC, scopinho commented on workflow-basics.qmd
>      #| error: true
Acredito que poderíamos traduzir aqui também:

`minha_variavel <- 10`

2023-11-13 18:27 UTC, scopinho commented on workflow-basics.qmd
>      my_varıable
```suggestion
    minha_varıavel
```

2023-11-13 18:40 UTC, beatrizmilz commented on workflow-basics.qmd
>      #| error: true
Feito! Descobri como muda nesse caso. Precisei entrar no fork do @nextmarte , encontrar o arquivo, e o github me deixa sugerir a alteração por lá!

2023-11-13 18:42 UTC, merged

2023-11-13 18:49 UTC, scopinho reviewed
Ajuste na sintaxe de minha_variavel. Ela precisa ter um erro para que o exercício faça sentido.

2023-11-13 18:49 UTC, scopinho commented on workflow-basics.qmd
>      #| error: true
Ah..legal. Bom saber, só um ponto... precisa ter uma letra L no lugar do i , na segunda linha : **minha_varıable** ao invés de **minha_variavel**, o exercício é justamente pra pegar o erro de sintaxe depois da atribuicao.

2023-11-13 18:49 UTC, scopinho commented on workflow-basics.qmd
> +    minha_variavel
minha_varıavel

2023-11-13 18:53 UTC, beatrizmilz commented on workflow-basics.qmd
> +    minha_variavel
eu percebi depois que eu tinha alterado isso errado, mas arrumei aqui: https://github.com/cienciadedatos/pt-r4ds/commit/73023cf25bb8d5ecec9f6b48a9879bb1491e0244