tradução capítulo (sem traduzir fig-alt)
cienciadedatos/pt-r4ds pull request #43
Opened 2023-09-09 19:51 UTC by brunomioto

Algumas observações sobre a tradução:

Estou enviando o PR quase finalizado pois viajo em coleta segunda e não terei muito tempo pelos próximos 10 dias.

Faltou traduzir apenas os textos alternativos (fig-alt) dos gráficos.

Traduzi os datasets utilizados de acordo com o pacote {dados}, não utilizando os pacote palmerpenguins, diamonds e mtcars.

A figura explicativa do boxplot ainda deve ser traduzida (externamente)

Algumas traduções que segui para tentar facilitar a leitura. Fiquem à vontade para mudar:

- mapping: mapeamento
- aesthetics: atributos estéticos
- scaling: dimensionamento
- geometrical object: geometria
- the geom: a geom
- labels: rótulos (eu até pensei em títulos mas pode ficar confuso)
- binwidth: largura de intervalo
- data frame: data frame

Talvez eu tenha mudado o estilo de tradução durante o trabalho porque o capítulo era bem longo.

2023-09-16 18:40 UTC, nextmarte requested changes
@brunomioto, fiz algumas sugestões, mas no geral achei que as traduções ficaram muito boas. Como é um cap. longo posso ter deixado passar alguma coisa, vou reler mais tarde pra ver se esqueci algo. 

Obs.: Na linha 864, quando e feita a menção ao QUARTO, achei um pouco estranha a tradução, então sugeri outra abordagem para a frase.

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +Normalmente, o primeiro ou os dois primeiros argumentos de uma função são tão importantes que você deve sabê-los de cor.
```suggestion
Normalmente, o primeiro ou os dois primeiros argumentos de uma função são tão importantes que você deve saber usar de cor.
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +No futuro, você também aprenderá sobre o pipe, `|>`, que permitirá que você crie esse gráfico com:
```suggestion
No futuro, você também aprenderá sobre o pipe(encadeamento), `|>`, que permitirá que você crie esse gráfico com a seguinte sintaxe:
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +Uma largura de intervalo de 200 proporciona um balanço adequado.
```suggestion
Uma largura de intervalo de 200 proporciona um balanço mais adequado.
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +No entanto, mapear muitos atirbutos estéticos a um gráfico faz com que ele fique desordenado e difícil de entender.
```suggestion
No entanto, mapear muitos atributos estéticos a um gráfico faz com que ele fique desordenado e difícil de entender.
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +Outra maneira, que é particularmente útil para variáveis categóricas, é dividir seu gráfico em **facetas**, subdivisões que exibem um subconjunto dos dados cada uma.
```suggestion
Outra maneira, que é particularmente útil para variáveis categóricas, é dividir seu gráfico em **facetas**, subdivisões ou janelas que exibem um subconjunto dos dados cada uma.
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
```suggestion
De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de editoração técnico científica que permite intercalar seu código e sua escrita e incluir automaticamente seus gráficos em seus relatórios.
```

2023-09-16 18:40 UTC, nextmarte commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
Achei essa parte do Quarto difícil de localizar para o português, acho que a @beatrizmilz pode contribuir aqui. De qualquer forma deixei uma proposta para o termo em pt-br.

2023-09-17 13:20 UTC, beatrizmilz reviewed
Não terminei ainda, logo continuo!

2023-09-17 13:20 UTC, beatrizmilz commented on data-visualize.qmd
> +No tidyverse, usamos *data frames* especiais chamados ***tibbles***, dos quais você aprenderá mais em breve.
nesse caso, me parece que os três asteriscos são para deixar em negrito e em itálico (e acho que faz sentido, pois no livro tá em negrito para destacar, mas não é uma palavra em português então deixamos em itálico.

2023-09-17 13:20 UTC, beatrizmilz commented on data-visualize.qmd
> +O primeiro argumento de `ggplot()` é o conjunto de dados a ser usado no gráfico e, portanto, `ggplot(data = pinguins)` cria um gráfico vazio que está preparado para exibir os dados dos `pinguins`, ma
```suggestion
O primeiro argumento da função `ggplot()` é o conjunto de dados a ser usado no gráfico e, portanto, `ggplot(data = pinguins)` cria um gráfico vazio que está preparado para exibir os dados dos `pinguins`, mas, como ainda não dissemos como visualizá-los, por enquanto ele está vazio.
```

2023-09-17 13:20 UTC, beatrizmilz commented on data-visualize.qmd
> +O argumento `mapping` é sempre definido na função `aes()`, e os argumentos `x` e `y` de `aes()` especificam quais variáveis devem ser mapeadas para os eixos x e y.
```suggestion
O argumento `mapping` é sempre definido na função `aes()`, e os argumentos `x` e `y` de `aes()` especificam quais variáveis devem ser mapeadas nos eixos x e y.
```

2023-09-17 13:20 UTC, beatrizmilz commented on data-visualize.qmd
> +Para isso, precisamos definir uma **geom**: A geometria que um gráfico usa para representar os dados.
```suggestion
Para isso, precisamos definir um **geom**: a geometria que um gráfico usa para representar os dados.
```

2023-09-17 16:38 UTC, beatrizmilz commented on data-visualize.qmd
> +Ele ainda não corresponde ao nosso gráfico de "objetivo final", mas, usando esse gráfico, podemos começar a responder à pergunta que motivou nossa exploração: "Como é a relação entre o comprimento da
```suggestion
Ele ainda não corresponde ao nosso gráfico mostrado no início da seção "objetivo final", mas, usando esse gráfico, podemos começar a responder à pergunta que motivou nossa exploração: "Como é a relação entre o comprimento da nadadeira e a massa corporal?" A relação parece ser positiva (à medida que o comprimento da nadadeira aumenta, a massa corporal também aumenta), razoavelmente linear (os pontos estão agrupados em torno de uma linha em vez de uma curva) e moderadamente forte (não há muita dispersão em torno dessa linha).
```

2023-09-17 16:38 UTC, beatrizmilz commented on data-visualize.qmd
> +Estamos vendo essa mensagem porque há dois pinguins em nosso conjunto de dados com valores ausentes de massa corporal e/ou comprimento da nadadeira e o ggplot2 não tem como representá-los no gráfico
```suggestion
Estamos vendo essa mensagem porque há dois pinguins em nosso conjunto de dados com valores ausentes (*NA*) de massa corporal e/ou comprimento da nadadeira e o ggplot2 não tem como representá-los no gráfico sem esses dois valores.
```

2023-09-17 16:42 UTC, beatrizmilz commented on data-visualize.qmd
> +Assim como o R, o ggplot2 adota a filosofia de que os valores ausentes nunca devem desaparecer silenciosamente.
```suggestion
Assim como o R, o ggplot2 adota a filosofia de que os valores faltantes nunca devem desaparecer silenciosamente.
```

2023-09-17 16:42 UTC, beatrizmilz commented on data-visualize.qmd
> +Esse tipo de aviso é provavelmente um dos tipos mais comuns de avisos que você verá ao trabalhar com dados reais - os valores ausentes são um problema muito comum e você aprenderá mais sobre eles ao
```suggestion
Esse tipo de aviso é provavelmente um dos tipos mais comuns de avisos que você verá ao trabalhar com dados reais - os valores faltantes são um problema muito comum e você aprenderá mais sobre eles ao longo do livro, especialmente em @sec-missing-values.
```

2023-09-17 16:44 UTC, beatrizmilz commented on data-visualize.qmd
> +Nos demais gráficos deste capítulo, suprimiuprimir esse aviso para que ele não seja mostrado em cada gráfico que fizermos.
```suggestion
Nos demais gráficos deste capítulo, vamos suprimir esse aviso para que ele não seja mostrado em cada gráfico que fizermos.
```

2023-09-17 16:47 UTC, beatrizmilz commented on data-visualize.qmd
> +Gráficos de dispersão são úteis para exibir a relação entre duas variáveis numéricas, mas é sempre uma boa ideia ser cético em relação a qualquer relação aparente entre duas variáveis e perguntar se
```suggestion
Gráficos de dispersão são úteis para exibir a relação entre duas variáveis numéricas, mas é sempre uma boa ideia ter uma postura cético em relação a qualquer relação aparente entre duas variáveis e perguntar se pode haver outras variáveis que expliquem ou mudem a natureza dessa relação aparente.
```

2023-09-17 17:01 UTC, beatrizmilz commented on data-visualize.qmd
> +Normalmente, o primeiro ou os dois primeiros argumentos de uma função são tão importantes que você deve sabê-los de cor.
```suggestion
Normalmente, o primeiro ou os dois primeiros argumentos de uma função são tão importantes que você logo saberá usar eles de cor.
```

2023-09-17 17:02 UTC, beatrizmilz commented on data-visualize.qmd
> +Normalmente, o primeiro ou os dois primeiros argumentos de uma função são tão importantes que você deve sabê-los de cor.
Essa minha sugestão muda um pouco do sentido da frase, e é uma questão pessoal minha... sinto que o "deve" fica muito pesado!

2023-09-17 17:03 UTC, beatrizmilz commented on data-visualize.qmd
> +Os dois primeiros argumentos de `ggplot()` são `data` e `mapping`; no restante do livro, não forneceremos esses nomes.
```suggestion
Os dois primeiros argumentos de `ggplot()` são `data` e `mapping`; no restante do livro, não escreveremos esses nomes.
```

2023-09-17 17:11 UTC, beatrizmilz commented on data-visualize.qmd
> +Um gráfico de densidade é uma versão suavizada de um histograma e uma alternativa prática, especialmente para dados contínuos provenientes de uma distribuição suavizada subjacente.
eu achei meio confuso o que quer dizer com o "distribuição suavizada subjacente"

2023-09-17 17:14 UTC, beatrizmilz commented on data-visualize.qmd
> +Ela mostra menos detalhes do que um histograma, mas pode facilitar a obtenção rápida da forma da distribuição, principalmente com relação aos modos e à assimetria.
Acho que modes aqui está falando dos números mais frequentes, não?
```suggestion
Ela mostra menos detalhes do que um histograma, mas pode facilitar a obtenção rápida da forma da distribuição, principalmente com relação à moda (valor que ocorre com maior frequência) e à assimetria.
```

2023-09-17 17:15 UTC, beatrizmilz commented on data-visualize.qmd
> +Nas seções a seguir, você aprenderá sobre os gráficos comumente usados para visualizar relações entre duas ou mais variáveis e os geoms usados para criá-los.
```suggestion
Nas seções a seguir, você aprenderá sobre os gráficos comumente usados para visualizar relações entre duas ou mais variáveis e as geometrias usados para criá-los.
```

2023-09-17 17:43 UTC, beatrizmilz commented on data-visualize.qmd
> +-   Uma linha que se estende de cada extremidade da caixa e vai até o ponto mais distante sem *outlier* na distribuição.
```suggestion
-   Uma linha que se estende de cada extremidade da caixa e vai até o ponto mais distante (sem considerar os valores discrepantes - *outliers*) na distribuição.
```

2023-09-17 17:43 UTC, beatrizmilz commented on data-visualize.qmd
> +No gráfico a seguir, ela está *definida* como 0,5.
```suggestion
No gráfico a seguir, ela está *definida* como 0.5.
```

2023-09-17 17:44 UTC, beatrizmilz commented on data-visualize.qmd
> +-   Nós *mapeamos* variáveis para atributos estéticos se quisermos que o atributo visual representado por esse atributo varie com base nos valores dessa variável.
```suggestion
-   Nós *mapeamos* variáveis para atributos estéticos se quisermos que o atributo visual representado por esse atributo varie de acordo com os valores dessa variável.
```

2023-09-17 17:45 UTC, beatrizmilz commented on data-visualize.qmd
> +-   Caso contrário, nós *definimos* o valor de um atributo estético.
```suggestion
-   Caso contrário, nós **definimos** o valor de um atributo estético.
```

2023-09-17 17:46 UTC, beatrizmilz commented on data-visualize.qmd
> +O segundo gráfico é um gráfico de frequência relativa, criado pela definição de `position = "fill"` na geom, que é mais útil para comparar as distribuições de espécies entre as ilhas, pois não é afet
```suggestion
O segundo gráfico é um gráfico de frequência relativa, criado pela definição de `position = "fill"` na geometria, que é mais útil para comparar as distribuições de espécies entre as ilhas, pois não é afetado pelo número desigual de pinguins entre as ilhas.
```
"na geom" pra mim fica estranho mas tbm não sei como é a melhor forma..

2023-09-17 17:47 UTC, beatrizmilz commented on data-visualize.qmd
> +Usando esse gráfico, podemos ver que todos os Pinguim-gentoo vivem na ilha Biscoe e constituem aproximadamente 75% dos pinguins dessa ilha, todos os Pinguim-de-barbicha vivem na ilha Dream e constitu
```suggestion
Usando esse gráfico, podemos ver que todos os Pinguim-gentoo vivem na ilha Biscoe e constituem aproximadamente 75% dos pinguins dessa ilha, todos os Pinguim-de-barbicha vivem na ilha Dream e constituem aproximadamente 50% dos pinguins dessa ilha, e os Pinguim-de-adélia vivem nas três ilhas e constituem todos os pinguins da ilha Torgersen.
```

2023-09-17 17:49 UTC, beatrizmilz commented on data-visualize.qmd
> +Outra maneira, que é particularmente útil para variáveis categóricas, é dividir seu gráfico em **facetas**, subdivisões que exibem um subconjunto dos dados cada uma.
```suggestion
Outra maneira, que é particularmente útil para variáveis categóricas, é dividir seu gráfico em **facetas** (*facets*), subdivisões que exibem um subconjunto dos dados cada uma.
```

2023-09-17 17:53 UTC, beatrizmilz commented on data-visualize.qmd
> +Essa é a função de `ggsave()`, que salvará no computador o gráfico criado mais recentemente:
```suggestion
Esse é o objetido da função `ggsave()`, que salvará no computador o gráfico criado mais recentemente:
```

2023-09-17 17:54 UTC, beatrizmilz commented on data-visualize.qmd
> +Você pode obter mais informações sobre `ggsave()` na documentação.
```suggestion
Você pode obter mais informações sobre a função `ggsave()` na documentação.
```

2023-09-17 18:07 UTC, beatrizmilz commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
Acho que em vez de "autoria", poderia ser "escrita". 
sobre o termo original usado (reproducible), acho que o principal é a ideia de poder "gerar novamente" o arquivo e ter os mesmos resultados..
por mais que o quarto seja uma ferramenta de escrita técnica e científica, nem todas as ferramentas de escrita técnica e científica geram arquivos reprodutíveis, certo?

Eu acho que a sugestão do @nextmarte fica mais fácil de entender, mas tbm sai um pouco do sentido do termo original dos autores (reproducible).

em resumo: não sei o que é melhor HAHHAHA

@clente qual é a sua opinião, grande mestre?

2023-09-17 18:08 UTC, beatrizmilz commented on data-visualize.qmd
> +Você saberá mais sobre o Quarto em @sec-quarto.
```suggestion
Você aprenderá mais sobre o Quarto em @sec-quarto.
```

2023-09-17 18:10 UTC, beatrizmilz commented on data-visualize.qmd
> +Se você ainda estiver com dificuldades, tente a ajuda.
```suggestion
Se você ainda estiver com dificuldades, tente a ajuda (painel *Help*).
```

2023-09-17 18:11 UTC, beatrizmilz commented on data-visualize.qmd
> +Mas quando você é novo no R, mesmo que a resposta esteja na mensagem de erro, talvez você ainda não saiba como entendê-la.
```suggestion
Mas quando você é iniciante no R, mesmo que a resposta esteja na mensagem de erro, talvez você ainda não saiba como entendê-la.
```

2023-09-17 18:12 UTC, beatrizmilz commented on data-visualize.qmd
> +Você também aprendeu sobre gráficos comumente usados para visualizar a distribuição de uma única variável, bem como para visualizar relações entre duas ou mais variáveis ao utilizar mapeamentos de at
```suggestion
Você também aprendeu sobre gráficos comumente usados para visualizar a distribuição de uma única variável, bem como para visualizar relações entre duas ou mais variáveis ao utilizar mapeamentos de atributos estéticos adicionais e/ou dividindo seu gráfico em pequenos gráficos usando facetas (*facets*).
```

2023-09-17 18:12 UTC, beatrizmilz commented on data-visualize.qmd
> +Você também aprendeu sobre gráficos comumente usados para visualizar a distribuição de uma única variável, bem como para visualizar relações entre duas ou mais variáveis ao utilizar mapeamentos de at
não sei se ficou boa a sugestão. mas tá confuso pra mim a forma original

2023-09-17 18:13 UTC, beatrizmilz commented on data-visualize.qmd
> +Intercalamos conselhos sobre fluxo de trabalho com ferramentas de ciência de dados ao longo desta parte do livro, pois isso o ajudará a se manter organizado à medida que você escreve quantidades cada
```suggestion
Intercalamos conselhos sobre fluxo de trabalho com ferramentas de ciência de dados ao longo desta parte do livro, pois isso te ajudará a se manter organizado à medida que você escreve quantidades cada vez maiores de código em R.
```

2023-09-17 18:14 UTC, beatrizmilz commented
Uhul! terminei de passar pelo arquivo todo :D

2023-09-18 13:06 UTC, nextmarte commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
"Um sistema de escrita técnico-científica que permite reprodutibilidade, ou seja, permite que outras pessoas consigam reproduzir o que foi escrito" 

O que vocês acham?

2023-09-18 15:51 UTC, clente commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
Neste contexto, "técnico-científica" foge do significado original; podemos usar o Quarto para qualquer coisa, mesmo escrita que não seja técnico-científica.

Eu pessoalmente traduziria como "escrita reprodutível", mas também sou favorável ao "autoria reproduzível" original (ambos "reprodutível" e "reproduzível" são válidos). A @rmhirota sugeriu "criação" ao invés de "escrita" ou "autoria".

2023-09-26 13:37 UTC, brunomioto commented on data-visualize.qmd
> +De modo geral, entretanto, recomendamos que você monte seus relatórios finais usando o Quarto, um sistema de autoria reproduzível que permite intercalar seu código e sua escrita e incluir automaticam
Concordo que "técnico-científica" foge do significado pois muitos utilizam o Quarto para fazer sites, tutoriais, etc.
Deixei "escrita reprodutível" pois engloba todos estes significados.

2023-09-26 20:16 UTC, brunomioto commented
@nextmarte e @beatrizmilz Corrigi a tradução de acordo com as revisões de vocês.
Aproveitei e traduzi os alt-text também. Se puderem revisar, agradeço.
Eles são meio chatos de traduzir por causa do `|#` e diversas repetições, posso ter deixado algo passar.

Obrigado!!

2023-10-08 19:05 UTC, beatrizmilz reviewed
São coisas bem pequenas! Apenas no alt text das figuras

2023-10-08 19:05 UTC, beatrizmilz commented on data-visualize.qmd
> +#|   Um gráfico de dispersão da massa corporal em função o comprimento da
```suggestion
#|   Um gráfico de dispersão da massa corporal em função do comprimento da
```

2023-10-08 19:05 UTC, beatrizmilz commented on data-visualize.qmd
> +#|   Pinguim-gentoo) é representada por um contorno colorido diferente em #|   cada curva de densidade.
```suggestion
#|   Pinguim-gentoo) é representada por um contorno colorido diferente em
#|   cada curva de densidade.
```
aqui também é só uma quebra de linha

2023-10-08 19:05 UTC, beatrizmilz commented on data-visualize.qmd
> +#|   Pinguim-gentoo) é representada por um contorno colorido diferente em #|   cada curva de densidade. As curvas de densidade também são
```suggestion
#|   Pinguim-gentoo) é representada por um contorno colorido diferente em 
#|   cada curva de densidade. As curvas de densidade também são 
```
quebrando linha

2023-10-09 14:16 UTC, nextmarte requested changes
Dei mais uma lida mas acho que a @beatrizmilz pegou os mesmos pontos, além disso, só uma sugestão de tradução de fig-cap.

2023-10-09 14:16 UTC, nextmarte commented on data-visualize.qmd
> +#|   Diagrama sobre como um boxplot é criado.
```suggestion
#|   Diagrama mostrando como um boxplot é criado.
```

2023-10-09 15:29 UTC, brunomioto commented
Feito! Obrigado pelas correções @beatrizmilz e @nextmarte !

2023-10-09 17:51 UTC, beatrizmilz commented
Obrigada pela tradução @brunomioto !

2023-10-09 17:51 UTC, merged