Traducção 13 - visualize.qmd
cienciadedatos/pt-r4ds pull request #53
Opened 2023-11-16 16:44 UTC by brunomioto

2023-11-16 16:56 UTC, beatrizmilz reviewed
🚀

2023-11-16 16:56 UTC, beatrizmilz commented on visualize.qmd
> +O melhor lugar para aprender mais é o livro ggplot2: [*ggplot2: Elegant graphics for data analysis*](https://ggplot2-book.org/).
```suggestion
O melhor lugar para aprender mais é o livro sobre o ggplot2: [*ggplot2: Elegant graphics for data analysis*](https://ggplot2-book.org/).
```

2023-11-16 16:58 UTC, brunomioto commented on visualize.qmd
> +Este livro aprofunda muito mais a teoria subjacente e tem muitos exemplos de como combinar as peças individuais para resolver problemas práticos.
Sim, fiquei nessa também :/

2023-11-16 18:56 UTC, beatrizmilz commented on visualize.qmd
> +Este livro aprofunda muito mais a teoria subjacente e tem muitos exemplos de como combinar as peças individuais para resolver problemas práticos.
"os componentes do ggplot2" ? 😆

2023-11-17 13:40 UTC, scopinho commented
@beatrizmilz , pode me colocar como revisor desse tb.

2023-11-17 13:50 UTC, scopinho requested changes
@brunomioto / @beatrizmilz . Fiz a revisão do .qmd.

2023-11-17 13:50 UTC, scopinho commented on visualize.qmd
> +Este livro aprofunda muito mais a teoria subjacente e tem muitos exemplos de como combinar as peças individuais para resolver problemas práticos.
```suggestion
Este livro aprofunda muito mais a teoria subjacente e tem muitos exemplos de como combinar as diversas funções do pacote para resolver problemas práticos.
```

2023-11-17 13:50 UTC, scopinho commented on visualize.qmd
> +Este livro aprofunda muito mais a teoria subjacente e tem muitos exemplos de como combinar as peças individuais para resolver problemas práticos.
Não sei se ficou muito 'livre', mas me parece fazer mais sentido para um leitor iniciante.

2023-11-17 14:45 UTC, brunomioto commented
Obrigado @scopinho !

P.S. @beatrizmilz estraguei algo do yaml que eu devo ter feito o commit sem querer, ignore esse arquivo por favor se for possível.

2023-11-17 14:47 UTC, merged