Tradução: program.qmd
cienciadedatos/pt-r4ds pull request #55
Opened 2023-11-17 18:13 UTC by ligialouzada

Revisores: fiquei na dúvida de como traduzir "you’ll see in the wild" (linha 46). Escrevi "por aí" mas talvez tenha ficado muito informal.

2023-11-17 20:13 UTC, beatrizmilz reviewed
Ótimo!! 🚀

2023-11-17 20:13 UTC, beatrizmilz commented on program.qmd
> +    No @sec-base-r, você irá aprender algumas das funções mais importantes do R base que você vê por aí.
```suggestion
    No @sec-base-r, você irá aprender algumas das funções mais importantes do R base que você verá por aí.
```

2023-11-17 20:13 UTC, beatrizmilz commented on program.qmd
> +Quando você dominar esse material, recomendamos fortemente que você continue a investir em suas habilidades de programação.
```suggestion
Quando você dominar esse material, recomendamos fortemente que você continue a investir nas suas habilidades de programação.
```

2023-11-20 20:02 UTC, scopinho commented on program.qmd
> +Programação é uma competência transversal para todo trabalho de ciência de dados: você deve usar o computador para fazer ciência de dados; você não pode fazê-la em sua cabeça, com lápis e papel.
Apesar de a tradução literal não ser a mesma, achei que "essencial" faria mais sentido para o leitor em portugues. O que acham?

2023-11-20 20:10 UTC, scopinho commented on program.qmd
> +[*Hands on Programming with R*](https://rstudio-education.github.io/hopr/), de Garrett Grolemund, é uma introdução a R como linguagem de programação e um ótimo ponto de partida se R é sua primeira li
```suggestion
[*Hands on Programming with R*](https://rstudio-education.github.io/hopr/), de Garrett Grolemund, é uma introdução ao R como linguagem de programação e um ótimo ponto de partida se o R for sua primeira linguagem de programação.
```

2023-11-20 20:11 UTC, scopinho commented on program.qmd
> +[*Advanced R*](https://adv-r.hadley.nz/) de Hadley Wickham entra em detalhes na linguagem de programação R; é um ótimo ponto de partida se você já tem experiência em programação e ótimo próximo passo
```suggestion
[*Advanced R*](https://adv-r.hadley.nz/) de Hadley Wickham entra em detalhes na linguagem de programação R; é um ótimo ponto de partida se você já tem experiência em programação e ótimo próximo passo se você já estiver familiarizado com as ideias desses capítulos.
```

2023-11-21 12:57 UTC, scopinho requested changes
Notei que no cap. "whole-game" usamos **organizar** ao invés de _arrumar_.

2023-11-21 12:57 UTC, scopinho commented on program.qmd
> +#|   arrumar, transformar, visualizar, modelar e comunicar, ou seja, tudo)
```suggestion
#|   organizar, transformar, visualizar, modelar e comunicar, ou seja, tudo)
```

2023-11-21 14:53 UTC, ligialouzada commented on program.qmd
> +Programação é uma competência transversal para todo trabalho de ciência de dados: você deve usar o computador para fazer ciência de dados; você não pode fazê-la em sua cabeça, com lápis e papel.
Inicialmente tinha pensado por aí tb. Mas refletindo um pouco, eu acho que o que ele quer dizer é que a programação é uma competência que permeia todo o trabalho, no sentido de "percorrer" todo o processo / estar sempre presente. Acho que é um pouco mais além que "essencial", por isso mantive a tradução como "transversal". Faz sentido?

2023-11-21 15:11 UTC, scopinho commented on program.qmd
> +Programação é uma competência transversal para todo trabalho de ciência de dados: você deve usar o computador para fazer ciência de dados; você não pode fazê-la em sua cabeça, com lápis e papel.
Entendi, mas acho que transversal não é um termo comum aplicado nestes casos pelo leitor em PT. Deixamos assim e quem sabe alguém aparece com alguma outra sugestão. 😉

2023-11-21 23:44 UTC, beatrizmilz commented on program.qmd
> +Escrever códigos claros é importante para que outros (como você do futuro) possam entender o porquê de você ter abordado uma análise da forma como fez.
```suggestion
Escrever códigos claros é importante para que outras pessoas (como você do futuro) possam entender o porquê de você ter abordado uma análise da forma como fez.
```

2023-11-21 23:45 UTC, beatrizmilz commented on program.qmd
> +Programação é uma competência transversal para todo trabalho de ciência de dados: você deve usar o computador para fazer ciência de dados; você não pode fazê-la em sua cabeça, com lápis e papel.
Eu também entendi como a Lígia! É uma competência presente em todas as etapas

2023-11-21 23:50 UTC, beatrizmilz commented on program.qmd
> +[*Advanced R*](https://adv-r.hadley.nz/) de Hadley Wickham entra em detalhes na linguagem de programação R; é um ótimo ponto de partida se você já tem experiência em programação e ótimo próximo passo
```suggestion
[*Advanced R*](https://adv-r.hadley.nz/) de Hadley Wickham entra em detalhes na linguagem de programação R; é um ótimo ponto de partida se você já tem experiência em programação e ótimo próximo passo se as ideias desses capítulos forem familiares para você.
```

Tentando reescrever sem marcar o gênero na palavra "familiarizad**o**". acham que a leitura está ok? @ligialouzada @scopinho

2023-11-21 23:51 UTC, beatrizmilz commented on program.qmd
> +Escrever códigos claros é importante para que outras pessoas (como você do futuro) possam entender o porquê de você ter abordado uma análise da forma como fez.
```suggestion
Escrever códigos claros é importante para que outras pessoas (como você no futuro) possam entender o porquê de você ter abordado uma análise da forma como fez.
```

@scopinho você adicionou o "como **o** você", esse **o** é necessário?

2023-11-22 01:50 UTC, scopinho commented on program.qmd
> +[*Advanced R*](https://adv-r.hadley.nz/) de Hadley Wickham entra em detalhes na linguagem de programação R; é um ótimo ponto de partida se você já tem experiência em programação e ótimo próximo passo
Faz sentido sim @beatrizmilz

2023-11-22 01:53 UTC, scopinho commented on program.qmd
> +Escrever códigos claros é importante para que outras pessoas (como você do futuro) possam entender o porquê de você ter abordado uma análise da forma como fez.
Não sei dizer se é necessário, mas pelas aparições no google (procurar por "o você do futuro" e "você do futuro", esse **o** aparece mais nos textos, apesar se não ver problema sem deixarmos sem também.

2023-11-22 11:00 UTC, merged