Tradução: transform.qmd
cienciadedatos/pt-r4ds pull request #56
Opened 2023-11-18 16:53 UTC by arianacabral

**Adicionando a tradução inicial do capítulo transform.qmd [#17]**

Eu fiz a tradução apenas do conteúdo mesmo do capítulo, sem alterar as referências cruzadas ou os elementos no `.yml` para deixá-los em português também.

Eu senti a necessidade de adaptar a tradução de alguns trechos pontuais para melhorar a compreensão.  Por exemplo, quando  é mencionada a ideia de chaves (`keys`).  Mas, sinta-se à vontade para fazer as considerações e alterações que julgar pertinente no documento. 

Espero ter contribuído com a tradução dessa parte do livro  e estou à disposição para fazer revisões dessa parte se for necessário😊

2023-11-19 13:07 UTC, beatrizmilz commented on transform.qmd
> +-   O @sec-strings fornece as ferramentas necessárias para trabalhar com cadeias de caracteres (*strings*): você conseguirá extrair partes de uma *string*, separar uma *string* em vários caracteres e
```suggestion
-   O @sec-strings fornece as ferramentas necessárias para trabalhar com cadeias de caracteres (*strings*): você conseguirá extrair partes de uma *string*, separar uma *string* em vários caracteres e concatená-los para gerar uma *string* novamente.
```

2023-11-19 13:07 UTC, beatrizmilz commented on transform.qmd
> +    Este capítulo fará com que você saía da fase de pensar que um um gato caminhou sobre o seu teclado e passe a ler e escrever com facilidade padrões complexos de *strings*.
```suggestion
    Este capítulo fará com que você saia da fase de pensar que um um gato caminhou sobre o seu teclado e passe a ler e escrever com facilidade padrões complexos de *strings*.
```

2023-11-19 13:07 UTC, beatrizmilz commented on transform.qmd
> +    Este capítulo fará com que você saía da fase de pensar que um um gato caminhou sobre o seu teclado e passe a ler e escrever com facilidade padrões complexos de *strings*.
hahahhahaa adorei essa frase dele!!! é como me sinto escrevendo regex...

2023-11-19 13:07 UTC, beatrizmilz commented on transform.qmd
> +    Entender sobre junções fará com que você assimile o conceito de chaves de banco de dados e pense sobre como identificar cada linha em um conjunto de dados.
```suggestion
    Entender sobre *joins* fará com que você assimile o conceito de chaves (*keys*) de banco de dados e pense sobre como identificar cada linha em um conjunto de dados.
```

2023-11-19 13:08 UTC, beatrizmilz commented
Oi Ari!! Ficou ótimo!
Fiz algumas sugestões, veja se faz sentido pra você!

2023-11-20 13:50 UTC, arianacabral commented on transform.qmd
> +#|   Nosso modelo de ciência de dados com 'transform' destacado em azul.
Não havia prestado atenção a esse detalhe. Da próxima vez, vou lembrar de deixar como verbo.

2023-11-20 14:04 UTC, arianacabral commented
Oi, Bea! 

Achei muito pertinentes as sugestões pontuadas. Vou incluí-las e fazer um PR 😉

2023-11-20 14:07 UTC, beatrizmilz commented
> Oi, Bea!
> 
> Achei muito pertinentes as sugestões pontuadas. Vou incluí-las e fazer um PR 😉
Oiee! Você não precisa fazer um novo PR, pode aceitar as sugestões por aqui mesmo :D

Para as. sugestões que fizerem sentido pra vc, vc pode clicar em "commit suggestion":
![imagem](https://github.com/cienciadedatos/pt-r4ds/assets/42153618/c52cfae4-417b-4029-813a-0b811ffd95c6)

2023-11-20 14:18 UTC, arianacabral commented
Prontinho!!! 😁 

Muito obrigada, Bea!!!

2023-11-20 14:19 UTC, beatrizmilz commented
> Prontinho!!! 😁
> 
> Muito obrigada, Bea!!!

Obrigada você :D

2023-11-20 19:46 UTC, scopinho commented
Olá @arianacabral / @beatrizmilz , posso fazer a revisão deste também.

2023-11-20 19:56 UTC, scopinho requested changes
Fiz uma revisão. Ajuste mínimo incluíndo "uniões" (*joins*). Excelente tradução @arianacabral ! Parabéns!

2023-11-20 19:56 UTC, scopinho commented on transform.qmd
> +    Entender sobre *joins* fará com que você assimile o conceito de chaves (*keys*) de banco de dados e pense sobre como identificar cada linha em um conjunto de dados.
```suggestion
    Entender sobre uniões (*joins*) fará com que você assimile o conceito de chaves (*keys*) de banco de dados e pense sobre como identificar cada linha em um conjunto de dados.
```

2023-11-21 13:20 UTC, arianacabral commented
Contribuições sempre são bem-vindas para melhorar o material. 

Muito obrigada pela sugestão, @scopinho!!! Eu já a aceitei.  😁

Aí, @beatrizmilz só confirma se acha válida também, por favor.

2023-11-21 23:53 UTC, beatrizmilz commented
Ficou ótimo!! Obrigada @arianacabral e @scopinho !!

2023-11-21 23:53 UTC, merged