Tradução: spreadsheets.qmd
cienciadedatos/pt-r4ds pull request #58
Opened 2023-11-22 03:00 UTC by scopinho

Capítulo longo sobre importação de dados (Excel e Google Sheets).
Observações Importantes:

1-) Worksheet e Spreadsheet aparecem com sentido de "planilha" e de "arquivo" em alguns lugares. Utilizei:
worksheet = Planilhas
spreadsheet = Arquivo do Excel
Em alguns casos, se apresentam como sinônimo do que usamos como "aba" em PT.

2-) Há arquivos Excel/Google externos/publicos utilizados nos exemplos de importação.
Eles estão em inglês, fiz uma tradução aqui no .qmd, mas precisamos definir a estratégia de tradução e armazenamento dos mesmos: 

Lista de arquivos externos:
- data/students.xlsx = data/estudantes.xlsx (students também daqui https://docs.google.com/spreadsheets/d/1V1nPp1tzOuutXFLb3G9Eyxi3qxeEhnOXUzL5_BcCQ0w ) 
- data/penguins.xlsx = data/pinguins.xlsx (palmerpenguins também daqui https://docs.google.com/spreadsheets/d/1aFu8lnD_g0yjF5O-K6SFgSEWiHPpgvFCF0NY9D6LXnY/ e também daqui https://pos.it/r4ds-penguins)
- data/deaths.xlsx = data/obitos.xlsx
- data/bake-sale.xlsx = data/doces-vendas.xlsx
- data/survey.xlsx = data/pesquisa.xlsx (survey também daqui https://docs.google.com/spreadsheets/d/1yc5gL-a2OOBr8M7B3IsDNX5uR17vBHOyWZq6xSTG2G8 ) , survey também daqui (https://pos.it/r4ds-survey)
- data/roster.xlsx = data/lista.xlsx (roster em Excel de https://docs.google.com/spreadsheets/d/1LgZ0Bkg9d_NK8uTdP2uHXm07kAlwx8-Ictf8NocebIE ), também daqui: https://pos.it/r4ds-roster)
-data/sales.xlsx = data/vendas.xlsx (sales também daqui: https://docs.google.com/spreadsheets/d/1oCqdXUNO8JR3Pca8fHfiz_WXWxMuZAp3YiYFaKze5V0 )

3-) O pacote **readxl** tem um arquivo Excel exemplo '_deaths.xlsx_'. Precisamos definir se iremos criar um pacote nos moldes do "dados", incluí-lo no mesmo traduzido ou não traduzir.

4-) No primeiro exercício, acho que a **descrição da imagem em Inglês está errada**, pois repete no exercício 2. Fiz uma tradução livre em PT.

5) Na frase "therefore other tasks may require further updates to the function calls", acabei optando por "por isso, algumas chamadas de funções podem ser diferentes" para fazer mais sentido em PT.

6) No exemplo do Google Sheets, ele possui uma função **gs4_examples**() que carrega a planilha "deaths". No caso do **readxl_examples**() é a mesmo coisa pro arquivo Excel. Também precisaremos definir uma estratégia para estes casos (ex: traduzir, não traduzir, como as funções podem ler de outro lugar traduzido, onde armazenar, etc. 

7) Os termos _read_ e _write_ foram traduzidos como "**importar**" e "**exportar**" ao invés de ler e gravar na maioria dos casos, pois achei que faziam mais sentido nas frases depois de traduzidas.

2023-11-23 12:43 UTC, decarvaa commented
@scopinho e @beatrizmilz, posso revisar esse aqui tambem!

2024-03-31 23:39 UTC, beatrizmilz commented
> @scopinho e @beatrizmilz, posso revisar esse aqui tambem!

Boa! Caso precise de alguma coisa, pode avisar! Muito obrigada!

2024-04-09 23:45 UTC, carlossb1 commented
opa! posso ser o segundo revisor?

2024-04-10 00:06 UTC, beatrizmilz commented
Claro! Muito obrigada @carlossb1

2024-04-10 15:58 UTC, carlossb1 requested changes
Fala pessoal, a tradução ficou mt boa!

Segue a sugestão dos itens que achei interessante alterar ou que tinham algum errinho de digitação.

Fui até a linha 121 nesse primeiro momento, assim que conseguir completar a revisão eu sinalizo pra vocês aqui nos comentários.

2024-04-10 16:05 UTC, carlossb1 requested changes

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +As boas práticas presentes neste artigo evitarão dores de cabeça quando importar dados de planilhas para o R para analisá-los e visualizá-los.
```suggestion
As boas práticas presentes neste artigo evitarão dores de cabeça ao importar dados de planilhas para análise e visualização com o R.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +Microsoft Excel é um software de planilha muito utilizado onde os dados são organizados em planilhas (*worksheets*) dentro de arquivos Excel (*spreadsheet*).
```suggestion
Microsoft Excel é um software de planilha muito utilizado onde os dados são organizados em planilhas (*worksheets*) dentro de arquivos Excel (*spreadsheet*).
```
```suggestion
O Microsoft Excel é um software muito utilizado onde os dados são organizados em planilhas (*worksheets*) dentro de arquivos Excel (*spreadsheet*).
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +-   `read_xls()` importa arquivos Excel no format `xls`.
```suggestion
-   `read_xls()` importa arquivos Excel que estejam no format `xls`.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +-   `read_xlsx()` importa arquivos Excel no formato `xlsx`.
```suggestion
-   `read_xlsx()` importa arquivos Excel que estejam no formato `xlsx`.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +-   `read_excel()` pode importar arquivos do Excel nos formatos `xls` e `xlsx`. Ela identifica o formato baseado no tipo de arquivo de entrada.
```suggestion
-   `read_excel()` pode importar arquivos em ambos os formatos `xls` e `xlsx`. Ela identifica o formato baseado no tipo de arquivo de entrada.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +Estas funções possuem uma sintaxe similar à outras funções introduzidas anteriormente para importar outros tipos de arquivos, ex: `read_csv()`, `read_table()`, etc.
```suggestion
Estas funções possuem uma sintaxe similar à outras funções introduzidas anteriormente para importar outros tipos de arquivos, ex: `read_csv()`, `read_table()`, etc.
```
```suggestion
Estas funções possuem uma sintaxe similar às outras funções introduzidas anteriormente para importar outros tipos de arquivos, ex: `read_csv()`, `read_table()`, etc.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +#|   informações de 6 estudantes, seus IDs, nomes completos, comida favorita, plano de refeição
```suggestion
#|   informações de 6 estudantes, seus IDs, nomes completos, comida favorita, plano alimentar
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +Entretanto, existem algumas coisas que devemos endereçar neste conjunto de dados:
```suggestion
Entretanto, existem algumas coisas que devemos abordar neste conjunto de dados:
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +    Infelizmente, apenas isto não faz o serviço completo.
```suggestion
    Infelizmente, apenas isto não é o suficiente.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +    Temos agora o nome das variáveis como gostaríamos, mas o que era anteriormente a linha de cabeçalho aparece nos dados como a primeira linha das observações.
```suggestion
    Temos agora o nome das variáveis como gostaríamos, mas o que era anteriormente a linha de cabeçalho passou a aparecer nos dados como a primeira linha das observações.
```

2024-04-10 16:05 UTC, carlossb1 commented on spreadsheets.qmd
> +2.  Na coluna `comida_favorita`, uma das observações está como `N/A`, que significa "não disponível" (*not available*) mas não é reconhecida um valor não disponível (`NA`) do R (veja a diferença entr
```suggestion
2.  Na coluna `comida_favorita`, uma das observações está como `N/A`, que significa "não disponível" (*not available*) mas essa forma não é reconhecida como um valor não disponível (`NA`) do R (veja a diferença entre este `N/A` e o presente na `idade` do quarto estudante da lista).
```

2024-04-10 16:11 UTC, carlossb1 commented
Fala pessoal, a tradução ficou mto boa! 

Fui até a linha 121 nesse primeiro momento, assim que concluir eu sinalizo pra vocês aqui nos comentários

2024-04-11 15:51 UTC, carlossb1 commented on spreadsheets.qmd
> +A @fig-deaths-excel mostra uma planilha: no centro da planilha temos algo que se parece com um *data frame*, mas existem estranhos textos extras acima e abaixo dos dados.
```suggestion
A @fig-deaths-excel mostra um exemplo: no centro da planilha temos algo que se parece com um *data frame*, mas existem estranhos textos acima e abaixo dos dados.
```

2024-04-11 15:51 UTC, carlossb1 commented on spreadsheets.qmd
> +Cada planilha tem o mesmo número de colunas, mas diferente número de linhas.
```suggestion
Cada planilha tem o mesmo número de colunas, mas diferentes números de linhas.
```

2024-04-11 15:51 UTC, carlossb1 commented on spreadsheets.qmd
> +Alternativamente, você pode usar `excel_sheets()` para obter informações de todas as planilhas presentes em um arquivo Excel, e então importar aquela(s) que você está interesado.
```suggestion
Alternativamente, você pode usar `excel_sheets()` para obter informações de todas as planilhas presentes em um arquivo Excel, e então importar aquela(s) em que você está interessado.
```

2024-04-11 15:51 UTC, carlossb1 commented on spreadsheets.qmd
> +Ciência de dados é um processo iterativo, e este processo de iteração pode ser ainda mais entediante quando importamos dados de planilhas se comparado a quando importamos dados de arquivos textos (da
```suggestion
A ciência de dados é um processo iterativo, e este processo de iteração pode ser ainda mais entediante quando importamos dados de planilhas se comparado a quando importamos dados de arquivos textos (dados retangulares) pois os humanos tendem a inserir dados nas planilhas e usá-las não apenas para armazenar os dados, mas também para compartilhamento e communicação.
```

2024-04-11 15:51 UTC, carlossb1 commented on spreadsheets.qmd
> +    Você pode definir quais cadeias de caracteres (*strings*) devem ser reconhecidas como `NA` com o argumento `na`.
```suggestion
    Você pode definir quais cadeias de caracteres (*strings*) devem ser reconhecidas pelo R como `NA` utilizando o argumento `na`.
```

2024-04-11 15:53 UTC, carlossb1 commented on spreadsheets.qmd
> +#|   ou não, data de nascimento e óbito. Na parte debaixo, existem outras 4 linhas
```suggestion
#|   ou não, data de nascimento e óbito. Na parte de baixo, existem outras 4 linhas 
```

2024-04-11 15:54 UTC, carlossb1 commented on spreadsheets.qmd
> +#|   estamos nos descontando agora!' está espalhado por estas quatro linhas finais.
```suggestion
#|   estamos nos desconectando agora!' está espalhado por estas quatro linhas finais.
```

2024-04-11 15:55 UTC, carlossb1 commented on spreadsheets.qmd
> +É possível elminar estas linhas extras usando os argumentos `skip` e `n_max`, mas recomendamos utilizar intervalo (*range*) de células.
```suggestion
É possível eliminar estas linhas extras usando os argumentos `skip` e `n_max`, mas recomendamos utilizar intervalos (*range*) de células.
```

2024-04-11 15:56 UTC, carlossb1 commented on spreadsheets.qmd
> +Aqui, os dados que desejamos importar começa na célula `A5` e termina na célula `F15`.
```suggestion
Aqui, os dados que desejamos importar começam na célula `A5` e terminam na célula `F15`.
```

2024-04-11 16:04 UTC, carlossb1 requested changes
Segue a continuação da revisão, fui até a linha 287

2024-04-12 16:29 UTC, carlossb1 commented on spreadsheets.qmd
> +Da mesma maneira, datas são na verdade armazenadas como números, especificamente número de segundos desde 1o de Janeiro de 1970.
```suggestion
Da mesma maneira, datas são na verdade armazenadas como números, especificamente número de segundos desde 1º de Janeiro de 1970.
```

2024-04-12 16:30 UTC, carlossb1 commented on spreadsheets.qmd
> +Estas diferenças em como os dados intrínsecos são armazenados vs. como eles são mostrados na tela podem causar surpresas quando os dados são importados para o R..
```suggestion
Estas diferenças em como os dados intrínsecos são armazenados vs. como eles são mostrados na tela podem causar surpresas quando os dados são importados para o R.
```

2024-04-12 16:32 UTC, carlossb1 commented on spreadsheets.qmd
> +Outro desafio é quando você tem uma coluna na planilha Excel que tem uma mistura de diferentes tipos, ex: algumas células são numéricas, outras texto, outras datas.
```suggestion
Outro desafio é quando você tem uma coluna na planilha do Excel que tem uma mistura de diferentes tipos, ex: algumas células são numéricas, outras contém texto, outras contém datas.
```

2024-04-12 16:33 UTC, carlossb1 commented on spreadsheets.qmd
> +Nestes casos, você pode definir o tipo para esta coluna como `"list"`, o qual importará a coluna como uma lista de vetor de tamanho 1, onde o tipo de cada elemento do vetor é sugerido.
```suggestion
Nestes casos, você pode definir o tipo para esta coluna como `"list"`, o qual importará a coluna como uma lista de vetores de tamanho 1, onde o tipo de cada elemento do vetor é sugerido.
```

2024-04-12 16:34 UTC, carlossb1 commented on spreadsheets.qmd
> +Veja <https://nacnudus.github.io/spreadsheet-munging-strategies/> para mais sobre estratégias para trabalhar com dados não tabulares vindos do Excel.
```suggestion
Veja <https://nacnudus.github.io/spreadsheet-munging-strategies/> para mais ideias sobre estratégias para trabalhar com dados não tabulares vindos do Excel.
```

2024-04-12 16:36 UTC, carlossb1 commented on spreadsheets.qmd
> +Note que os nomes das columnas também aparecem e em negrito.
```suggestion
Note que os nomes das colunas também aparecem em negrito.
```

2024-04-12 16:42 UTC, carlossb1 commented on spreadsheets.qmd
> +Assim como acontence quando importamos dados de um CSV, as informações sobre os tipos de dados são perdidas quando importamos os dados novamente.
```suggestion
Assim como acontece quando importamos dados de um CSV, as informações sobre os tipos de dados são perdidas quando importamos os dados novamente.
```

2024-04-12 16:44 UTC, carlossb1 commented on spreadsheets.qmd
> +Isto também tornam os arquivos do Excel uma fonte não confiável para armazenar resultados parciais.
```suggestion
Isto torna os arquivos do Excel uma fonte não confiável para armazenar resultados parciais.
```

2024-04-12 16:47 UTC, carlossb1 commented on spreadsheets.qmd
> +O pacote writexl é uma solução simples para criar uma simples planilha Excel, mas se você estiver interessado em características adicionais como escrever em uma planilha dentro de um arquivo e estili
```suggestion
O pacote writexl é uma solução simplificada para criar uma simples planilha do Excel, mas se você estiver interessado em características adicionais como escrever em uma planilha dentro de um arquivo e estilizá-la, você pode querer utilizar o pacote [openxlsx](https://ycphs.github.io/openxlsx).
```

2024-04-12 16:51 UTC, carlossb1 commented on spreadsheets.qmd
> +Observe que este pacote não faz parte do tidyverse, portanto as funções e fluxo de trabalho podem não ser familiares.
```suggestion
Observe que este pacote não faz parte do tidyverse, portanto as funções e fluxos de trabalho podem não ser familiares.
```

2024-04-12 16:51 UTC, carlossb1 commented on spreadsheets.qmd
> +Por exemplo, os nomes das funções usam *camelCase*, várias funções não podem compor um *pipeline*, e os argumentos tendem a seguir ordens diferentes daquela do tidyverse.
```suggestion
Por exemplo, os nomes das funções usam *camelCase*, várias funções não podem compor um *pipeline*, e os argumentos tendem a seguir ordens diferentes daquelas do tidyverse.
```

2024-04-12 16:52 UTC, carlossb1 commented on spreadsheets.qmd
> +Conforme seu aprendizado e uso do R expandem para além deste livro, você encontrará vários outros estilos em diversos pacotes que usará para atingir seus objetivos específicos no R.
```suggestion
Conforme seu aprendizado e uso do R expandem para além deste livro, você encontrará vários outros estilos em diversos pacotes disponíveis para atingir seus objetivos específicos no R.
```

2024-04-12 16:57 UTC, carlossb1 commented on spreadsheets.qmd
> +1.  Em um arquivo Excel, crie o seguinte conjunto de dados e salve como `pesquisa.xlsx`.
```suggestion
1.  Em um arquivo do Excel, crie o seguinte conjunto de dados e salve como `pesquisa.xlsx`.
```

2024-04-12 16:57 UTC, carlossb1 commented on spreadsheets.qmd
> +    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1yc5gL-a2OOBr8M7B3IsDNX5uR17vBHOyWZq6xSTG2G8) como arquivo Excel.
```suggestion
    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1yc5gL-a2OOBr8M7B3IsDNX5uR17vBHOyWZq6xSTG2G8) como arquivo do Excel.
```

2024-04-12 16:58 UTC, carlossb1 commented on spreadsheets.qmd
> +    #|   A coluna n_animais_estimacao, possui valores entre 0 e 2, contento dois valores em texto (N/A e two).
```suggestion
    #|   A coluna n_animais_estimacao, possui valores entre 0 e 2, contendo dois valores em texto (N/A e two).
```

2024-04-12 16:58 UTC, carlossb1 commented on spreadsheets.qmd
> +2.  Em outro arquivo Excel, crie o seguinte conjunto de dados e salve como `lista.xlsx`.
```suggestion
2.  Em outro arquivo do Excel, crie o seguinte conjunto de dados e salve como `lista.xlsx`.
```

2024-04-12 17:01 UTC, carlossb1 commented on spreadsheets.qmd
> +    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1LgZ0Bkg9d_NK8uTdP2uHXm07kAlwx8-Ictf8NocebIE) como arquivo Excel.
```suggestion
    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1LgZ0Bkg9d_NK8uTdP2uHXm07kAlwx8-Ictf8NocebIE) como arquivo do Excel.
```

2024-04-12 17:01 UTC, carlossb1 commented on spreadsheets.qmd
> +    #|   (combinando 3 linhas juntas), B (combinando 4 linhas juntass), A (combinando 2
```suggestion
    #|   (combinando 3 linhas juntas), B (combinando 4 linhas juntas), A (combinando 2 
```

2024-04-12 17:02 UTC, carlossb1 commented on spreadsheets.qmd
> +    O conjunto de dados resultante deve ser nomeado como `lista` e deve parecer como a seguir.
```suggestion
    O conjunto de dados resultante deve ser nomeado como `lista` e deve se parecer como a seguir.
```

2024-04-12 17:03 UTC, carlossb1 commented on spreadsheets.qmd
> +3.  Em um novo arquivo Excel, crie o seguinte conjunto de dados e salve como `vendas.xlsx`.
```suggestion
3.  Em um novo arquivo do Excel, crie o seguinte conjunto de dados e salve como `vendas.xlsx`.
```

2024-04-12 17:03 UTC, carlossb1 commented on spreadsheets.qmd
> +    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1oCqdXUNO8JR3Pca8fHfiz_WXWxMuZAp3YiYFaKze5V0) como arquivo Excel.
```suggestion
    Alternativamente, você pode baixar [aqui](https://docs.google.com/spreadsheets/d/1oCqdXUNO8JR3Pca8fHfiz_WXWxMuZAp3YiYFaKze5V0) como arquivo do Excel.
```

2024-04-12 17:08 UTC, carlossb1 commented on spreadsheets.qmd
> +Uma boa forma de se famliarizar com o estilo de código em um novo pacote é executar alguns exemplos fornecidos na documentação das funções, sentir a sintaxe e formatos de saída, assim como ler qualqu
```suggestion
Uma boa forma de se familiarizar com o estilo de código em um novo pacote é executar alguns exemplos fornecidos na documentação das funções, sentir a sintaxe e formatos de saída, assim como ler qualquer *vignette* que acompanha o pacote.
```

2024-04-12 17:10 UTC, carlossb1 commented on spreadsheets.qmd
> +    #|   de vendas". Linha 2 diz "Dados estão organizados por nome da marca e
```suggestion
    #|   de vendas". A linha 2 diz "Dados estão organizados por nome da marca e 
```

2024-04-12 17:11 UTC, carlossb1 commented on spreadsheets.qmd
> +    O conjunto de dados deve ser parecer como o a seguir, com `id` e `n` como nomes das colunas e com 9 linhas.
```suggestion
    O conjunto de dados deve se parecer como a seguir, com `id` e `n` como nomes das colunas e com 9 linhas.
```

2024-04-12 17:12 UTC, carlossb1 commented on spreadsheets.qmd
> +    Modifique `vendas` de forma a ficar organizado (*tidy*) com três colunas (`marca`, `id`, and `n`) e 7 linhas de dados.
```suggestion
    Modifique `vendas` de forma a ficar organizado (*tidy*) com três colunas (`marca`, `id`, e `n`) e 7 linhas de dados.
```

2024-04-12 17:13 UTC, carlossb1 commented on spreadsheets.qmd
> +4.  Recrie o conjunto de dados `doces_vendas`, exporte para um arquivo Excel usando a função `write.xlsx()` do pacote openxlsx.
```suggestion
4.  Recrie o conjunto de dados `doces_vendas`, exporte para um arquivo do Excel usando a função `write.xlsx()` do pacote openxlsx.
```

2024-04-12 17:45 UTC, carlossb1 requested changes
Consegui finalizar

Desculpa aí pessoal, só agora eu vi que tava mandando as alterações individualmente e deve ter aparecido uma chuva de notificações aí pra vocês =/

2024-04-12 17:45 UTC, carlossb1 commented on spreadsheets.qmd
> +5.  No @sec-data-import voê aprendeu sobre a função `janitor::clean_names()` para transformar os nomes das colunas em *snake case*.
```suggestion
5.  No @sec-data-import você aprendeu sobre a função `janitor::clean_names()` para transformar os nomes das colunas em *snake case*.
```

2024-04-12 17:45 UTC, carlossb1 commented on spreadsheets.qmd
> +Você também pode criar uma nova planilha com a `gs4_create()` ou escrever em uma planilha já existente com a `sheet_write()` e suas amigas.
```suggestion
Você também pode criar uma nova planilha com a `gs4_create()` ou escrever em uma planilha já existente com a `sheet_write()` e semelhantes.
```

2024-04-12 17:45 UTC, carlossb1 commented on spreadsheets.qmd
> +#|   informações de 6 estudantes, seus IDs, nomes completos, comida favorita, plano de refeição e
```suggestion
#|   informações de 6 estudantes, seus IDs, nomes completos, comida favorita, plano alimentar e  
```

2024-04-12 17:45 UTC, carlossb1 commented on spreadsheets.qmd
> +Quando você tenta acessar uma planilha que requer autenticação, o googlesheets4 irá te redirecionar para um navegador web e pedir sua conta do Google para obter a permissão de operar em seu lugar as
```suggestion
Quando você tenta acessar uma planilha que requer autenticação, o googlesheets4 irá te redirecionar para um navegador web e pedir sua conta do Google para obter a permissão de operar as planilhas em seu lugar. Entretanto, se você quiser definir uma conta específica, escopo de autenticação, etc, você pode fazer através da `gs4_auth()`, ex: `gs4_auth(email = "meu@exemplo.com")`, o qual irá forçar o uso de um *token* associado a este email específico.
```

2024-04-12 18:15 UTC, scopinho commented
> Consegui finalizar
> 
> Desculpa aí pessoal, só agora eu vi que tava mandando as alterações individualmente e deve ter aparecido uma chuva de notificações aí pra vocês =/

Opa.. tranquilo Carlos. Muito obrigado pela revisao!!!

2024-04-12 18:21 UTC, scopinho commented
@decarvaa , você pretende vai revisar este?
@beatrizmilz , FYI, o @carlossb1 acabou uma revisão.

2024-05-06 23:14 UTC, beatrizmilz commented
> @decarvaa , você pretende vai revisar este? @beatrizmilz , FYI, o @carlossb1 acabou uma revisão.

@decarvaa Oi Arthur! Você ainda tá interessado em revisar esse capítulo?

2024-05-07 10:05 UTC, decarvaa commented
> > @decarvaa , você pretende vai revisar este? @beatrizmilz , FYI, o @carlossb1 acabou uma revisão.
> 
> @decarvaa Oi Arthur! Você ainda tá interessado em revisar esse capítulo?

@scopinho e @beatrizmilz, posso revisar esse capítulo sim!

2024-05-07 10:08 UTC, beatrizmilz commented
> > > @decarvaa , você pretende vai revisar este? @beatrizmilz , FYI, o @carlossb1 acabou uma revisão.
> > 
> > 
> > @decarvaa Oi Arthur! Você ainda tá interessado em revisar esse capítulo?
> 
> @scopinho e @beatrizmilz, posso revisar esse capítulo sim!

Uhul! Obrigada!

2024-06-01 09:56 UTC, decarvaa reviewed
Segue minha revisão, pessoal!

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Conforme você se move pelas colunas para a direita, o título da célula segue a sequência do alfabeto, ex:
Fiz uma sugestão aqui que se assemelha ao que sugeri sobre a abreviação "e.g.".
Neste caso, i.e. também provém do latim (id est) e pode ser traduzida livremente como "isto é" ou substituída por "ou seja" sem prejuízo de sentido. Também dá pra manter puramente como "i.e.'. Deixo aqui a sugestão e com vocês a decisão sobre manter ou não.

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Para confundir ainda mais, também é possível ter algo que se parece com um número, mas é na verdade uma *string* (ex: , digite `'10` em uma célula no Excel).
```suggestion
Para confundir ainda mais, também é possível ter algo que se parece com um número, mas é na verdade uma *string* (por exemplo: , digite `'10` em uma célula no Excel).
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Outro desafio é quando você tem uma coluna na planilha do Excel que tem uma mistura de diferentes tipos, ex: algumas células são numéricas, outras contém texto, outras contém datas.
```suggestion
Outro desafio é quando você tem uma coluna na planilha do Excel que tem uma mistura de diferentes tipos: algumas células são numéricas, outras contém texto, outras contém datas.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Veja <https://nacnudus.github.io/spreadsheet-munging-strategies/> para mais ideias sobre estratégias para trabalhar com dados não tabulares vindos do Excel.
```suggestion
Veja <https://nacnudus.github.io/spreadsheet-munging-strategies/> para mais estratégias de trabalho com dados não tabulares vindos do Excel.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Vamos criar um pequeno conjunsto de dados (*tibble*) que iremos exportar.
```suggestion
Vamos criar um pequeno conjunto de dados (*tibble*) que iremos exportar.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Não entraremos entrar nos detalhes deste pacote aqui, mas recomendamos ler <https://ycphs.github.io/openxlsx/articles/Formatting.html> para uma extensa discussão sobre mais funcionalidades de formata
```suggestion
Não entraremos nos detalhes deste pacote aqui, mas recomendamos ler <https://ycphs.github.io/openxlsx/articles/Formatting.html> para uma extensa discussão sobre outras funcionalidades de formatação de dados do R para o Excel usando o openxlsx.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +    O conjunto de dados deve se parecer como a seguir, com `id` e `n` como nomes das colunas e com 9 linhas.
```suggestion
    O conjunto de dados deve se parecer com o que é mostrado a seguir, com `id` e `n` como nomes das colunas e com 9 linhas.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +    O conjunto de dados resultante deve ser nomeado como `lista` e deve se parecer como a seguir.
```suggestion
    O conjunto de dados resultante deve ser nomeado como `lista` e deve se parecer com o que é mostrado a seguir.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Este pacote também faz parte dos componentes não-principais (*non-core*) do tidyverse, portanto devemos carregá-lo explicitamente.
```suggestion
Este pacote também faz parte dos componentes secundários (*non-core*) do tidyverse, portanto devemos carregá-lo explicitamente.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Uma breve nota sobre o nome do pacote: googlesheets4 usa a [versão 4 da API do Planilhas Google](https://developers.google.com/sheets/api/) para fornecer uma interface do Planilhas Google para o R, p
```suggestion
Uma breve nota sobre o nome do pacote: googlesheets4 usa a versão 4 da [API do Planilhas Google](https://developers.google.com/sheets/api/) para fornecer uma interface do Planilhas Google para o R, por isso este nome.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +Observe que estamos também utilizando a função `gs4_example()` para localizar a planilha de exemplo que vem junto com o pacote googlesheets4.
```suggestion
Observe que também estamos utilizando a função `gs4_example()` para localizar a planilha de exemplo que vem junto com o pacote googlesheets4.
```

2024-06-01 09:56 UTC, decarvaa commented on spreadsheets.qmd
> +    O *data frame* resultante deve se chamar `lista` e deve ser como abaixo.
```suggestion
    O *data frame* resultante deve se chamar `lista` e deve se parecer como mostrado abaixo.
```

2024-06-11 18:46 UTC, merged