Tradução: databases.qmd
cienciadedatos/pt-r4ds pull request #59
Opened 2023-11-22 21:12 UTC by scopinho

Tradução do capítulo (longo) databases.qmd
Pontos importantes:

1-) o dbplyr tem a função **copy_nycflights13**() que copia localmente os dados do nycflights13 para um database. Precisamos ver como iremos tratar este caso. Na tradução usei os nomes de **voos** e **avioes** do pacote **dados**, mas o código irá falhar pois ainda chama esta função. 

2-) Nos títulos, temos _SQL basic_, _dbplyr basic_ , etc. Traduzi como "**O básico do ..**." . Ficou um pouco mais extenso, mas acho que passa melhor a idéia que "SQL básico" ou "dbplyr básico".

3-) Tem um callout que começa com "In the examples above note that "**year**" and "**type**" are wrapped in double quotes. That’s because these are reserved words in duckdb...". O leitor não poderá ver este efeito, pois como usamos o **voos**, estes nomes não existem e portanto não aparecem com aspas duplas. Fiz um ajuste livre no callout tentando explicar isso. 

Sugestões são bem-vindas!!!

2023-11-25 14:42 UTC, Luaaalex commented
Eu posso seguir com a revisão desse aqui, @beatrizmilz .

2023-11-28 02:43 UTC, beatrizmilz commented
> Eu posso seguir com a revisão desse aqui, @beatrizmilz .

Legal! Me coloquei pra revisar também (mas amanhã haha). Tenho interesse no capítulo :D

2024-01-16 01:51 UTC, magnotairone reviewed
revisei este aqui!

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +O exemplo mais simples de `dbWriteTable()` precisa de três argumentos: uma conexão ao banco de dados, o nome da tabela a ser criada no banco de dados e um *data frame* com os dados.
```suggestion
O exemplo de uso mais simples de `dbWriteTable()` precisa de três argumentos: uma conexão ao banco de dados, o nome da tabela a ser criada no banco de dados e um *data frame* com os dados.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +`dbReadTable()` retorna um `data.frame` portanto usamos `as_tibble()` para converter em um *tibble* para que imprima de forma mais bonita na tela.
```suggestion
`dbReadTable()` retorna um `data.frame`, portanto usamos `as_tibble()` para converter em um *tibble* para que imprima de forma mais bonita na tela.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +dbplyr roda por tráz do dplyr (*dplyr* **backend**), isso significa que você continua a escrever códigos dplyr, mas o *backend* o executa de maneira diferente.
```suggestion
dbplyr roda por tráz do dplyr, isso significa que você continua a escrever códigos dplyr, mas o *backend* o executa de maneira diferente.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +Primeira, muitas organizações possuem banco de dados muito grandes, então você precisa de alguma hierarquia para manter todas as tabelas organizadas.
```suggestion
Primeiro, muitas organizações possuem banco de dados muito grandes, então você precisa de alguma hierarquia para manter todas as tabelas organizadas.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +-   No SQL, variações de letras (maiúscula/minúscula) não faz diferença: você pode escrever `select`, `SELECT` ou até `SeLeCt`. Neste livro ficaremos com a convenção comum de escrever as palavras-cha
```suggestion
-   No SQL,  a maiúscula e minúscula não fazem diferença: você pode escrever `select`, `SELECT` ou até `SeLeCt`. Neste livro ficaremos com a convenção comum de escrever as palavras-chaves SQL usando letras maiúsculas para distinguir de nomes de tabelas ou variáveis.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +-   NO SQL, a ordem importa: você sempre deve escrever as declarações em ordem `SELECT`, `FROM`, `WHERE`, `GROUP BY`, `ORDER BY`. É um pouco confuso, pois esta ordem não é a mesma de como as declaraç
```suggestion
-   No SQL, a ordem importa: você sempre deve escrever as declarações em ordem `SELECT`, `FROM`, `WHERE`, `GROUP BY`, `ORDER BY`. É um pouco confuso, pois esta ordem não é a mesma de como as declarações são realmente avaliadas com `FROM` em primeiro, depois `WHERE`, `GROUP BY`, `SELECT` e `ORDER BY`.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +As traduções do dbplyr certamente não são perfeitas, e ainda existem muitas funções do R que ainda não são traduzidas, mas faz um surpreendente bom trabalho em traduzir as funções que você usará na m
```suggestion
As traduções do dbplyr certamente não são perfeitas, e ainda existem muitas funções do R que ainda não são traduzidas, mas o dbplyr faz um surpreendente bom trabalho em traduzir as funções que você usará na maior parte do tempo.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +Nós focamos no dbplyr, um "*backend*" do dplyr que permite que você escreva seu código dplyr que está familiarizado e o tenha automaticamente traduzido em SQL.
```suggestion
Nós focamos no dbplyr, um "*backend*" do dplyr que permite que você escreva o código dplyr que está familiarizado e o tenha automaticamente traduzido em SQL.
```

2024-01-16 01:51 UTC, magnotairone commented on databases.qmd
> +-   [*Practical SQL*](https://www.practicalsql.com) de Anthony DeBarros é escrito sob a perspectiva de uma pessoa jornalista de dados (cientista de dados especialista em contar atraentes histórias) e
```suggestion
-   [*Practical SQL*](https://www.practicalsql.com) de Anthony DeBarros é escrito sob a perspectiva de uma pessoa jornalista de dados (cientista de dados especialista em contar histórias atraentes) e entra em mais detalhes sobre ter seus dados em um banco de dados e rodar seu próprio SGBD.
```

2024-01-16 10:16 UTC, scopinho commented
> revisei este aqui! @scopinho @beatrizmilz

Show! Já comitei. Muito obrigado @magnotairone !

2024-03-31 22:51 UTC, beatrizmilz commented
> Eu posso seguir com a revisão desse aqui, @beatrizmilz .

Oi @Luaaalex ! Você ainda tem interesse em revisar esse capítulo? Se estiver corrido, posso tirar seu nome e procuramos outra pessoa para revisar! Sem pressão <3

2024-04-02 20:34 UTC, Luaaalex commented
@beatrizmilz  posso revisar, sim. Até sexta vou concluir o capítulo.

2024-04-06 01:06 UTC, Luaaalex requested changes
@beatrizmilz segue revisão capítilo 28 - databases =)

2024-04-06 15:11 UTC, beatrizmilz commented on databases.qmd
> +    Este pacote traduz os comandos genéricos do DBI para as necessidades específicas do um dado SGBD.
```suggestion
    Este pacote traduz os comandos genéricos do DBI para as necessidades específicas de um determinado SGBD.
```

2024-04-06 15:16 UTC, beatrizmilz commented on databases.qmd
> -If you want to use duckdb for a real data analysis project, you'll also need to supply the `dbdir` argument to make a persistent database and tell duckdb where to save it.
Acho que "permanente" também fica estranho.

2024-04-06 15:21 UTC, beatrizmilz commented on databases.qmd
> +Se você quiser usar o duckdb em um projeto de análise de dados real, você também precisará fornecer o argumento `dbdir` para persistir o banco de dados e dizer ao duckdb onde salvá-lo.
```suggestion
Se você quiser usar o duckdb em um projeto de análise de dados real, será necessário incluir o argumento `dbdir` para um banco de dados permanente e dizer ao duckdb onde salvar.
```
Sugestão da Luana @Luaaalex.
Coloquei assim para facilitar a revisão, mas eu acho que essa tradução ainda não está refletindo bem...


Tô pensando, e para traduzir bem, acho que primeiro preciso entender o contexto e o que os autores querem dizer. Me parece que o ponto é indicar um diretório onde o bd será salvo, né? Ou entendi errado?

2024-04-06 15:23 UTC, beatrizmilz commented on databases.qmd
> +Nos exemplos acima, se tivessemos os nomes de `"ano"` e `"tipo"` em inglês (*year* e *type*), elas apareceriam entre aspas duplas.
```suggestion
Nos exemplos acima, se tivéssemos os nomes de `"ano"` e `"tipo"`, elas apareceriam entre aspas duplas.
```

2024-04-06 15:24 UTC, beatrizmilz commented on databases.qmd
> +Se você quiser usar o duckdb em um projeto de análise de dados real, você também precisará fornecer o argumento `dbdir` para persistir o banco de dados e dizer ao duckdb onde salvá-lo.
Qual a opinião de vocês @scopinho e @magnotairone ?

2024-04-08 19:45 UTC, scopinho commented on databases.qmd
> -If you want to use duckdb for a real data analysis project, you'll also need to supply the `dbdir` argument to make a persistent database and tell duckdb where to save it.
My two cents: Persistente é um termo bastante comum no mundo dos bancos de dados, ele reforça a situação do dados persistir em dados e não em memória

2024-04-09 02:30 UTC, scopinho commented on databases.qmd
> +Se você quiser usar o duckdb em um projeto de análise de dados real, você também precisará fornecer o argumento `dbdir` para persistir o banco de dados e dizer ao duckdb onde salvá-lo.
oi @beatrizmilz , é isso mesmo. Por padrao o duckdb grava o db na memoria e nao 'persiste' o db em.disco a naonser que passe este argumento

2024-04-22 14:42 UTC, beatrizmilz commented on databases.qmd
> -If you want to use duckdb for a real data analysis project, you'll also need to supply the `dbdir` argument to make a persistent database and tell duckdb where to save it.
Então vamos manter como persistente!

2024-04-22 14:42 UTC, beatrizmilz commented on databases.qmd
> +Se você quiser usar o duckdb em um projeto de análise de dados real, será necessário incluir o argumento `dbdir` para um banco de dados permanente e dizer ao duckdb onde salvar.
```suggestion
Se você quiser usar o duckdb em um projeto de análise de dados real, será necessário incluir o argumento `dbdir` para um banco de dados persistente e dizer ao duckdb onde salvar.
```

2024-04-22 14:45 UTC, merged

2024-04-22 14:45 UTC, beatrizmilz commented
Obrigada @scopinho e @Luaaalex !!