Tradução: arrow.qmd
cienciadedatos/pt-r4ds pull request #60
Opened 2023-11-23 13:34 UTC by scopinho

Tradução arrow.qmd. 
Pontos importantes:

1-) O capítulo usa o dataset de items retirados das bibliotecas públicas de Seattle que está disponível online em (https://data.seattle.gov/Community/Checkouts-by-Title/tmmm-ytt6). 
Precisamos definir se este será incluído no pacote dados e traduzido ou alguma outra estratégia. O problema é que o CSV dele tem 9 GB e está armazenado em um bucket S3 da AWS aqui: "https://r4ds.s3.us-west-2.amazonaws.com/seattle-library-checkouts.csv". Por ora, mantive o codigo sem traducao dos campos, tentando explicar alguns termos ao longo do texto como CheckoutYear (ano da retirada).

2-) Assim como no databases.qmd, usei "roda por trás do dplyr" (*dplyr backend*) e depois usei *backend* ao longo do texto.  

3-) Para *tree-like* usei "semelhantes a árvores" (mas achei meio esquisito) , então deixei em inglês na frente tb.

Sugestões são bem-vindas!

2023-11-23 20:15 UTC, beatrizmilz commented
@decarvaa

2023-11-24 13:02 UTC, decarvaa requested changes

2023-11-24 13:02 UTC, decarvaa commented on arrow.qmd
> +Muito menos ferramentas podem funcionar com arquivos parquet em comparação com CSV, mas sua estrutura particionada, compactada e colunar torna a análise muito mais eficiente.
```suggestion
Um número muito menor de ferramentas podem funcionar com arquivos parquet em comparação com CSV, mas sua estrutura particionada, compactada e colunar torna sua análise muito mais eficiente.
```

2023-11-24 13:10 UTC, decarvaa requested changes

2023-11-24 13:10 UTC, decarvaa commented on arrow.qmd
> +Vamos nos concentrar nos dados provenientes de arquivos JSON, mas os princípios gerais se aplicam a dados semelhantes a árvores (*tree-like*), independentemente de sua origem.
Pensei em deixar "tree-like" como "dados com estrutura baseada em árvore"

2023-11-24 13:10 UTC, decarvaa commented on arrow.qmd
> +Vamos nos concentrar nos dados provenientes de arquivos JSON, mas os princípios gerais se aplicam a dados semelhantes a árvores (*tree-like*), independentemente de sua origem.
```suggestion
Vamos nos concentrar nos dados provenientes de arquivos JSON, mas os princípios gerais se aplicam a dados com estrutura baseada em árvore (*tree-like*), independentemente de sua origem.
```

2023-11-24 13:11 UTC, scopinho commented on arrow.qmd
> +Vamos nos concentrar nos dados provenientes de arquivos JSON, mas os princípios gerais se aplicam a dados semelhantes a árvores (*tree-like*), independentemente de sua origem.
```suggestion
Vamos nos concentrar nos dados provenientes de arquivos JSON, mas os princípios gerais se aplicam a dados com estrutura baseada em árvore (*tree-like*), independentemente de sua origem.
```

2023-11-24 13:55 UTC, scopinho commented
@decarvaa , muito obrigado pela ajuda na revisão! Excelente!

2023-11-26 07:01 UTC, decarvaa commented
> @decarvaa , muito obrigado pela ajuda na revisão! Excelente!

@scopinho , imagina! A tradução tá muito bem feita e aprendo muito fazendo as revisões!

2023-11-28 02:16 UTC, beatrizmilz commented
> Tradução arrow.qmd. Pontos importantes:
> 
> 1-) O capítulo usa o dataset de items retirados das bibliotecas públicas de Seattle que está disponível online em (https://data.seattle.gov/Community/Checkouts-by-Title/tmmm-ytt6). Precisamos definir se este será incluído no pacote dados e traduzido ou alguma outra estratégia. O problema é que o CSV dele tem 9 GB e está armazenado em um bucket S3 da AWS aqui: "https://r4ds.s3.us-west-2.amazonaws.com/seattle-library-checkouts.csv". Por ora, mantive o codigo sem traducao dos campos, tentando explicar alguns termos ao longo do texto como CheckoutYear (ano da retirada).


Obrigada @scopinho por documentar isso!!

@rivaquiroga In the book, there are big datasets stored in AWS, and the code points to how the reader can download the data directly from AWS.

I guess, in this case, we can:
1 ) use the dataset as it is (in English) or
2) Translate it locally and upload the CSV file to a similar cloud instance.

What is your opinion? Did you face something like that in the 1ed?

@scopinho What do you think?

2023-11-28 02:17 UTC, beatrizmilz commented on arrow.qmd
> +Next capítulo, você aprenderá uma alternativa poderosa: o formato [parquet](https://parquet.apache.org/), um formato baseado em um padrão aberto amplamente utilizado em sistemas de grande volume de d
```suggestion
Neste capítulo, você aprenderá uma alternativa poderosa: o formato [parquet](https://parquet.apache.org/), um formato baseado em um padrão aberto amplamente utilizado em sistemas de grande volume de dados (*big data*).
```

2023-11-28 02:18 UTC, beatrizmilz commented on arrow.qmd
> +Nós iremos juntar arquivos *parquet* com o [Apache Arrow](https://arrow.apache.org), um conjunto de ferramentas muti-linguagens projetado para análise eficiente e transporte de grandes conjunto de da
```suggestion
Nós iremos juntar arquivos *parquet* com o [Apache Arrow](https://arrow.apache.org), um conjunto de ferramentas multi-linguagens projetado para análise eficiente e transporte de grandes conjunto de dados.
```

2023-11-28 02:19 UTC, beatrizmilz commented on arrow.qmd
> +Nós iremos juntar arquivos *parquet* com o [Apache Arrow](https://arrow.apache.org), um conjunto de ferramentas muti-linguagens projetado para análise eficiente e transporte de grandes conjunto de da
A ideia de "transporte" é meio estranha né? Mas tá assim em inglês...
Será que não tem outra palavra que fique menos estranha mas mantendo a ideia da frase?

2023-11-28 02:20 UTC, beatrizmilz commented on arrow.qmd
> +Usaremos *Apache Arrow* via [pacote arrow](https://arrow.apache.org/docs/r/), o qual fornece um *backend* dplyr permitindo que você analise conjuntos de dados maiores que a quantidade de memória de s
```suggestion
Usaremos *Apache Arrow* via o [pacote arrow](https://arrow.apache.org/docs/r/), o qual fornece um *backend* dplyr, permitindo que você analise conjuntos de dados maiores que a quantidade de memória de seu computador, usando a familiar sintaxe dplyr.
```

2023-11-28 02:21 UTC, beatrizmilz commented on arrow.qmd
> +Como benefício adicional, *arrow* é extremamente rápido: você verá alguns exemplos a seguir neste capítulo.
```suggestion
Como benefício adicional, o *arrow* é extremamente rápido: você verá alguns exemplos a seguir neste capítulo.
```

2023-11-28 02:22 UTC, beatrizmilz commented on arrow.qmd
> +Geralmente, é dificil saber qual funcionará melhor, então para fases iniciais da tua análise, vamos te encorajar a tentar usar ambos e escolher aquele que funcione melhor para você.
```suggestion
Geralmente, é dificil saber qual funcionará melhor, então para fases iniciais da sua análise, vamos te encorajar a tentar usar ambos e escolher aquele que funcione melhor para você.
```

2023-11-28 02:23 UTC, beatrizmilz commented on arrow.qmd
> +Tanto *arrow* quanto dbplyr rodam por trás do dplyr (dplyr *backends*), assim, você deve estar se perguntando quando usar um ou outro.
```suggestion
Tanto o  pacote *arrow* quanto o pacote dbplyr rodam por trás do dplyr (dplyr *backends*), assim, você deve estar se perguntando quando usar um ou outro.
```

2023-11-28 02:24 UTC, beatrizmilz commented on arrow.qmd
> +Neste capítulo, continuaremos a usar tydiverse, particularmente dplyr, mas iremos combiná-lo com o pacote *arrow*, que foi projetado especificamente para trabalhar com grandes conjuntos de dados.
```suggestion
Neste capítulo, continuaremos a usar o tidyverse, particularmente o dplyr, mas iremos combiná-lo com o pacote *arrow*, que foi projetado especificamente para trabalhar com grandes conjuntos de dados.
```

2023-11-28 02:24 UTC, beatrizmilz commented on arrow.qmd
> +Posteriormente neste capítulo, veremos também algumas conexões entre *arrow* e o duckdb, portanto também precisaremos do dbplyr e duckdb.
```suggestion
Posteriormente neste capítulo, veremos também algumas conexões entre o *arrow* e o duckdb, portanto também precisaremos do dbplyr e duckdb.
```

2023-11-28 02:25 UTC, beatrizmilz commented on arrow.qmd
> +O código abaixo baixa uma cópia em *cache* desses dados.
```suggestion
O código abaixo faz download de uma cópia em *cache* desses dados.
```

2023-11-28 02:26 UTC, beatrizmilz commented on arrow.qmd
> +Como regra geral, dizemos que você vai querer ter no mínimo duas vezes mais memória que o tamanho dos dados e muitos *laptops* chegam até 16 GB.
```suggestion
Como regra geral, dizemos que você vai querer ter no mínimo duas vezes mais memória que o tamanho dos dados e muitos notebooks chegam até 16 GB.
```

2023-11-28 02:28 UTC, beatrizmilz commented on arrow.qmd
> +`open_dataset()` irá varrer (*scan*) alguns milhares de linhas para entender a estrutura do conjunto de dados.
Em vez de varrer, talvez inspecionar? tem mais ideias?

2023-11-28 02:30 UTC, beatrizmilz commented on arrow.qmd
> +    *Parquet* é baseado em [codificação eficiente](https://parquet.apache.org/docs/file-format/data-pages/encodings/) para manter o tamanho do arquivo menor e suporta compressão de arquivo.
```suggestion
    *Parquet* é baseado em [codificação eficiente](https://parquet.apache.org/docs/file-format/data-pages/encodings/) para manter o tamanho do arquivo menor, e permite a compressão do arquivo.
```

2023-11-28 02:33 UTC, beatrizmilz commented on arrow.qmd
> +Como um guia grosseiro, *arrow* sugere que você evite arquivos menores que 20MB e maiores que 2GB e evite particionamentos que produzam mais que 10.000 arquivos.
```suggestion
Como uma recomendação aproximada, *arrow* sugere que você evite arquivos menores que 20MB e maiores que 2GB e evite particionamentos que produzam mais que 10.000 arquivos.
```
Tentando melhorar a leitura

2023-11-28 02:35 UTC, beatrizmilz commented on arrow.qmd
> +Os nomes dos arquivos usam uma convensão de "auto-descrição" usada pelo projeto [Apache Hive](https://hive.apache.org).
```suggestion
Os nomes dos arquivos usam uma convenção de "auto-descrição" usada pelo projeto [Apache Hive](https://hive.apache.org).
```

2023-11-28 02:37 UTC, beatrizmilz commented on arrow.qmd
> +Entretanto, a lista de operações e funcções suportadas é bastante extensa e contínua aumentando, veja a lista completa de funções atualmente suportadas digitando `?acero`.
```suggestion
Entretanto, a lista de operações e funções suportadas é bastante extensa e continua aumentando; veja a lista completa de funções atualmente suportadas digitando `?acero`.
```

2023-11-28 02:40 UTC, beatrizmilz approved these changes

2023-11-28 02:41 UTC, beatrizmilz commented
Oi @scopinho e @decarvaa !
Obrigada pela tradução e primeira revisão.
Algo que não tem relação com a tradução em si: eu já tinha ouvido falar do pacote parquet, mas nunca usei. O capítulo me deixou muito interessada!! Parece muito bom. 

Sobre a minha revisão: tem alguns typos mas a maioria são coisas que eu anotei para tentar deixar a leitura mais fluida. Veja o que faz sentido para você! :D

2023-11-28 08:57 UTC, scopinho reviewed
Também achei melhor usar "inspecionar" neste caso do scan.

2023-11-28 08:57 UTC, scopinho commented on arrow.qmd
> +`open_dataset()` irá varrer (*scan*) alguns milhares de linhas para entender a estrutura do conjunto de dados.
```suggestion
`open_dataset()` irá inspecionar (*scan*) alguns milhares de linhas para entender a estrutura do conjunto de dados.
```

2023-11-28 09:01 UTC, scopinho commented
> Oi @scopinho e @decarvaa ! Obrigada pela tradução e primeira revisão. Algo que não tem relação com a tradução em si: eu já tinha ouvido falar do pacote parquet, mas nunca usei. O capítulo me deixou muito interessada!! Parece muito bom.
> 
> Sobre a minha revisão: tem alguns typos mas a maioria são coisas que eu anotei para tentar deixar a leitura mais fluida. Veja o que faz sentido para você! :D

Valeu @beatrizmilz , já aceitei a revisão. Sobre o arrow: Depois que comecei a usar, uso em quase todos os casos onde tem dados maiores que uns 5GB até uns 400GB. Dicas: 1-) Leia sobre os tipos de dados, pois as vezes precisa fazer algumas conversões, etc 2-) Como ele não tem todas as funções usar com o duckdb salva a pele 3-) Funções de janela (window) tipo lead/lag não rola com ele, entao teria que converter pra tibbble ou criar uma função diferente vetorizada, etc. Good luck!

2023-11-28 12:00 UTC, beatrizmilz commented
> > > Tradução arrow.qmd. Pontos importantes:
> > > 1-) O capítulo usa o dataset de items retirados das bibliotecas públicas de Seattle que está disponível online em (https://data.seattle.gov/Community/Checkouts-by-Title/tmmm-ytt6). Precisamos definir se este será incluído no pacote dados e traduzido ou alguma outra estratégia. O problema é que o CSV dele tem 9 GB e está armazenado em um bucket S3 da AWS aqui: "https://r4ds.s3.us-west-2.amazonaws.com/seattle-library-checkouts.csv". Por ora, mantive o codigo sem traducao dos campos, tentando explicar alguns termos ao longo do texto como CheckoutYear (ano da retirada).
> > 
> > 
> > Obrigada @scopinho por documentar isso!!
> > @rivaquiroga In the book, there are big datasets stored in AWS, and the code points to how the reader can download the data directly from AWS.
> > I guess, in this case, we can: 1 ) use the dataset as it is (in English) or 2) Translate it locally and upload the CSV file to a similar cloud instance.
> > What is your opinion? Did you face something like that in the 1ed?
> > @scopinho What do you think?
> 
> @beatrizmilz , my two cents: I like option 2: Although for the r4ds translation it might not be a big deal leave it as is (english), I see more and more examples where the data comes from the web like in the webscraping chapter and other articles we may want to translate in the future. Hence, if we could have a bucket somewhere where the link wont go away, it cold be a good asset for this and other translation projects.

I'll work on that, and will be back with new info!

2023-11-28 14:02 UTC, beatrizmilz commented
https://github.com/cienciadedatos/dados/pull/105

2023-12-05 18:08 UTC, rivaquiroga commented
@beatrizmilz, the use AWS is new to the second edition. Did they store the datasets there because they are too big?

2023-12-05 18:31 UTC, scopinho commented
> @beatrizmilz, the use AWS is new to the second edition. Did they store the datasets there because they are too big?

Hi @rivaquiroga , apologizes for jumping in here, but Beatriz mentioned she is a bit busy, so I hope you don't mind if I share some info I have. Anyway, I believe your guess is correct. The idea with arrow is to use a dataset that is big enough to showcase the technology (bigger than memory) and that csv has 9GB.

2023-12-18 12:58 UTC, scopinho commented
> Ideia: podemos seguir com esse capítulo com a versão em inglês, e depois que estiver disponível os dados traduzidos, podemos atualizar. O que acha @scopinho ?

Concordo, pois ao menos ja começamos a disponibilizar para os leitores.

2023-12-18 13:02 UTC, beatrizmilz commented
> > Ideia: podemos seguir com esse capítulo com a versão em inglês, e depois que estiver disponível os dados traduzidos, podemos atualizar. O que acha @scopinho ?
> 
> Concordo, pois ao menos ja começamos a disponibilizar para os leitores.

Criei outra issue pra essa tarefa específica (pra não esquecer haha). E vou aceitar esse PR então!

Posso aceitar? Você ainda quer editar algo?

2023-12-18 13:07 UTC, scopinho commented
> > > Ideia: podemos seguir com esse capítulo com a versão em inglês, e depois que estiver disponível os dados traduzidos, podemos atualizar. O que acha @scopinho ?
> > 
> > 
> > Concordo, pois ao menos ja começamos a disponibilizar para os leitores.
> 
> Criei outra issue pra essa tarefa específica (pra não esquecer haha). E vou aceitar esse PR então!
> 
> Posso aceitar? Você ainda quer editar algo?

Pode aceitar... no momento é tudo que tenho. Se decidirmos mudar, colocamos outro PR depois. thx

2023-12-18 13:31 UTC, merged