Tradução: rectangling.qmd
cienciadedatos/pt-r4ds pull request #61
Opened 2023-11-23 21:21 UTC by scopinho

Tradução do rectangling.qmd
Pontos importantes:  

1-) _**rectangling**_ ficou como '_representação retangular_'
2-) O capítulo usa do pacote 'repurrrsive':
 
got_chars - lista não-nomeada
gmaps_cities - tibble 2 colunas e 5 linhas
gh_users - lista não-nomeada e arquivo JSON

Acredito que precisaremos adicionar ao "dados", mas não sei se o esquema de tradução com os yamls funcionaria para listas tb. Discutindo o tópico com a @beatrizmilz . Por ora, deixei os das listas ainda em Inglês.

3-) O pacote **gh_users_json()** que pega o json de dentro do pacote **repurrrsive**.
Discutir como lidaremos com estes cenário de funções dentro dos pacotes que pegam o dataset automaticamente. 

4-) "children" de uma lista foi traduzido como "**elementos**" na maioria dos casos. Já vi este termo na doc do purr e achei melhor que "filhos/filhas".

5-) Deixei ***list-column*** como termo não traduzido. O ideia foi de usá-lo como fazemos com *data frame*

6-) **Computing** with *list-columns*: Troquei o 'computar' por Trabalhar...achei que fazia mais sentido.

7-) Na linha 332, se migrarmos os dados por pacote '**dados**' devemos alterar a descrição que deixei ainda apontando pro pacote **repurrsive**.

8-) Aguardando inspirações melhores para traduzir "_were sourced from wild-caught JSON_" . Por ora ficou "foram originados de JSONs obtidos por aí".

9-) Deixei os tipos do JSON em inglês (ex: string, number, arrays, objects)

Sugestões são bem-vindas!!!

2024-01-11 13:33 UTC, cmusso86 commented
Olá! Posso revisar esse capítulo!

2024-01-15 16:13 UTC, cmusso86 requested changes
Terminei a revisão desse capítulo. Tentei ser consistente gramaticalmente e com o guia de tradução. Corrigi alguns typos mas também fiz sugestões de uma "versão mais brasileira" , ou seja, mudando mesmo traduções corretas para algo que acho que soa melhor para gente no Brasil. 
Deixei a dívida se os dados dos pacotes usados aqui também serão traduzidos.

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +-   O tipo mais simples é o nulo (`null`) que tem o mesmo papél do `NA` no R. Representa ausência de dados.
```suggestion
-   O tipo mais simples é o nulo (`null`) que tem o mesmo papel do `NA` no R. Representa ausência de dados.
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +Note que JSON não possui umjeito nativo para representar datas e data_hora (*datetime*), então estes são geralmente armazenados como *strings* e você deverá usar `readr::parse_date()` ou `readr::pars
```suggestion
Note que JSON não possui um jeito nativo para representar datas e data_hora (*datetime*), então estes são geralmente armazenados como *strings* e você deverá usar `readr::parse_date()` ou `readr::parse_datetime()` para transformá-los na estrutura de dados correta.
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +Por exemplo, o pacote repurrsive também é a fonte para `gh_user` como um arquivo JSON e você pode importá-la com `read_json()`:
```suggestion
Por exemplo, o pacote repurrsive também é a fonte do `gh_user` como um arquivo JSON e você pode importá-la com `read_json()`:
```
```suggestion
Por exemplo, o pacote repurrrsive também é a fonte para `gh_user` como um arquivo JSON e você pode importá-la com `read_json()`:
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +# O caminho para o arquivo JSON dentro do pacote:
```suggestion
# Um caminho para o arquivo JSON dentro do pacote:
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +# Importa com read_json()
```suggestion
# Importe com read_json()
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +# Verifica se é o mesmo dado que usamos anteriormente
```suggestion
# Verifique se é o mesmo dado que usamos anteriormente
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +Nest livro, usaremos também `parse_json()`, que recebe uma *string* representando um JSON, o que a torna boa para gerar exemplos simples.
```suggestion
Neste livro, usaremos também `parse_json()`, que recebe uma *string* representando um JSON, o que a torna boa para gerar exemplos simples.
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +Para começar, aqui estão três simples conjuntos de dados JSON, começando com um número, entao adicionando alguns números em *array* e então adicionando o *array* e então adicionando este *array* em u
```suggestion
Para começar, aqui estão três simples conjuntos de dados JSON, começando com um número, e então adicionando alguns números em *array* e em seguida adicionando esse *array* em um *object*:
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +jsonlite tem uma outra importante função chamada `fromJSON()`.
```suggestion
jsonlite tem uma outra função importante chamada `fromJSON()`.
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +Isto geralmente funciona bem, particularmente em casos simples, mas achamos que você estaria melhor fazendo você mesmo a representação retangular para que saiba exatamente o que está acontecendo e po
```suggestion
Isto geralmente funciona bem, particularmente em casos simples, mas achamos que é mais vantajoso se fizer você mesmo a representação retangular para que saiba exatamente o que está acontecendo e possa lidar mais facilmente com estruturas aninhadas mais complexas.
```

2024-01-15 16:13 UTC, cmusso86 commented on rectangling.qmd
> +JSON é o formato de dados mais comuns retornados por APIs web.
```suggestion
JSON é o formato de dados mais comum retornados por APIs web.
```

2024-01-15 16:27 UTC, scopinho commented on rectangling.qmd
> +Isto nos dá novos `bounds` (uma região retangular) e `location` (um ponto).
Isso mesmo

2024-01-16 00:29 UTC, scopinho commented on rectangling.qmd
> +Neste capítulo, usaremos várias funções do tidyr, um componente principal do tidyverse.
Oi @cmusso86 ... então, preciso confirmar, mas tem algum capítulo anterior onde ele explica os 'componentes' que são carregados automaticamente com o tidyverse e os que não são. Acredito que qd o leitor chega até aqui, este conceito deve ser conhecido. Vou manter este item aberto até confirmar.

2024-01-16 00:32 UTC, scopinho commented on rectangling.qmd
> +Começaremos com `gh_repos`.
A ideia em geral é essa, mas neste caso, não sei ao certo se faria sentido, pois eh uma lista do github, onde os valores nao viriam em PT. @beatrizmilz , sabe se no datos tem algo sobre este item?

2024-01-16 21:08 UTC, cmusso86 commented on rectangling.qmd
> +Neste capítulo, usaremos várias funções do tidyr, um componente principal do tidyverse.
Eu acho que as pessoas usam como material de consulta e consultam capítulos pontuais mais do que ler de cabo a rabo.  Mas não sou apegada não, é só uma sugestão hehee

2024-06-26 14:34 UTC, debora-s commented
@beatrizmilz posso ser a segunda revisora desse capítulo também.

2024-06-26 21:15 UTC, beatrizmilz commented
> @beatrizmilz posso ser a segunda revisora desse capítulo também.

Ótimo @debora-s! Caso tenha dúvidas, me avise. Esse arquivo também pode ser útil:  https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html
Obrigada pela revisão @cmusso86 !

2024-08-03 15:21 UTC, beatrizmilz commented
Oi @debora-s !
Se você precisar de alguma ajuda, me avisa.
Esse link pode ser útil: https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html
Atenção para a parte que comenta sobre esse botão: 
![imagem](https://github.com/user-attachments/assets/351db961-9309-4e22-a29b-e63a044e5ace)
Ele ajuda muito a deixar mais fácil para aceitar as sugestões depois!
<3

2024-08-20 14:40 UTC, debora-s commented on rectangling.qmd
> +Em geral, é conveniente nomear os componentes ou **elementos** de uma lista, o que pode ser feito da mesma forma que nomeamos colunas de um *tibble*:
```suggestion
Em geral, é conveniente nomear os componentes ou **filhos** de uma lista, o que pode ser feito da mesma forma que nomeamos colunas de um *tibble*:
```

2024-08-20 14:42 UTC, debora-s commented on rectangling.qmd
> +Em geral, é conveniente nomear os componentes ou **elementos** de uma lista, o que pode ser feito da mesma forma que nomeamos colunas de um *tibble*:
Acho que esse termo filho é utlizado mais abaixo indicando que esses elementos são *filhos* de uma lista. Logo abaixo tambem tem as traduções de "neto" demonstrando a conexão.

2024-08-20 16:59 UTC, debora-s commented on rectangling.qmd
> +#|   x5. Ele também tem dois filhos, um vetor *double* e outra
```suggestion
#|   x5. Ele também tem dois filhos, um vetor *double* e outra
```

2024-08-20 17:02 UTC, debora-s commented on rectangling.qmd
> +#|   x5. Ele também tem dois filhos, um vetor *double* e outra
tem que decidir se será utilizado o termo *filho* ou elemento, lembrando que na linha 111, *component* foi traduzido como elemento. mesmo que tenha decidido la em cima traduzir children como elemento, as palavras estão sendo utilizadas em diferentes traduçoes de acordo com o texto o que por de dificultar o entendimento do leitor brasileiro.

2024-09-25 15:31 UTC, debora-s requested changes
Olá, revisão 2 finalizada!
Abraços

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +#|   Clicando no triangulo  apontado para a direita, o elemento de lista se expande
```suggestion
#|   Clicando no triangulo  apontado para a direita, o componente da lista se expande 
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Estes vetores são tidos como simples pois são homogêneos: cada elemento tem o mesmo tipo de dado.
```suggestion
Estes vetores são simples pois são homogêneos: cada elemento tem o mesmo tipo de dado.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +É mais fácil usar *list-columns* com *tibbles*, pois a função `tibble()` trata listas como vetores e o método de impressão exibição foi projetado tendo listas em mente.
```suggestion
É mais fácil usar *list-columns* com *tibbles*, pois a função `tibble()` trata listas como vetores e o método de exibição foi projetado tendo listas em mente.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Quado cada linha tem o mesmo número de elementos com o mesmo nome, como em `df1`, é natural colocar cada elemento em sua própria coluna com `unnest_wider()`:
```suggestion
Quado cada linha tem o mesmo número de elementos com o mesmo nome, como em `df1`, é natural colocar cada componente em sua própria coluna com `unnest_wider()`:
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +`unnest_longer()` sempre mantém o conjunto de colunas inmutável, enquanto muda o número de linhas.
```suggestion
`unnest_longer()` sempre mantém o conjunto de colunas imutável, enquanto muda o número de linhas.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Não: cada elemento é uma lista, mesmo que o conteúdo seja de tipos diferentes.
```suggestion
Não: cada elemento é uma lista, mesmo que os conteúdos sejam de tipos diferentes.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Esta é uma lista que contém dados de uma coleção de repositórios do GitHub obtidos usando a API do GitHub. É uma lista aninhada em vários níveis, por isso é difícil de mostrar sua estrutura neste liv
```suggestion
Esta é uma lista que contém dados sobre uma coleção de repositórios do GitHub obtidos usando a API do GitHub. É uma lista aninhada em vários níveis, por isso é difícil de mostrar sua estrutura neste livro; nós recomendamos que você a explore por conta própria usando `View(gh_repos)` antes de continuar.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Você pode usar isso para entender como o `gh_repos` foi estruturado: cada elemento era um usuário do GitHub contendo uma lista de até 30 repositórios do GitHub que eles criaram.
```suggestion
Você pode usar isso para entender como o `gh_repos` foi estruturado: cada elemento filho era um usuário do GitHub contendo uma lista de até 30 repositórios do GitHub que eles criaram.
```

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +2.  A coluna `owner` do `gh_repo` contém muitas informações duplicadas pois cada pessoa priprietária pode ter vários repositórios.
A coluna `owner` do `gh_repo` contém muitas informações duplicadas pois cada pessoa proprietária pode ter vários repositórios.

2024-09-25 15:31 UTC, debora-s commented on rectangling.qmd
> +Todos os estudos de caso na seção anterior foram originados de JSONs obtidos por aí.
```suggestion
Todos os estudos de caso na seção anterior foram originados de JSONs bruto/proveniente de fontes diretas.
```

2024-09-25 15:32 UTC, debora-s commented
@scopinho  e @beatrizmilz  revisão 2 finalizada, ok?
Abraços

2024-09-25 16:35 UTC, beatrizmilz commented
> @scopinho e @beatrizmilz revisão 2 finalizada, ok? Abraços

Olá!! Muito obrigadaaa!
Agora que eu vi que as duas revisões que você estava estão finalizadas! 
Neste final de semana eu aceito as sugestões e incorporo o capítulo traduzido no livro, muito obrigada 🎉

2024-09-26 09:30 UTC, scopinho commented on rectangling.qmd
> +#|   Clicando no triangulo  apontado para a direita, o elemento de lista se expande
> 

nos pacotes tidyverse (i.e purr) que lidam com listas, a documentação em ingles traz sempre "element". Sugiro padronizarmos com elemento, O que acha?

2024-09-26 09:31 UTC, scopinho commented on rectangling.qmd
> +#|   x5. Ele também tem dois filhos, um vetor *double* e outra
```suggestion
#|   x5. Ele também tem dois elementos filhos, um vetor *double* e outra
```

2024-09-26 09:33 UTC, scopinho commented on rectangling.qmd
> +#|   x5. Ele também tem dois filhos, um vetor *double* e outra
> tem que decidir se será utilizado o termo _filho_ ou elemento, lembrando que na linha 111, _component_ foi traduzido como elemento. mesmo que tenha decidido la em cima traduzir children como elemento, as palavras estão sendo utilizadas em diferentes traduçoes de acordo com o texto o que por de dificultar o entendimento do leitor brasileiro.

Neste caso podemos usar elemento filho...para os que estao aninhados. (child element). O que acha?

2024-09-26 09:35 UTC, scopinho commented on rectangling.qmd
> +2.  A coluna `owner` do `gh_repo` contém muitas informações duplicadas pois cada pessoa priprietária pode ter vários repositórios.
```suggestion
2.  A coluna `owner` do `gh_repo` contém muitas informações duplicadas pois cada pessoa proprietária pode ter vários repositórios.
```

2024-09-26 09:38 UTC, scopinho commented
> @scopinho e @beatrizmilz revisão 2 finalizada, ok? Abraços

Muito obrigado @debora-s !!!
@beatrizmilz , revisao commitada. Mais um pronto pro merge! ;-)

2024-09-29 15:07 UTC, debora-s commented on rectangling.qmd
> +#|   x5. Ele também tem dois filhos, um vetor *double* e outra
Acho que fica otimo!

2024-11-04 18:29 UTC, merged