Tradução: webscraping.qmd
cienciadedatos/pt-r4ds pull request #62
Opened 2023-11-24 19:51 UTC by scopinho

Tradução do webscraping.qmd
Pontos importantes:

1-) "escapes" = "fugas" . Achei 'meio estranho', mas não encontrei nada melhor ainda.

2-) "javascript bookmarklet" = aplicativo (*bookmarklet*) javascript. 

3-) o rvest usa a HTML do vignette ("**starwars**") como exemplo e também da URL https://rvest.tidyverse.org/articles/starwars.html. 
Precisamos encontrar uma alternativa aqui. Talvez usar a mesma tática das listas e incluir uma tradução no pacote dados? Por ora mantive o código usando o conteúdo da origem em inglês.

4-) Similar ao item anterior. O texto usa a página de **top filmes do IMDB** em https://web.archive.org/web/20220201012049/https://www.imdb.com/chart/top/  . 
Também precisamos definir a estratégia para tradução.  Por ora mantive o código usando o conteúdo da origem em inglês.

5-) Será que vale a pena colocar alguma nota de rodapé informando sobre **LGPD** no BR em alguma lugar?

Sugestões são bem-vindas!

2023-12-20 12:45 UTC, carlossb1 commented
Oi @beatrizmilz e @scopinho, posso participar da revisão desse capítulo.

2023-12-20 13:15 UTC, beatrizmilz commented
ótimo José! Boas vindas!

2023-12-20 13:45 UTC, scopinho commented
Bem-vindo @carlossb1 !!! Qq dúvida estamos por aqui!!! :-)

2023-12-20 15:41 UTC, carlossb1 commented
`1-) "escapes" = "fugas" . Achei 'meio estranho', mas não encontrei nada melhor ainda.`

Vi que outras fontes se referem a esses caracteres como "entidades", o que vcs acham dessa alteração?

https://developer.mozilla.org/en-US/docs/Glossary/Entity

2023-12-20 15:43 UTC, carlossb1 requested changes

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Entretanto, algumas vezes você chegará a um site onde `html_elements()` e amigos não retornam nada parecido com o que você vê no navegador.
```suggestion
Entretanto, algumas vezes você chegará a um site onde `html_elements()` e companhia não retornam nada parecido com o que você vê no navegador.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +#|   "O Cavalheiro das Trevas", "O Poderoso Chefão: Parte 2" e "Doze Homens e uma Sentença".
```suggestion
#|   "O Cavaleiro das Trevas", "O Poderoso Chefão: Parte 2" e "Doze Homens e uma Sentença".
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Você aprenderá então o básicos sobre selectores CSS para localizar elementos específicos em uma página e como usar funções do rvest para obter dados de textos e atributos de um HTML para o R.
```suggestion
Você aprenderá o básico sobre seletores CSS para localizar elementos específicos em uma página e como usar funções do rvest para obter dados de textos e atributos de um HTML para o R.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Depois, discutiremos algumas técnicas para descobrir qual seletor CSS você precisa para a página que está fazendo a raspagem de dados, e terminaremos falando sobre alguns estudos de caso e uma breve
```suggestion
Depois, discutiremos algumas técnicas para descobrir qual seletor CSS utilizar para página em que você está fazendo a raspagem de dados, e terminaremos falando sobre alguns estudos de caso e uma breve discussão sobre websites dinâmicos.
```
O que vocês acham de reescrever dessa forma? Ela altera um pouco a estrutura, mas evita que o leitor pense que é a página que realiza a raspagem dos dados.

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Iremos também carregar o tidyverse completo já que é geralmente muito útil para trabalhar com os dados da raspagem.
```suggestion
Iremos também carregar o tidyverse completo já que é geralmente muito útil para trabalhar com os dados obtidos da raspagem.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Em qualquer caso, você deve respeitar os recursos do servidor que hospeda as páginas que está efetuando a raspagem de dados.
```suggestion
Em qualquer caso, você deve respeitar os recursos do servidor que hospeda as páginas em que está efetuando a raspagem de dados.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Mais importante ainda, isso significa que se você estiver fazendo raspagem de muitas páginas, espere um pouco entre cada requisição.
```suggestion
Mais importante ainda, isso significa que se você estiver fazendo raspagem de muitas páginas, certifique-se de esperar um pouco entre cada requisição.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Um jeito fácil é utilizar o pacote [**polite**](https://dmi3kno.github.io/polite/) de Dmytro Perepolkin.
```suggestion
Um jeito fácil de fazer isso é utilizar o pacote [**polite**](https://dmi3kno.github.io/polite/) de Dmytro Perepolkin.
```

2023-12-20 15:43 UTC, carlossb1 commented on webscraping.qmd
> +Se você olhar atentamente, descobrirá que muitos websites incluem em alguma lugar da página um *link* para "termo e condições" ou "termo de serviço", e se você ler a página atentamente, você descobri
```suggestion
Se você olhar atentamente, descobrirá que muitos websites incluem em algum lugar da página um *link* para "termos e condições" ou "termos de serviço", e se você ler a página atentamente, você geralmente descobrirá que o site especificamente proíbe sua raspagem de dados.
```

2023-12-20 16:54 UTC, scopinho commented
> `1-) "escapes" = "fugas" . Achei 'meio estranho', mas não encontrei nada melhor ainda.`
> 
> Vi que outras fontes se referem a esses caracteres como "entidades", o que vcs acham dessa alteração?
> 
> https://developer.mozilla.org/en-US/docs/Glossary/Entity

Talvez faça sentido neste capítulo, minha ressalva é que, por exemplo, no cap regex usam escapes como caracteres de 'escapadas' . tipo \\d, etc .... será que deixamos entidade aqui e escapadas lá?

2023-12-20 17:45 UTC, beatrizmilz commented
> > `1-) "escapes" = "fugas" . Achei 'meio estranho', mas não encontrei nada melhor ainda.`
> > Vi que outras fontes se referem a esses caracteres como "entidades", o que vcs acham dessa alteração?
> > https://developer.mozilla.org/en-US/docs/Glossary/Entity
> 
> Talvez faça sentido neste capítulo, minha ressalva é que, por exemplo, no cap regex usam escapes como caracteres de 'escapadas' . tipo \d, etc .... será que deixamos entidade aqui e escapadas lá?

@jtrecenti @clente como vocês usam essas palavras?

2023-12-21 15:19 UTC, clente commented
@beatrizmilz eu votaria por usar "escapadas" como no capítulo de regex. Entendo que "entidade" é o mais correto no caso do HTML, mas o R4DS usa o mesmo termo para ambos, então talvez devêssemos manter a uniformidade.

2023-12-26 18:23 UTC, beatrizmilz commented
Obrigada Caio! @clente

2024-01-11 00:41 UTC, carlossb1 requested changes
Vou dar uma nova olhada nesse capítulo, encontrei alguns pontos que posso melhorar antes da segunda revisão.

(Já tinha até começado a fazer da parte até a seção de direitos autorais, mas acho que vacilei na hora de fazer o envio e não ficou salvo lol)

2024-01-11 01:06 UTC, scopinho commented
> Vou dar uma nova olhada nesse capítulo, encontrei alguns pontos que posso melhorar antes da segunda revisão.
> 
> (Já tinha até começado a fazer da parte até a seção de direitos autorais, mas acho que vacilei na hora de fazer o envio e não ficou salvo lol)

@carlossb1 ...show...pps, coloca um comentário aqui wd concluir. Muito obrigado!

2024-01-13 16:45 UTC, carlossb1 requested changes

2024-01-16 15:54 UTC, carlossb1 requested changes
Opa, continuando a revisão, parei em "encontrando elementos"

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +Depois, falaremos brevemente sobre tabelas HTML, as quais possuem algumas ferramentas especiais.
```suggestion
Depois, falaremos brevemente sobre tabelas HTML, que possuem algumas ferramentas especiais.
```

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +Você aprenderá primeiro sobre seletores CSS, os quais permitem que você identifique elementos de interesse e sobre funções rvest que permitem que você extraia dados desses elementos.
```suggestion
Você aprenderá primeiro sobre seletores CSS, os quais permitem que você identifique elementos de interesse e sobre as funções do rvest que permitem que você extraia dados desses elementos.
```

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +Dois dos mais importantes atributos são `id` e `class`, que são usados juntamente com as folhas de estilo CSS (*Cascading Style Sheets*) para controlar aparência visual da página.
```suggestion
Dois dos mais importantes atributos são `id` e `class`, que são usados juntamente com as folhas de estilo CSS (*Cascading Style Sheets*) para controlar a aparência visual da página.
```

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +A maioria dos elementos tem conteúdo entre suas marcaçãoes de início e fim.
```suggestion
A maioria dos elementos podem ter conteúdo entre suas marcações de início e fim.
```

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +[^webscraping-4]: Em várias marcações (incluindo `<p>` e `<li>`) a marcção de fim não é obrigatória, mas acreditamos ser melhor incluí-la, pois torna a visualização da estrutura HTML mais fácil.
```suggestion
[^webscraping-4]: Em várias marcações (incluindo `<p>` e `<li>`) a marcação de fim não é obrigatória, mas acreditamos ser melhor incluí-la, pois torna a visualização da estrutura HTML mais fácil.
```

2024-01-16 15:54 UTC, carlossb1 commented on webscraping.qmd
> +Por isso é que quando você procura por uma receita na Internet existe tanto conteúdo antes.
```suggestion
É por isso que quando você procura por uma receita na internet, ela é acompanhada de tanto conteúdo.
```

2024-01-17 15:58 UTC, carlossb1 requested changes
continuando, cheguei em ## Encontrando os seletores adequados {#sec-css-selectors}

vou tentar finalizar hoje a noite e sinalizo pra vocês

2024-01-17 15:58 UTC, carlossb1 commented on webscraping.qmd
> +`html_elements()` retorna um vetor de tamanho 0, enquanto `html_element()` returno um valor faltante (*missing value*).
```suggestion
`html_elements()` retorna um vetor de tamanho 0, enquanto `html_element()` retorna um valor faltante (*missing value*).
```

2024-01-17 15:58 UTC, carlossb1 commented on webscraping.qmd
> +CSS inclui uma pequena linguagem para seleção de elementos em uma página chamada **seletores CSS** (*CSS Selectors*).
```suggestion
CSS inclui uma pequena linguagem chamada **seletores CSS** (*CSS Selectors*) para seleção de elementos em uma página.
```

2024-01-17 15:58 UTC, carlossb1 commented on webscraping.qmd
> +CSS é abreviação para "folha de estilo em cascata" (*cascading style sheets*), e é uma ferramenta para definir os estilo visual dos documentos HTML.
```suggestion
CSS é a abreviação para "folha de estilo em cascata" (*cascading style sheets*), que é uma ferramenta para definir os estilos visuais dos documentos HTML.
```

2024-01-17 23:59 UTC, carlossb1 requested changes
@scopinho consegui finalizar o capítulo, valeu pela paciência 😄 

Assim como vc sugeriu, acho bem legal a gente colocar essa nota sobre a LGPD pra contextualizar como são as tratativas aqui no Brasil. Sobre a questão dos exemplos de Star Wars e do IMDb, se vocês optarem pela tradução, podem contar comigo pra ajudar também no que for preciso.

2024-01-17 23:59 UTC, carlossb1 commented on webscraping.qmd
> +Esta funcionalidade não estava disponível quando escrevemos este livro, mas é algo que estamos trabalhando ativamente e pode estar disponível quando você ler isto.
```suggestion
Esta funcionalidade não estava disponível quando escrevemos este livro, mas é algo em que estamos trabalhando ativamente e pode estar disponível quando você ler isto.
```

2024-01-17 23:59 UTC, carlossb1 commented on webscraping.qmd
> +Ainda assim é possível raspar os dados desse tipo de sites, mas o rvest precisa usar um processo mais caro: simular totalmente o navegador da web, incluindo a execução de todo *javascript*.
```suggestion
Ainda assim é possível raspar os dados desses tipos de sites, mas o rvest precisa usar um processo mais caro: simular totalmente o navegador da web, incluindo a execução de todo *javascript*.
```

2024-01-17 23:59 UTC, carlossb1 commented on webscraping.qmd
> +Jamos juntar tudo isso e fazer a aspagem de dados de alguns websites.
```suggestion
Vamos juntar tudo isso e fazer a raspagem de dados de alguns websites.
```

2024-01-17 23:59 UTC, carlossb1 commented on webscraping.qmd
> +Existem duas principais ferramentas disponíveis para te ajudar com este processo: *SelectorGadget* and as Ferramentas do Desenvolvedor de seu navegador.
```suggestion
Existem duas principais ferramentas disponíveis para te ajudar com este processo: *SelectorGadget* e as Ferramentas do Desenvolvedor de seu navegador.
```

2024-01-18 07:21 UTC, scopinho commented
> @scopinho consegui finalizar o capítulo, valeu pela paciência 😄
> 
> Assim como vc sugeriu, acho bem legal a gente colocar essa nota sobre a LGPD pra contextualizar como são as tratativas aqui no Brasil. Sobre a questão dos exemplos de Star Wars e do IMDb, se vocês optarem pela tradução, podem contar comigo pra ajudar também no que for preciso.

@carlossb1 ,  muito obrigado pela revisão!

2024-04-12 01:06 UTC, cesar-galvao reviewed
Pouquíssimas revisões necessárias! Muito bom!

2024-04-12 01:06 UTC, cesar-galvao commented on webscraping.qmd
> +Este dados tem uma clara estrutura tabular, então vale a pena começar com `html_table()`:
```suggestion
Este dados têm uma clara estrutura tabular, então vale a pena começar com `html_table()`:
```

2024-04-12 01:06 UTC, cesar-galvao commented on webscraping.qmd
> +Mesmo neste caso, em que a maioria dos dados vem de células de tabela, ainda vale a pena dar uma olhada no HTML bruto.
```suggestion
Mesmo neste caso, em que a maioria dos dados vêm de células de tabela, ainda vale a pena dar uma olhada no HTML bruto.
```

2024-04-12 01:06 UTC, cesar-galvao commented on webscraping.qmd
> +Neste capítulo, você aprendeu sobre o porquê, o porquê não e como fazer raspagem de dados em páginas da web.
```suggestion
Neste capítulo, você aprendeu sobre o porquê, o porque não e como fazer raspagem de dados em páginas da web.
```

2024-04-12 01:06 UTC, cesar-galvao commented
@scopinho pronto!

2024-04-12 10:55 UTC, scopinho commented on webscraping.qmd
> +Essas páginas tendem a ser uma apropriação jurídica de terras, onde as empresas fazem reivindicações muito amplas.
Essas páginas tendem a ser uma uma terra sem lei onde as empresas fazem reivindicações muito amplas.

2024-04-12 10:57 UTC, scopinho commented on webscraping.qmd
> +Essas páginas tendem a ser uma apropriação jurídica de terras, onde as empresas fazem reivindicações muito amplas.
```suggestion
Essas páginas tendem a ser uma terra sem lei, onde as empresas fazem reivindicações muito amplas.
```

2024-04-12 10:57 UTC, scopinho commented on webscraping.qmd
> +Essas páginas tendem a ser uma apropriação jurídica de terras, onde as empresas fazem reivindicações muito amplas.
concordo

2024-04-12 10:58 UTC, scopinho commented
Ola @beatrizmilz , mais com com dois revisores concluído. ;-)

2024-04-27 21:40 UTC, beatrizmilz commented
Oiee!
Gente, desculpa! Não tinha visto que essa tradução estava completa. Já vou aceitar e adicionar no livro!!!

Muito obrigada!

2024-04-27 21:40 UTC, merged

2024-04-28 15:09 UTC, scopinho commented
> Oiee! Gente, desculpa! Não tinha visto que essa tradução estava completa. Já vou aceitar e adicionar no livro!!!
> 
> Muito obrigada!

Mais um pra conta galera!!! Obrigado!!!