Tradução: joins.qmd
cienciadedatos/pt-r4ds pull request #70
Opened 2023-12-12 12:51 UTC by scopinho

Tradução do capitulo joins.qmd.
Notas:

1-) Last observation carried forward : Última observação levada adiante
2-) Zen-like koan: diálogo meio Zen 
3-) Usando codigo_cauda ao invés de cauda. Versao dev de dados está com PR para mudar no nome desta coluna
4-) `Batting`, `People` e `Salaries` do pacote Lahman foram pegos do pacotes dados
5-) Rolling joins ficou "Uniões deslizantes"
Em geral, tentei traduzir os tipos de joins, mas mantive os termos em inglês, pois são mais utilizados pelos cientistas de dados (IMHO).

Sugestões são bem-vindas!

2024-04-04 00:48 UTC, MaximilianCF commented
Vou revisar este capítulo.

2024-06-24 20:52 UTC, beatrizmilz commented
A @debora-s comentou por email que quer fazer a revisão também!

2024-06-25 14:11 UTC, debora-s commented
Oi gente! Vou contribuir com a Revisão!

2024-06-26 21:17 UTC, beatrizmilz commented
> Oi gente! Vou contribuir com a Revisão!

Ótimo! Se tiver alguma dúvida, pode me chamar!

2024-06-27 12:15 UTC, MaximilianCF commented
Oi Debora,
Que tal dividirmos em partes o capítulo e distribuímos entre nós para revisão?

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTlNXVjNMNDRQS1BSU05EUkdFUTJZU0ZFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
On jun 25 2024, at 11:11 am, Debora Silva ***@***.***> wrote:
>
>
> Oi gente! Vou contribuir com a Revisão!
> —
> Reply to this email directly, view it on GitHub ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F70%23issuecomment-2189073908&recipient=cmVwbHkrQVdBUUhPTlNXVjNMNDRQS1BSU05EUkdFUTJZU0ZFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOJJLK2UN5LBAQZA6WTZJF3CFAVCNFSM6AAAAABARNNL5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBZGA3TGOJQHA&recipient=cmVwbHkrQVdBUUhPTlNXVjNMNDRQS1BSU05EUkdFUTJZU0ZFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you commented.
>

2024-06-28 13:42 UTC, debora-s commented
Oi maxmilian vou ent'ao compartilhar o que eu ja fiz de correção desse aqui, pode ser?

2024-06-28 13:49 UTC, MaximilianCF commented
Oi Debora, pode ser.

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
On jun 28 2024, at 10:42 am, Debora Silva ***@***.***> wrote:
>
>
> Oi maxmilian vou ent'ao compartilhar o que eu ja fiz de correção desse aqui, pode ser?
> —
> Reply to this email directly, view it on GitHub ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F70%23issuecomment-2196944901&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOLY4NJYGYP7S3CULE3ZJVR4BAVCNFSM6AAAAABARNNL5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJWHE2DIOJQGE&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you commented.
>

2024-06-28 14:00 UTC, debora-s requested changes
texto de revisão de @debora-s. Fui até a linha 698. Maxmillian ficou de pegar a outra parte. :)
Tentei manter as traduções join inner join equi joins etc. conforme solicitado.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Nesta seção, você aprenderá sobre os dois tipos de chave e verá exemplos de ambos nos conjuntos de dados do pacote dados.
Nesta seção, você aprenderá sobre os dois tipos de chave e verá exemplos de ambos nos conjuntos de dados do pacote nycflights13.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Neste capítulo, exploraremos os cinco conjuntos de dados relacionados do pacote dados usando as funções de união do pacote dplyr.
Neste capítulo, exploraremos os cinco conjuntos de dados relacionados do pacote nycflights13 usando as funções de união do pacote dplyr.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +library(dados)
library(nycflights13)

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +## Chaves
## Chaves (*keys*)
Penso que essa palavra também deve ser mantida em inglês aqui no título, usando a sequencia lógica do texto

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Cada união envolve um par de chaves: uma chave primária (*primary key*) e uma chave estrangeira (*foreign key*).
Cada união (*join*) envolve um par de chaves: uma chave primária (*primary key*) e uma chave estrangeira (*foreign key*).

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Quando mais de uma variável é necessária, a chave é chamada de **chave primária composta.** (*compound primary key*). Por exemplo, no pacote dados:
Quando são necessárias mais de uma variável , a chave é  denominada de **chave primária composta** (*compound primary key*). Por exemplo, no pacote dados:
OBS: A tradução literal as vezes nao respeita muita a concordancia verbal no portugues. Tentei melhorar a frase e pontuação

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +    Você pode identificar uma companhia aérea com seu código de operadora de duas letras, tornando `companhia_aerea` a chave primária (*primary key*).
Você pode identificar uma companhia aérea com seu código de transportadora de duas letras, tornando `companhia_aerea` a chave primária (*primary key*). 

"carrier code" se refere ao código da companhia aérea, que é internacionalmente reconhecido pela IATA (International Air Transport Association) na area de logistica de transporte de carga ou companhia aerea ou os dois . Então nesse parágrafo sugiro colocar (codigo da transportadora) pq fica mais claro. desde a linha 49 para fazer mais sentido no texto.
A versão em ingles está escrito "carrier" com sendo a chave primaria. Aqui mantivemos a tradução como "companhia_aerea" porem fica confuso pq ele esta se referindo as duas letras  como a chave primário. Podemos discutir isso

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +-   `clima` registra dados sobre cada os aeroportos de orgigem.
correção:
'clima' registra dados sobre o clima no aeroportos de origem.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +    Você pode identificar cada observação pela combinação de origem e horário, tornando `origem` e `data_hora` a chave primária composta (*compound primary key*).
Você pode identificar cada observação pela combinação de localização (origem do aeroporto) e horário, tornando `origem` e `data_hora` a chave primária composta (*compound primary key*).
Penso que fica mais claro, pois origem se refere a localizaçã do aeroporto.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Você notará um recurso interessante no design dessas chaves: as chaves primária e estrangeira quase sempre têm os mesmos nomes, o que, como você verá em breve, tornará sua vida para as uniões (*joins
Você notará um recurso interessante no design dessas chaves: as chaves primária (*primary key*) e estrangeira (foreign key*) quase sempre têm os mesmos nomes, o que, como você verá em breve, tornará sua vida para as uniões (*joins*) muito mais fácil.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Há apenas uma exceção: `ano` significa ano de saída em `voos` e ano de fabricação em `aviões`.
Há apenas uma exceção: `ano` significa ano de partida em `voos` e ano de fabricação em `aviões`.
departure nesse caso foi o ano de partida daquele vôo.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Agora que identificamos as chaves primárias em cada tabela, é uma boa prática verificar se elas realmente identificam cada observação de forma única.
gora que identificamos as chaves primárias (*primary keys*) em cada tabela, é uma boa prática verificar se elas realmente identificam cada observação de forma única.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Uma maneira de fazer isso é contar com a função `count()` as chaves primárias e procurar entradas onde `n` é maior que um.
Uma maneira de fazer isso é contar com a função `count()` as chaves primárias (*primary keys*) e procurar entradas onde `n` é maior que um.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Você também deve verificar se há valores ausentes (*missing values*) em suas chaves primárias – se um valor estiver faltando, ele não poderá identificar uma observação!
Você também deve verificar se há valores ausentes (*missing values*) em suas chaves primárias (*primary keys*) – se um valor estiver faltando, ele não poderá identificar uma observação!

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Até agora não falamos sobre a chave primária para `voos`..
Até agora não falamos sobre a chave primária (*primary key*) para `voos`.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Não é muito importante aqui, porque não existem quadros de dados que o utilizem como chave estrangeira, mas ainda é útil considerar porque é mais fácil trabalhar com observações se tivermos alguma ma
Não é muito importante aqui, porque não existem *data frames* que o utilizem como chave estrangeira, mas ainda é útil considerar porque é mais fácil trabalhar com observações se tivermos alguma maneira de descrevê-las para outras pessoas.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +A ausência de linhas duplicadas torna automaticamente `data_hora`-`companhia_aerea`-`voo` uma chave primária?
A ausência de linhas duplicadas torna automaticamente `data_hora`-`companhia_aerea`-`voo` uma chave primária (*primary key*)?

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Por exemplo, latitude e longitude são boas chaves primárias para `aeroportos`?
Por exemplo, latitude e longitude são boas chaves primárias (*primary keys*) para `aeroportos`?

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Identificar um aeroporto pela sua latitude e longitude é claramente uma má ideia e, em geral, não é possível saber apenas a partir dos dados se uma combinação de variáveis ​​constitui ou não uma boa
Identificar um aeroporto pela sua latitude e longitude é claramente uma má ideia e, em geral, não é possível saber apenas a partir dos dados se uma combinação de variáveis ​​constitui ou não uma boa chave primária (*primary key*).

correção de pontuação também

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +### Chaves substitutas
### Chaves substitutas (*Surrogate keys*)
Penso que esse termo deve seguir a mesma logica do termo primary key

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Dito isto, seria melhor introduzir uma chave substituta numérica simples usando o número da linha:
Dito isto, seria melhor introduzir uma chave substituta (*surrogate key*) numérica simples usando o número da linha:

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Chaves substitutas podem ser particularmente úteis na comunicação com outras pessoas: é muito mais fácil dizer a alguém para dar uma olhada no voo 2001 do que dizer para olhar o UA430, que partiu às
Chaves substitutas (*Surrogates keys*) podem ser particularmente úteis na comunicação com outras pessoas: é muito mais fácil dizer a alguém para dar uma olhada no voo 2001 do que dizer para olhar o UA430, que partiu às 9h.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +5.  Desenhe um diagrama ilustrando as conexões entre os *data frames* `rebatedores`, `pessoas` e `salarios` do pacote dados.
Desenhe um diagrama ilustrando as conexões entre os *data frames* `rebatedores`, `pessoas` e `salarios` do pacote dados Lahman.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +### Uniões de mutação
### Uniões de mutação (*Mutating joins*)

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +### Especificando chaves das uniões
### Especificando chaves das uniões (*join keys*)

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Por padrão, `left_join()` usará todas as variáveis ​​que aparecem em ambos os *data frames* como a chave de união, a chamada união **natural** (*natural join*).
Por padrão, `left_join()` usará todas as variáveis ​​que aparecem em ambos os *data frames* como a chave de união (*join key), a chamada união **natural** (*natural join*).

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Observe que as variáveis ​​`ano` são desambiguadas na saída com um sufixo (`ano.x` e `ano.y`), que informa se a variável veio do argumento `x` ou `y`.
desambiguar aqui significa tirar a ambiguidade existente nessa variável. Não seria melhor a palavra "diferenciar" pq na verdade elas significam informações sobre ano mas  uma é sobre o ano do vôo  e outra é o ano do avião. "desambiguar nao me parece que isso fica claro

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Em segundo lugar, é como você especifica diferentes chaves de união em cada tabela.
Em segundo lugar, é como você especifica diferentes chaves de união (*join keys*) em cada tabela.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Em códigos mais antigos, você pode ver uma maneira diferente de especificar as chaves de união, usando um vetor de caracteres:
Em códigos mais antigos, você pode ver uma maneira diferente de especificar as chaves de união (*join keys*), usando um vetor de caracteres:

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Agora que existe, preferimos `join_by()` pois fornece uma especificação mais clara e flexível.
Agora que isto existe, preferimos `join_by()` pois fornece uma especificação mais clara e flexível.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +A diferença é quais linhas elas mantêm: a *left join* mantém todas as linhas em `x`, a *right join* mantém todas as linhas em `y`, a *full join* mantém todas as linhas em `x` ou `y`, e a *inner join*
A diferença é quais linhas as funções mantêm: a *left join* mantém todas as linhas em `x`, a *right join* mantém todas as linhas em `y`, a *full join* mantém todas as linhas em `x` ou `y`, e a *inner join* mantém apenas as linhas que ocorrem em `x` e `y`.
Modificado: funções. Fica mais claro sobre o que esta sendo escrito.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +### Uniões de filtragem
### Uniões de filtragem (*Filtering joins*)

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Valores implicitamente ausentes não aparecem como `NA`s, mas existem apenas como uma ausência.
Valores implicitamente ausentes (*implicity missing values*) não aparecem como `NA`s, mas existem apenas como uma ausência.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
>  Or we can find which `tailnum`s are missing from `planes`:
Ou podemos encontrar cada valor em  `codigo_cauda` que estiverem ausentes de `avioes`:

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +## Como as uniões funcionam?
## Como as uniões (*joins*) funcionam?

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Começaremos apresentando uma representação visual de uniões, usando os *tibbles* simples definidos abaixo e mostrados na @fig-join-setup.
Começaremos apresentando uma representação visual de uniões (*joins*), usando os *tibbles* simples definidos abaixo e mostrados na @fig-join-setup.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   TPara entender como funcionam as junções, é útil pensar em todos os possíveis
Para entender como funcionam as junções, é útil pensar em todos os possíveis
correção de digitação

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Para descrever um tipo específico de união, indicamos correspondências com pontos.
Para descrever um tipo específico de união (*join*), indicamos correspondências com pontos.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Essas uniões funcionam adicionando uma observação "virtual" a cada *data frame*.
Essas uniões (*joins*) funcionam adicionando uma observação "virtual" a cada *data frame*.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +    #|   Em comparação com o diagrama anterior que mostra uma união interna, a tabela y
Em comparação com o diagrama anterior que mostra uma união interna (*innner join*), a tabela y

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +    #|   Uma representação visual da união completa onde cada linha em `x`
Uma representação visual da união completa (*full join*) onde cada linha em `x`

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   Diagramas de Venn para uniões internas, completas, esquerda e direita. Cada união
Diagramas de Venn para uniões internas (*inner join*), completas (*full join*), esquerda (*left join*) e direita (*right join*).

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   União interna: a interseção está sombreada.
União interna (*Inner join*): a interseção está sombreada.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   União completa: Tudo está sombreado.
União completa (*Full join*): Tudo está sombreado.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   União esquerda: Tudo em x está sombreado.
União esquerda (*Left join*): Tudo em x está sombreado.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   União direita: Tudo em y está sombreado.
União direita (*Right join*): Tudo em y está sombreado.

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Voltaremos às unão não-equivalentes (*non-equi joins*) no @sec-non-equi-joins.
Voltaremos às união não-equivalentes (*non-equi joins*) no @sec-non-equi-joins.
correção de grafia

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   Uma anti-união **anti-join*) é o inverso de uma semi-união (*semi-join*), eliminando linhas de `x`
Uma anti-união (*anti-join*) é o inverso de uma semi-união (*semi-join*), eliminando linhas de `x

retirado asteristico e inserido parenteses

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +#|   Uma anti-união é o inverso de uma semi-união, então as correspondências são desenhadas com
Uma anti-união (*anti-join*) é o inverso de uma semi-união, então as correspondências são desenhadas com

2024-06-28 14:00 UTC, debora-s commented on joins.qmd
> +Nas uniões equivalentes, as chaves `x` e `y` são sempre iguais, então só precisamos mostrar uma na saída.
Nas uniões equivalentes (*equi joins*), as chaves `x` e `y` são sempre iguais, então só precisamos mostrar uma na saída.

2024-06-28 14:04 UTC, debora-s commented
Olá, @MaximilianCF, revisei até a linha 698. 
@scopinho  acabou que onde estava as traduções do item :
4-) Batting, People e Salaries do pacote Lahman foram pegos do pacotes dados, eu acabei colocando o nome do pacote. Me desculpe mas não fazia sentido pra mim enquanto lia.
Fique a vontade para manter ou não.
Agradeço a oportunidade de contribuir.

2024-06-28 14:05 UTC, debora-s commented
> Oi Debora, pode ser. Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
> […](#)
> On jun 28 2024, at 10:42 am, Debora Silva ***@***.***> wrote: Oi maxmilian vou ent'ao compartilhar o que eu ja fiz de correção desse aqui, pode ser? — Reply to this email directly, view it on GitHub ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F70%23issuecomment-2196944901&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOLY4NJYGYP7S3CULE3ZJVR4BAVCNFSM6AAAAABARNNL5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJWHE2DIOJQGE&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you commented.

Oi mandei já a minha revisão. Parei na linha 698. obrigada

2024-07-11 20:49 UTC, MaximilianCF requested changes
Não estou certo, mas acredito que ao invés de utilizar uniões o mais adequado seria junções. Contudo, não tenho nível técnico da terminologia apenas indicando o que achei em pesquisas.

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   de x corresponde a uma linha de y e a segunda e terceira linhas correspondem
```suggestion
#|   de x corresponde a uma linha de y e a segunda e terceira linhas correspondem a
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
>  Each of these is described in more detail in the following sections.
```suggestion
Cada um deles é descrito em maiores detalhes nas seções a seguir.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +As uniõescruzadas são úteis ao gerar permutações.
```suggestion
As uniões cruzadas são úteis ao gerar permutações.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +As uniões cruzadas usam uma função de união diferente porque não há distinção entre interno/esquerdo/direito/completo quando você corresponde a cada linha
```suggestion
As uniões cruzadas usam uma função de união diferente porque não há distinção entre interno/esquerdo/direito/completo quando você corresponde todas as linhas.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Uniões de desigualdade (*inequality joins*) usam `<`, `<=`, `>=` ou `>` para restringir o conjunto de correspondências possíveis, como na @fig-join-gte e na @fig-join-lt.
```suggestion
Uniões de desigualdade (*inequality joins*) usam `<`, `<=`, `>=` ou `>` para restringir o conjunto de correspondências possíveis, como em @fig-join-gte e @fig-join-lt.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   AUma junção de desigualdade onde `x` é unido a `y` nas linhas onde a chave
```suggestion
#|  Uma junção de desigualdade onde `x` é unido a `y` nas linhas onde a chave 
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   de `x` é menor que a chave de `y`. Isso forma um triângulo
```suggestion
#|   de `x` é menor que a chave de `y`. Isso retorna uma forma triangular
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   em um triangulo no canto superior esquerdo.
```suggestion
#|   em uma forma triangular no canto superior esquerdo.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +As uniões de desigualdade são extremamente gerais, tão gerais que é difícil encontrar casos de uso específicos significativos.
```suggestion
As uniões de desigualdade são extremamente gerais, tão gerais que é difícil encontrar casos relevantes de uso específico.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Uniões deslizantes (*rolling joins*) são um tipo especial de uniã0 de desigualdade onde, em vez de obter *todas* as linhas que satisfaçam a desigualdade, você obtém apenas a linha mais próxima, como
```suggestion
Uniões deslizantes (*rolling joins*) são um tipo especial de união de desigualdade em que ao invés de obter *todas* as linhas que satisfaçam a desigualdade, você obtém apenas a linha mais próxima, como na @ fig-join-closest.
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   Uma união deslizante é semelhante a uma união de desigualdade maior ou igual
```suggestion
#|   Uma união deslizante é semelhante a uma união de desigualdade maior ou igual a
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   Uma união dezlizante é um subconjunto de uma uniçao de desigualdade, portanto algumas correspondências são
```suggestion
#|   Uma união dezlizante é um subconjunto de uma união de desigualdade, portanto algumas correspondências são
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +#|   acinzentadas indicando que eles não são usados ​​porque não são os
```suggestion
#|   desconsideradas indicando que eles não são usados ​​porque não são os 
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +funcionarios
```suggestion
funcionários
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Para resolver esse problema, precisaremos abordar o problema de uma maneira diferente, com uniões de sobreposições (*overlap joins*).
```suggestion
Para resolver esse problema, precisaremos abordar o problema de uma maneira diferente, com uniões de sobreposições (*overlap joins*).
```
```suggestion
Para resolver este problema, precisaremos abordar o problema de uma maneira diferente, com uniões de sobreposições (*overlap joins*).
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Ops, há uma sobreposição, então vamos corrigir esse problema e continuar:
```suggestion
Ops, há uma sobreposição, então vamos corrigir este problema e continuar:
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Ao longo do caminho você aprendeu como identificar chaves (*keys*) e a diferença entre chaves primárias (*primary keys*) e estrangeiras (*foreign keys*).
```suggestion
Ao longo do caminho você aprendeu como identificar chaves (*keys*) e a diferença entre chaves primárias (*primary keys*) e externas (*foreign keys*).
```

2024-07-11 20:49 UTC, MaximilianCF commented on joins.qmd
> +Finalmente, você teve uma ideia do poder das uniões não-equivalentes (*non-equi joins*) e viu alguns casos de uso interessantes.
```suggestion
Finalmente, você teve uma ideia do poder das uniões não-equivalentes (*non-equi joins*) e viu alguns casos interessantes de seu uso.
```

2024-07-11 20:50 UTC, MaximilianCF commented
> > Oi Debora, pode ser. Enviado do Mailspring _**@**_._**/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
> > […](#)
> > On jun 28 2024, at 10:42 am, Debora Silva _**@**_.**_> wrote: Oi maxmilian vou ent'ao compartilhar o que eu ja fiz de correção desse aqui, pode ser? — Reply to this email directly, view it on GitHub _**@**_._**/1?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F70%23issuecomment-2196944901&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe _**@**_.**_/2?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOLY4NJYGYP7S3CULE3ZJVR4BAVCNFSM6AAAAABARNNL5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJWHE2DIOJQGE&recipient=cmVwbHkrQVdBUUhPTFpUMk5aMjdJMzJPRVFCVDZFUktQTUJFVkJOSEhIUzVGTzY0QHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you commented.
> 
> Oi mandei já a minha revisão. Parei na linha 698. obrigada

Pronto.

2024-08-03 13:22 UTC, beatrizmilz commented
Obrigada gente!! @MaximilianCF @debora-s

2024-08-03 14:09 UTC, beatrizmilz reviewed
Aplicando sugestões da @debora-s

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +# Uniões {#sec-joins}
```suggestion
# ✅ Uniões (*joins*) {#sec-joins}
```

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +Neste capítulo, exploraremos os cinco conjuntos de dados relacionados do pacote dados usando as funções de união do pacote dplyr.
```suggestion
Neste capítulo, exploraremos os cinco conjuntos de dados relacionados do pacote nycflights13[^nt-joins-1] usando as funções de união do pacote dplyr.

[^nt-joins-1]: **Nota de tradução**: Disponíveis em português no pacotes [dados](https://cienciadedatos.github.io/dados/).
```

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +## Chaves
```suggestion
## Chaves (*keys*)
```
Sugestão da @debora-s

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +# Uniões {#sec-joins}
Deixando em inglês também (seguindo outra sugestão da @debora-s)

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +Nesta seção, você aprenderá sobre os dois tipos de chave e verá exemplos de ambos nos conjuntos de dados do pacote dados.
```suggestion
Nesta seção, você aprenderá sobre os dois tipos de chave e verá exemplos de ambos nos conjuntos de dados do pacote nycflights13.
```

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +Nesta seção, você aprenderá sobre os dois tipos de chave e verá exemplos de ambos nos conjuntos de dados do pacote dados.
Sugestão da @debora-s

2024-08-03 14:09 UTC, beatrizmilz commented on joins.qmd
> +Cada união envolve um par de chaves: uma chave primária (*primary key*) e uma chave estrangeira (*foreign key*).
Sugestão da @debora-s 
```suggestion
Cada união (*join*) envolve um par de chaves (*key*): uma chave primária (*primary key*) e uma chave estrangeira (*foreign key*).
```

2024-08-03 14:11 UTC, beatrizmilz commented on joins.qmd
> +Quando mais de uma variável é necessária, a chave é chamada de **chave primária composta.** (*compound primary key*). Por exemplo, no pacote dados:
```suggestion
Quando são necessárias mais de uma variável, a chave é denominada de chave primária composta (*compound primary key*). Por exemplo, no pacote dados:
```

2024-08-03 14:20 UTC, beatrizmilz reviewed
Continuando a registrar as sugestões da @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +    Você pode identificar uma companhia aérea com seu código de operadora de duas letras, tornando `companhia_aerea` a chave primária (*primary key*).
```suggestion
-   `companhias_aereas` registra dois dados sobre cada companhia aérea: seu código e seu nome completo.
    Você pode identificar uma companhia aérea com seu código de transportadora de duas letras, tornando `companhia_aerea` a chave primária (*primary key*).
```
sugestão da @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +-   `clima` registra dados sobre cada os aeroportos de orgigem.
```suggestion
-   `clima` registra dados sobre o clima nos aeroportos de origem.
```

sugestão @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +    Você pode identificar cada observação pela combinação de origem e horário, tornando `origem` e `data_hora` a chave primária composta (*compound primary key*).
```suggestion
    Você pode identificar cada observação pela combinação de localização (origem do aeroporto) e horário, tornando `origem`e `data_hora` a chave primária composta (*compound primary key*).
```

Sugestão da @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +Você notará um recurso interessante no design dessas chaves: as chaves primária e estrangeira quase sempre têm os mesmos nomes, o que, como você verá em breve, tornará sua vida para as uniões (*joins
```suggestion
Você notará um recurso interessante no design dessas chaves: as chaves primária (*primary key*) e estrangeira (*foreign key*) quase sempre têm os mesmos nomes, o que, como você verá em breve, tornará sua vida para as uniões (*joins*) muito mais fácil.
```
Sugestão da @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +Há apenas uma exceção: `ano` significa ano de saída em `voos` e ano de fabricação em `aviões`.
Sugestão da @debora-s 
```suggestion
Há apenas uma exceção: `ano` significa ano de partida em `voos` e ano de fabricação em `avioes`.
```

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +### Chaves substitutas
```suggestion
### Chaves substitutas (*Surrogate keys*)
```
Sugestão da @debora-s

2024-08-03 14:20 UTC, beatrizmilz commented on joins.qmd
> +Até agora não falamos sobre a chave primária para `voos`..
```suggestion
Até agora não falamos sobre a chave primária para `voos`.
```

2024-08-03 14:24 UTC, beatrizmilz commented
Pessoal, estou incorporando as sugestões da @debora-s , ok?

2024-08-03 14:25 UTC, beatrizmilz commented on joins.qmd
> +Não é muito importante aqui, porque não existem quadros de dados que o utilizem como chave estrangeira, mas ainda é útil considerar porque é mais fácil trabalhar com observações se tivermos alguma ma
```suggestion
Não é muito importante aqui, porque não existem *data frames* que o utilizem como chave estrangeira, mas ainda é útil considerar porque é mais fácil trabalhar com observações se tivermos alguma maneira de descrevê-las para outras pessoas.
```

2024-08-03 14:26 UTC, beatrizmilz commented on joins.qmd
> +Identificar um aeroporto pela sua latitude e longitude é claramente uma má ideia e, em geral, não é possível saber apenas a partir dos dados se uma combinação de variáveis ​​constitui ou não uma boa
```suggestion
Identificar um aeroporto pela sua latitude e longitude é claramente uma má ideia e, em geral, não é possível saber apenas a partir dos dados se uma combinação de variáveis ​​constitui ou não uma boa chave primária.
```

2024-08-03 14:26 UTC, beatrizmilz commented on joins.qmd
> +Dito isto, seria melhor introduzir uma chave substituta numérica simples usando o número da linha:
```suggestion
Dito isto, seria melhor introduzir uma chave substituta (*surrogate key*) numérica simples usando o número da linha:
```

2024-08-03 14:27 UTC, beatrizmilz commented on joins.qmd
> +### Uniões de mutação
```suggestion
### Uniões de mutação (*Mutating joins*)
```

2024-08-03 14:27 UTC, beatrizmilz commented on joins.qmd
> +### Especificando chaves das uniões
```suggestion
### Especificando chaves das uniões (*join keys*)
```

2024-08-03 14:28 UTC, beatrizmilz commented on joins.qmd
> +Por padrão, `left_join()` usará todas as variáveis ​​que aparecem em ambos os *data frames* como a chave de união, a chamada união **natural** (*natural join*).
```suggestion
Por padrão, `left_join()` usará todas as variáveis ​​que aparecem em ambos os *data frames* como a chave de união (*join key*), a chamada união **natural** (*natural join*).
```

2024-08-03 14:28 UTC, beatrizmilz commented on joins.qmd
> +Observe que as variáveis ​​`ano` são desambiguadas na saída com um sufixo (`ano.x` e `ano.y`), que informa se a variável veio do argumento `x` ou `y`.
```suggestion
Observe que as variáveis ​​`ano` são diferenciadas na saída com um sufixo (`ano.x` e `ano.y`), que informa se a variável veio do argumento `x` ou `y`.
```

2024-08-03 14:29 UTC, beatrizmilz commented on joins.qmd
> +Em segundo lugar, é como você especifica diferentes chaves de união em cada tabela.
```suggestion
Em segundo lugar, é como você especifica diferentes chaves de união (*join keys*) em cada tabela.
```

2024-08-03 14:29 UTC, beatrizmilz commented on joins.qmd
> +Agora que existe, preferimos `join_by()` pois fornece uma especificação mais clara e flexível.
```suggestion
Agora que isto existe, preferimos `join_by()` pois fornece uma especificação mais clara e flexível.
```

2024-08-03 14:31 UTC, beatrizmilz commented on joins.qmd
> +A diferença é quais linhas elas mantêm: a *left join* mantém todas as linhas em `x`, a *right join* mantém todas as linhas em `y`, a *full join* mantém todas as linhas em `x` ou `y`, e a *inner join*
```suggestion
A diferença é quais linhas as funções mantêm: a *left join* mantém todas as linhas em `x`, a *right join* mantém todas as linhas em `y`, a *full join* mantém todas as linhas em `x` ou `y`, e a *inner join* mantém apenas as linhas que ocorrem em `x` e `y`.
```

2024-08-03 14:31 UTC, beatrizmilz commented on joins.qmd
> +### Uniões de filtragem
```suggestion
### Uniões de filtragem (*Filtering joins*)
```

2024-08-03 14:32 UTC, beatrizmilz commented on joins.qmd
>  Or we can find which `tailnum`s are missing from `planes`:
```suggestion
Ou podemos encontrar cada valor em `codigo_cauda` que estiverem ausentes de `avioes`:
```

2024-08-03 14:32 UTC, beatrizmilz commented on joins.qmd
> +## Como as uniões funcionam?
```suggestion
## Como as uniões (*joins*) funcionam?
```

2024-08-03 14:33 UTC, beatrizmilz commented on joins.qmd
> +Começaremos apresentando uma representação visual de uniões, usando os *tibbles* simples definidos abaixo e mostrados na @fig-join-setup.
```suggestion
Começaremos apresentando uma representação visual de uniões (*joins*), usando os *tibbles* simples definidos abaixo e mostrados na @fig-join-setup.
```

2024-08-03 14:33 UTC, beatrizmilz commented on joins.qmd
> +#|   TPara entender como funcionam as junções, é útil pensar em todos os possíveis
```suggestion
#|   Para entender como funcionam as uniões, é útil pensar em todos os possíveis
```

2024-08-03 14:34 UTC, beatrizmilz commented on joins.qmd
> +É por isso que esse tipo de junção costuma ser chamado de **união equivalente** (*equi join*).
```suggestion
É por isso que esse tipo de união costuma ser chamado de **união equivalente** (*equi join*).
```

2024-08-03 14:34 UTC, beatrizmilz commented on joins.qmd
> +-   **Uniões de sobreposições** (*overlap joins*) são um tipo especial de junção de desigualdade projetada para trabalhar com intervalos.
```suggestion
-   **Uniões de sobreposições** (*overlap joins*) são um tipo especial de união de desigualdade projetada para trabalhar com intervalos.
```

2024-08-03 14:34 UTC, beatrizmilz commented on joins.qmd
> +#|   Um diagrama que descreve uma junção de desigualdade onde um quadro de dados x é unido por
```suggestion
#|   Um diagrama que descreve uma união de desigualdade onde um quadro de dados x é unido por 
```

2024-08-03 14:35 UTC, beatrizmilz commented on joins.qmd
> +-   **Uniões deslizantes** (*rolling joins*) são semelhantes às junções de desigualdade, mas apenas encontram a correspondência mais próxima.
```suggestion
-   **Uniões deslizantes** (*rolling joins*) são semelhantes às uniões de desigualdade, mas apenas encontram a correspondência mais próxima.
```

2024-08-03 14:36 UTC, beatrizmilz commented on joins.qmd
> +    #|   Em comparação com o diagrama anterior que mostra uma união interna, a tabela y
```suggestion
    #|   Em comparação com o diagrama anterior que mostra uma união interna (*inner join*), a tabela y
```

2024-08-03 14:37 UTC, beatrizmilz commented on joins.qmd
> +    #|   Uma representação visual da união completa onde cada linha em `x`
```suggestion
    #|   Uma representação visual da união completa (*full join*) onde cada linha em `x`
```

2024-08-03 14:38 UTC, beatrizmilz commented on joins.qmd
> +#|   Diagramas de Venn para uniões internas, completas, esquerda e direita. Cada união
```suggestion
#|   Diagramas de Venn para uniões internas (*inner join*), completas (*full join*), esquerda (*left join*) e direita (*right join*). Cada união
```

2024-08-03 14:38 UTC, beatrizmilz commented on joins.qmd
> +#|   União interna: a interseção está sombreada.
```suggestion
#|   União interna (*inner join*): a interseção está sombreada. 
```

2024-08-03 14:38 UTC, beatrizmilz commented on joins.qmd
> +#|   União completa: Tudo está sombreado.
```suggestion
#|   União completa (*full join*): Tudo está sombreado. 
```

2024-08-03 14:39 UTC, beatrizmilz commented on joins.qmd
> +#|   União esquerda: Tudo em x está sombreado.
```suggestion
#|   União esquerda (*left join*): Tudo em x está sombreado.
```

2024-08-03 14:39 UTC, beatrizmilz commented on joins.qmd
> +#|   União direita: Tudo em y está sombreado.
```suggestion
#|   União direita (*right join*): Tudo em y está sombreado.
```

2024-08-03 14:39 UTC, beatrizmilz commented on joins.qmd
> +Voltaremos às unão não-equivalentes (*non-equi joins*) no @sec-non-equi-joins.
```suggestion
Voltaremos às uniões não-equivalentes (*non-equi joins*) no @sec-non-equi-joins.
```

2024-08-03 14:40 UTC, beatrizmilz commented on joins.qmd
> +#|   Uma anti-união **anti-join*) é o inverso de uma semi-união (*semi-join*), eliminando linhas de `x`
```suggestion
#|   Uma anti-união (*anti-join*) é o inverso de uma semi-união (*semi-join*), eliminando linhas de `x`
```

2024-08-03 14:41 UTC, beatrizmilz commented on joins.qmd
> +#|   Uma anti-união é o inverso de uma semi-união, então as correspondências são desenhadas com
```suggestion
#|   Uma anti-união (*anti-join*) é o inverso de uma semi-união (*semi-join*), então as correspondências são desenhadas com
```

2024-08-03 14:41 UTC, beatrizmilz commented on joins.qmd
> +Nas uniões equivalentes, as chaves `x` e `y` são sempre iguais, então só precisamos mostrar uma na saída.
```suggestion
Nas uniões equivalentes (*equi joins*), as chaves `x` e `y` são sempre iguais, então só precisamos mostrar uma na saída.
```

2024-08-03 14:42 UTC, beatrizmilz commented on joins.qmd
> +### Uniões cruzadas
```suggestion
### Uniões cruzadas (*Cross joins*)
```

2024-08-03 14:43 UTC, beatrizmilz commented on joins.qmd
> +### Uniões de desigualdades
```suggestion
### Uniões de desigualdades (*Inequality joins*)
```

2024-08-03 14:43 UTC, beatrizmilz commented on joins.qmd
> +### Uniões deslizantes
```suggestion
### Uniões deslizantes (*Rolling joins*)
```

2024-08-03 14:44 UTC, beatrizmilz commented on joins.qmd
> +### Uniões de sobreposições
```suggestion
### Uniões de sobreposições (*Overlap joins*)
```

2024-08-03 14:45 UTC, beatrizmilz commented on joins.qmd
> +#|   Uma união dezlizante é um subconjunto de uma união de desigualdade, portanto algumas correspondências são
```suggestion
#|   Uma união deslizante é um subconjunto de uma união de desigualdade, portanto algumas correspondências são
```

2024-08-03 14:51 UTC, beatrizmilz commented
Obrigada pessoal!
@debora-s https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html

Caso você faça mais alguma revisão, dá uma olhada nesse botão:
Ele permite que você já coloque sua sugestão de uma forma que a gente consegue aceitar sua sugestão mais fácil <3
https://cienciadedatos.github.io/guia-traducao-ptbr/images/botao-suggestion.png

2024-08-03 14:51 UTC, merged