Tradução: base-R.qmd
cienciadedatos/pt-r4ds pull request #71
Opened 2023-12-12 23:03 UTC by scopinho

Tradução do capitulo base-R.qmd.
Notas:

1-) Para R base, foi usado "R base".
2-) Subsetting foi usado subconjunto.
3-) Usado do pacote dados o df "diamante"
4-) Loop foi deixado como loop mesmo.

Sugestões são bem-vindas!

2023-12-31 00:47 UTC, magnotairone commented
vou revisar este aqui

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +`[` é usado para extrair subcomponentes de vetores e *data frames* e é chamado como `x[i]` ou `x[i, j]`.
```suggestion
`[` é usado para extrair subcomponentes de vetores e *data frames* e é usado como `x[i]` ou `x[i, j]`.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +    Extrair um subconjunto com inteiros positivos obtem os elementos dessas posições:
```suggestion
    Extrair um subconjunto com inteiros positivos obtém os elementos dessas posições:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +    Isto é mais frequentemente útil em conjunto com a função de comparação.
```suggestion
    Isto é mais útil em conjunto com função de comparação.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +    # Todos os valores não faltantes (*non-missing values*) de x
```suggestion
    # Todos os valores não faltantes de x
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +    Se você tiver um vetor nomeado (*named vector*), poderá extrair um subconjunto com um vetor de caracteres:
```suggestion
    Se você tiver um vetor nomeado, poderá extrair um subconjunto com um vetor de caracteres:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Existem algumas maneiras diferentes[^base-r-1] de usar `[` com um quadro de dados, mas a maneira mais importante é selecionar linhas e colunas independentemente com `df[linhas, colunas]`. Aqui `linha
```suggestion
Existem algumas maneiras diferentes[^base-r-1] de usar `[` com uma tabela de dados, mas a maneira mais importante é selecionar linhas e colunas independentemente com `df[linhas, colunas]`. Aqui `linhas` e `colunas` são vetores conforme descrito acima.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +# Selecione linhas onde `x` é maior que 1 e todas as colunas
```suggestion
# Selecione linhas em que `x` é maior que 1 e todas as colunas
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Precisamos usá-lo aqui porque `[` não usa avaliação organizada (*tidy evaluation*), então você precisa ser explícito sobre a origem da variável `x`.
```suggestion
Precisamos usá-lo aqui porque `[` não usa avaliação *tidy*, então você precisa ser explícito sobre a origem da variável `x`.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Neste livro, usamos principalmente tibbles, que *são* quadros de dados, mas eles ajustam alguns comportamentos para tornar sua vida um pouco mais fácil.
```suggestion
Neste livro, usamos principalmente tibbles, que *são* tabelas de dados, mas eles ajustam alguns comportamentos para tornar sua vida um pouco mais fácil.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Uma maneira de evitar essa ambigüidade com `data.frame`s é especificar explicitamente `drop = FALSE`:
```suggestion
Uma maneira de evitar essa ambiguidade com `data.frame`s é especificar explicitamente `drop = FALSE`:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +### Equivalentes dplyr
```suggestion
### Equivalências do dplyr
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +-   `filter()` é equivalente a subconjunto das linhas com um vetor lógico, tomando cuidado para excluir valores ausentes:
```suggestion
-   `filter()` é equivalente a fazer um subconjunto das linhas com um vetor lógico, tomando cuidado para excluir valores ausentes:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +-   `arrange()` é equivalente a subconjunto das linhas com um vetor inteiro, geralmente criado com `order()`:
```suggestion
-   `arrange()` é equivalente a fazer um subconjunto das linhas com um vetor inteiro, geralmente criado com `order()`:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +-   Ambos `select()` e `relocate()` são semelhantes a subconjuntos das colunas com um vetor de caracteres:
```suggestion
-   Ambos `select()` e `relocate()` são semelhantes a fazer subconjuntos das colunas com um vetor de caracteres:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +O R base também fornece uma função que combina os recursos de `filter()` e `select()`[^base-r-2] chamada `subset()`:
```suggestion
O R base também fornece uma função que combina as características de `filter()` e `select()`[^base-r-2] chamada `subset()`:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Nesta seção, mostraremos como usar `[[` e `$` para extrair colunas de *data frames*, discutiremos mais algumas diferenças entre `data.frames` e tibbles e enfatizaremos algumas diferenças importantes
```suggestion
Nesta seção, mostraremos como usar `[[` e `$` para extrair colunas de *data frames*, discutiremos mais algumas diferenças entre `data.frames` e tibbles e enfatizaremos algumas diferenças importantes entre `[ ` e `[[` quando usado com listas.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +`[`, que seleciona muitos elementos, é emparelhado com `[[` e `$`, que extraem um único elemento.
trocaria esse "emparelhado" por outra palavra, mas não consegui pensar em uma que se adeque a essa frase

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +# bpor nome
```suggestion
# por nome
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Existem várias outras abordagens de base R para criar novas colunas, incluindo `transform()`, `with()` e `within()`.
```suggestion
Existem várias outras abordagens do R base para criar novas colunas, incluindo `transform()`, `with()` e `within()`.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +`pull()` pegam um nome de variável ou uma posição de variável e retornam apenas aquela coluna.
```suggestion
`pull()` pega um nome de variável ou uma posição de variável e retorna apenas a coluna correspondente.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Existem algumas diferenças importantes entre tibbles e `data.frame`s básicos quando se trata de `$`.
```suggestion
Existem algumas diferenças importantes entre tibbles e `data.frame`s quando se trata de `$`.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Os *data frames** correspondem ao prefixo de qualquer nome de variável (chamado de **correspondência parcial** (*partial matching*) ) e não reclamam se uma coluna não existir:
```suggestion
Os *data frames** acessam o prefixo de qualquer nome de variável (chamado de **correspondência parcial**) e reclamam se uma coluna não existir:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Tibbles são mais rigorosos: eles apenas correspondem exatamente aos nomes das variáveis ​​e irão gerar um aviso se a coluna que você está tentando acessar não existir:
```suggestion
Tibbles são mais rigorosos: eles apenas retornam os nomes das variáveis exatos ​​e irão gerar um aviso se a coluna que você está tentando acessar não existir:
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +  b = "uma sgring",
```suggestion
  b = "uma string", 
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +A diferença entre `[` e `[[` é particularmente importante para listas porque `[[` detalha a lista enquanto `[` retorna uma lista nova e menor.
```suggestion
A diferença entre `[` e `[[` é particularmente importante para listas porque `[[` acessa um elemento da lista enquanto `[` retorna uma lista nova e menor.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +#|   conter pimenta, contém vários pacotes de pimenta
```suggestion
#|   conter pimenta, contém vários pacotes de pimenta.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +No @sec-iteration, você aprendeu técnicas tidyverse para iteração como `dplyr::across()` e a família de funções map.
```suggestion
No @sec-iteration, você aprendeu técnicas do tidyverse para iteração como `dplyr::across()` e a família de funções map.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Infelizmente `tapply()` retorna seus resultados em um vetor nomeado (*named vector*) que requer alguma ginástica se você quiser coletar múltiplos resumos e agrupar variáveis ​​em um *data frame* (é c
```suggestion
Infelizmente `tapply()` retorna seus resultados em um vetor nomeado que requer alguma ginástica se você quiser coletar múltiplos resumos e agrupar variáveis ​​em um *data frame* (é certamente possível não fazer isso e apenas trabalhar com vetores livres, mas em nossa experiência isso apenas atrasa o trabalho).
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Isso raramente aparece na ciência de dados porque geralmente trabalhamos com quadros de dados e não com matrizes.
```suggestion
Isso raramente aparece na ciência de dados porque geralmente trabalhamos com tabelas de dados e não com matrizes.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +
```suggestion
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Muitos usuários de R que não usam o tidyverse preferem ggplot2 para plotagem devido a recursos úteis como padrões sensatos, legendas automáticas e uma aparência moderna.
```suggestion
Muitos usuários de R que não usam o tidyverse preferem ggplot2 para criação de gráficos devido a recursos úteis como padrões sensatos, legendas automáticas e uma aparência moderna.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +No entanto, as funções de plotagem do R base ainda podem ser úteis porque são muito concisas – é preciso muito pouca digitação para fazer um gráfico exploratório básico.
```suggestion
No entanto, as funções gráficas do R base ainda podem ser úteis porque são muito concisas – é preciso muito pouca digitação para fazer um gráfico exploratório básico.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Observe que as funções de plotagem básica funcionam com vetores, então você precisa extrair colunas do *data frame* usando `$` ou alguma outra técnica.
```suggestion
Observe que as funções gráficas básicas funcionam com vetores, então você precisa extrair colunas do *data frame* usando `$` ou alguma outra técnica.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Neste capítulo, mostramos uma seleção de funções do R base úteis para subconjuntos (*subsetting*)e iterações.
```suggestion
Neste capítulo, mostramos uma seleção de funções do R base úteis para subconjuntos e iterações.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Em comparação com as abordagens discutidas em outras partes do livro, essas funções tendem a ter mais um sabor de "vetor" do que de "data frames", porque as funções do R base (*base R)* tendem a usar
```suggestion
Em comparação com as abordagens discutidas em outras partes do livro, essas funções tendem a ter mais um sabor de "vetor" do que de "data frames", porque as funções do R base tendem a usar vetores individuais, em vez de um *data frame* e alguma especificação de coluna.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Esperamos que esses capítulos tenham despertado seu interesse em programação e que você esteja ansioso para aprender mais fora deste livro.
seguindo a diretriz da tradução para usar frases neutras
```suggestion
Esperamos que esses capítulos tenham despertado seu interesse em programação e que você esteja com bastante de empolgação para aprender mais fora deste livro.
```

2023-12-31 01:43 UTC, magnotairone commented on base-R.qmd
> +Para ajudá-lo a lembrar a diferença, dê uma olhada no pimenteiro incomum mostrado na @fig-pepper.
```suggestion
Para te ajudar a lembrar a diferença, dê uma olhada no pimenteiro incomum mostrado na @fig-pepper.
```

2024-01-02 19:34 UTC, scopinho commented on base-R.qmd
> +`[`, que seleciona muitos elementos, é emparelhado com `[[` e `$`, que extraem um único elemento.
@magnotairone  ... Que tal: "se parece com" ou "é similar " ?

2024-01-27 09:55 UTC, scopinho commented
O Cesar Galvao fará a segunda revisao (enviado pelo slack).

2024-01-27 11:31 UTC, beatrizmilz commented
Atualizei por aqui! Obrigada por seguir pessoal, tô enrolada pois deposito a tese nessa próxima semana 👀

2024-01-30 00:13 UTC, cesar-galvao requested changes
Texto revisado com poucas alterações. Via de regra eram erros de digitação, vírgulas, etc. Poucas vezes foi ajustada a frase para se adequar ao sentido original.

2024-01-30 00:13 UTC, cesar-galvao commented on base-R.qmd
> +Neste capítulo, mostramos uma seleção de funções do R base úteis para subconjuntos e iterações.
```suggestion
Neste capítulo mostramos uma seleção de funções do R base úteis para subconjuntos e iterações.
```

2024-01-30 20:19 UTC, scopinho commented on base-R.qmd
> +`[`, que seleciona muitos elementos, é emparelhado com `[[` e `$`, que extraem um único elemento.
```suggestion
`[`, que seleciona muitos elementos, é similar a  `[[` e `$`, que extraem um único elemento.
```

2024-01-30 20:21 UTC, scopinho commented
> Texto revisado com poucas alterações. Via de regra eram erros de digitação, vírgulas, etc. Poucas vezes foi ajustada a frase para se adequar ao sentido original.

Muito obrigado @cesar-galvao ! Já fiz os ajustes. @beatrizmilz acredito que com esta 2a revisão podemos concluir mais este. O que acha?

2024-02-01 21:21 UTC, merged

2024-02-01 21:21 UTC, beatrizmilz commented
Obrigada @scopinho @magnotairone @cesar-galvao !