Tradução: functions.qmd
cienciadedatos/pt-r4ds pull request #72
Opened 2023-12-15 19:08 UTC by scopinho

Tradução do cap functions.qmd
Notas:

1-) mutate functions ficou "Funções de mutate", pois trata-se daquelas que funcionam dentro da função *mutate()*

2-) Usei "Mascaramento de dados para **Data-masking** e Seleção Organizada **Tidy-selection**, pois no texto indica para procurar na dicumentação por estes dois termos, não faria sentido (IMHO) colocar somente em PT nestes casos.

3-) Usei o pacote dados para traduções de startwars , flights e weather.

Sugestões são bem-vindas!

2023-12-26 13:13 UTC, carlossb1 commented
Posso revisar esse capitulo também

2023-12-26 13:49 UTC, scopinho commented
> Posso revisar esse capitulo também

Que ótimo!!! Muito obrigado!!!

2023-12-26 18:52 UTC, carlossb1 requested changes
Segue a revisão.

Conforme pontuado, se vocês acharem legal fazer a padronização da tradução dos termos summary/summarize, eu posso fazer as alterações aqui e no capítulo **Numbers**

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +## Funções vetorias
```suggestion
## Funções vetoriais
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Para deixar isso um pouco mais claro, podemos substituir o bit que varia com `█`:
```suggestion
Para deixar isso um pouco mais claro, podemos substituir a parte que varia com `█`:
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +(No @sec-iteration, ocê aprenderá como usar `across()` para reduzir ainda mais a duplicação, então tudo que você precisará é `df |> mutate(across(a:d, rescala01))`).
```suggestion
(No @sec-iteration, você aprenderá como usar `across()` para reduzir ainda mais a duplicação, então tudo que você precisará é `df |> mutate(across(a:d, rescala01))`).
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Você pode notar que a função `rescala01()` faz algum trabalho desnecessário --- em vez de calcular `min()` duas vezes e `max()` uma vez que poderíamos calcular o mínimo e o máximo em uma única etapa
```suggestion
Você pode notar que a função `rescala01()` faz algum trabalho desnecessário --- em vez de calcular `min()` duas vezes e `max()` uma vez, poderíamos calcular o mínimo e o máximo em uma única etapa com `range( )`:
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Outra família importante de funções vetoriais são as funções de resumo, funções que retornam um único valor para uso em `summarize()`.
No capítulo **Numbers** essas funções foram traduzidas como funções de sumarização, e aqui estão como funções de resumo.

Não sugeri a alteração pois são sinônimos, então acho que a diferença não prejudica o entendimento do leitor. Mas achei legal pontuar, talvez por questões de padronização seja interessante realizar as alterações e incluir o termo no guia de tradução.

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Para permitir que você escreva uma função que use verbos dplyr, primeiro apresentaremos o desafio da indireção (*indirection challenge*) e como você pode superá-lo usando `{{ }}`.
```suggestion
Para permitir que você escreva uma função que use verbos dplyr, primeiro apresentaremos o desafio da indireção (*indirection challenge*) e como você pode superá-lo usando os sinais de chaves `{{ }}`.
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Abraçar (*embracing*) uma variável significa envolvê-la entre colchetes para que (por exemplo) `var` se torne `{{ var }}`.
```suggestion
Abraçar (*embracing*) uma variável significa envolvê-la entre chaves para que (por exemplo) `var` se torne `{{ var }}`.
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Além disso, uma vez que os argumentos da `summarize()` são usam mascamento de dados (*data-masking*), isso significa que o argumento `var` para a função `sumario6()` também é usa mascaramento de dado
```suggestion
Além disso, uma vez que os argumentos da `summarize()` usam mascaramento de dados (*data-masking*), isso significa que o argumento `var` para a função `sumario6()` também usa mascaramento de dados (*data-masking*).
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Por exemplo, imagine que você deseja escrever um `conta_faltantes()` que conte o número de observações faltantes nas linhas.
```suggestion
Por exemplo, imagine que você deseja escrever uma função `conta_faltantes()` que conte o número de observações faltantes nas linhas.
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +1.  Usando os conjuntos de dados voos e clima do pacote dados, escreva uma função que:
```suggestion
1.  Usando os conjuntos de dados "voos" e "clima" do pacote dados, escreva uma função que:
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +    2.  Conta o número de voos cancelados e o número de voos atrasados ​​mais de uma hora.
```suggestion
    2.  Conta o número de voos cancelados e o número de voos atrasados por um tempo maior que uma hora.
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Alguns das funções auxiliares mais úteis combinam uma pitada de manipulação de dados com ggplot2.
```suggestion
Algumas das funções auxiliares mais úteis combinam uma pitada de manipulação de dados com ggplot2.
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +#|   Gráfico de barras de transparência de diamantes, onde a clareza está no eixo y e conta
```suggestion
#|   Gráfico de barras de transparência de diamantes, onde a clareza está no eixo y e as contagens
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Lembre-se da função de histograma que mostramos anteriormente?
```suggestion
Lembra da função de histograma que mostramos anteriormente?
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Não seria bom se pudéssemos rotular a saída com a variável e a largura do compartimento que foi usada?
```suggestion
Não seria bom se pudéssemos rotular a saída com a variável e a largura do intervalo que foi usada?
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +# Não pe verbo, nem descritivo
```suggestion
# Não é verbo, nem descritivo
```

2023-12-26 18:52 UTC, carlossb1 commented on functions.qmd
> +Além disso, `funcao()` deve sempre ser seguida por colchetes (`{}`), e o conteúdo deve ser recuado por dois espaços adicionais.
```suggestion
Além disso, `funcao()` deve sempre ser seguida por chaves (`{}`), e o conteúdo deve ser recuado por dois espaços adicionais.
```

2023-12-27 11:22 UTC, scopinho commented on functions.qmd
> +Outra família importante de funções vetoriais são as funções de resumo, funções que retornam um único valor para uso em `summarize()`.
```suggestion
Outra família importante de funções vetoriais são as funções de sumarização, funções que retornam um único valor para uso em `summarize()`.
```

2023-12-27 11:27 UTC, scopinho commented
@carlossb1 , muito obrigado pela revisão. Ficou excelente! @beatrizmilz acredito que já podemos aguardar o segundo revisor aqui. thx

2024-04-06 23:38 UTC, cesar-galvao requested changes
Excelentemente traduzido! Muito bom mesmo. Foram pouquíssimas observações.

2024-04-06 23:38 UTC, cesar-galvao commented on functions.qmd
> +Uma maneira de lembrar o que está acontecendo é pensar em `{{ }}` como olhar para dentro de um túnel --- `{{ var }}` fará uma função dplyr olhar dentro de `var` em vez de procurar por uma variável ch
```suggestion
Uma maneira de lembrar o que está acontecendo é pensar em `{{ }}` como olhar para dentro de um túnel --- `{{ var }}` fará uma função dplyr olhar dentro de `var` em vez de procurar por uma variável chamada `var`.
```

2024-04-06 23:38 UTC, cesar-galvao commented on functions.qmd
> +2.  Para cada uma das funções a seguir, liste todos os argumentos que usam avaliação organizada (*tidy-evaluation) e descreva se eles usam mascaramento de dados (*data-masking*) ou seleção organizada
```suggestion
2.  Para cada uma das funções a seguir, liste todos os argumentos que usam avaliação organizada (*tidy-evaluation) e descreva se eles usam mascaramento de dados (*data-masking*) ou seleção organizada (tidy-selection): `distinct()`, `count()`, `group_by()`, `rename_with()`, `slice_min()`, `slice_sample()`.
```

2024-04-06 23:39 UTC, cesar-galvao commented
@scopinho pronto para a sua avaliação dos comentários!

2024-04-08 19:41 UTC, scopinho commented
@cesar-galvao , muito obrigado pela revisao!
@beatrizmilz , mas um com primeiro e segundo revisores completado. Acho que podemos concluiu tb?

2024-04-22 14:46 UTC, beatrizmilz commented
> @cesar-galvao , muito obrigado pela revisao! @beatrizmilz , mas um com primeiro e segundo revisores completado. Acho que podemos concluiu tb?

Sim!! Muito obrigada @scopinho @carlossb1 e @cesar-galvao !

2024-04-22 14:47 UTC, beatrizmilz commented on functions.qmd
> +# Funções {#sec-functions}
```suggestion
# ✅ Funções {#sec-functions}
```

2024-04-22 14:48 UTC, merged