Tradução: iteration.qmd
cienciadedatos/pt-r4ds pull request #75
Opened 2023-12-20 16:36 UTC by scopinho

Tradução inicial do iteration.qmd
Notas Importantes:

1-) Este capítulo utiliza planilhas Excel que estão em data/gapminder do lfonte do livro. Apesar dos conteúdo estar em inglês, o autor usa mais pra exemplificar como iterar para ler vários arquivos .xlsx, e não muito sobre o conteúdo em si. Portanto mantive com o uso destes arquivos Excel ao invés de exportar o dados::dados_gapmider para Excel e usar em PT. Aceito sugestões.

2-) No linha 683, tem um bloco com eval:false que ele usa .csv ao invés dos Excel. Imagino que é apenas código exemplo e o aluno não consegue executá-lo pois não há arquivos .csv. Ainda assim fiz uma pequena tradução

Sugestões são bem-vindas!!!

2024-01-11 13:33 UTC, cmusso86 commented
Olá, posso revisar esse capítulo!

2024-01-27 18:32 UTC, cmusso86 requested changes
Fui até a linha 435. Tentei manter coerência com o capítulo "retangling"

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +`median()` propaga esses valores ausentes, nos dando uma saída abaixo do ideal:
```suggestion
`median()` propaga esses valores ausentes, fornecendo um resultado não ideal:
```
achei "abaixo do ideal" estranho... e o literal "subótimo" muito  pouco usado...

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Isso é um pouco detalhado, então R vem com um atalho útil: para esse tipo de função descartável, ou **anônima**[^iteration-1], você pode substituir `function` por `\`[^iteration-2 ]:
```suggestion
Isso é um tanto verboso, então R vem com um atalho útil: para esse tipo de função descartável, ou **anônima**[^iteration-1], você pode substituir `function` por `\`[^iteration-2 ]:
```

existe essa  tradução direta, que acho que melhor e vejo pessoas usando em português.

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +[^iteration-1]: Anônimo, porque nunca lhe demos explicitamente um nome com `<-`.
```suggestion
[^iteration-1]: Ela é anônima, porque nunca lhe demos explicitamente um nome com `<-`.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +    Agora recomendamos a sintaxe base, `\(x) x + 1`.
só comentando haha, achei feião esse jeito

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Se você olhar com atenção, poderá intuir que as colunas são nomeadas usando uma especificação de cola (@sec-glue) como `{.col}_{.fn}` onde `.col` é o nome da coluna original e `. fn` é o nome da funç
```suggestion
Se você olhar com atenção, poderá intuir que as colunas são nomeadas usando uma especificação da função glue (@sec-glue) como `{.col}_{.fn}` onde `.col` é o nome da coluna original e `. fn` é o nome da função.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Como você aprenderá na próxima seção, você pode usar o argumento `.names` para fornecer sua própria especificação de cola (*glue*).
```suggestion
Como você aprenderá na próxima seção, você pode usar o argumento `.names` para fornecer sua própria especificação da função *glue*.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Poderíamos especificar o nosso próprio se quiséssemos que o nome da função viesse primeiro[^iteration-3]:
```suggestion
Poderíamos especificar o nosso próprio argumento se quiséssemos que o nome da função viesse primeiro[^iteration-3]:
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +[^iteration-3]: Atualmente você não pode alterar a ordem das colunas, mas pode reordená-las após o fato usando `relocate()` ou similar.
```suggestion
[^iteration-3]: Atualmente você não pode alterar a ordem das colunas, mas pode reordená-las posteriormente usando `relocate()` ou similar.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Portanto, dplyr fornece duas variantes de `across()` chamadas `if_any()` e `if_all()`:
```suggestion
Por isso, dplyr fornece duas variantes de `across()` chamadas `if_any()` e `if_all()`:
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Por exemplo, [Jacob Scott](https://twitter.com/_wurli/status/1571836746899283969) usa esta pequena função auxiliar que envolve um monte de funções do pacote lubridate para expandir todas as colunas d
```suggestion
Por exemplo, [Jacob Scott](https://twitter.com/_wurli/status/1571836746899283969) usa esta pequena função auxiliar que agrega um monte de funções do pacote lubridate para expandir todas as colunas de data em colunas de ano, mês e dia:
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +Esta é uma técnica útil para conhecer porque às vezes você encontrará um problema que atualmente não é possível resolver com `across()`: quando você tem grupos de colunas com os quais deseja calcular
```suggestion
Esta é uma técnica útil para conhecer porque às vezes você encontrará um problema que atualmente não é possível resolver com `across()`: quando você tem grupos de colunas com os quais deseja realizar cálculos simultaneamente.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +3.  Ajuste `expande_datas()` para remover automaticamente as colunas de data após elas terem sido expandidas.
```suggestion
3.  Ajuste `expand_dates()` para remover automaticamente as colunas de data após elas terem sido expandidas.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +    Você precisa abraçar algum argumento?
ainda não estou convencida que "abraçar" seria o melhor termo, hehe. Mas não pensei em um melhor...

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +4.  Explique o que faz cada etapa do pipeline nesta função.
```suggestion
4.  Explique o que cada etapa do pipeline faz nesta função.
```

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +    De qual recurso especial de `where()` estamos aproveitando?
```suggestion
    De qual recurso especial de `where()` estamos nos aproveitando?
```
ou "Qual recurso especial de `where()` estamos aproveitando"
o verbo muda a regência se preferir usar ou não a preposição "de"

2024-01-27 18:32 UTC, cmusso86 commented on iteration.qmd
> +## Lendo múltiplos arquivos
continuarei daqui depois

2024-01-29 22:43 UTC, cmusso86 requested changes
Finalizei a revisão. Eu fiquei na dúvida se deveríamos manter data frame em itálico ou não.
No mais, adorei revisar esse capítulo, aprendi várias coisas novas.

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Neste exemplo específico, há outra otimização que você pode fazer, vinculando todos os *data frames* anteriormente.
```suggestion
Neste exemplo específico, há outra otimização que você pode fazer, vinculando todos os data frames primeiro.
```
Não é literal, mas achei que ficava mais claro assim em português

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Infelizmente, às vezes não é possível ir de `map()` direto para `list_rbind()` porque os *data frames* são tão heterogêneos que `list_rbind()` falha ou produz um *data frame* que não é muito útil.
```suggestion
Infelizmente, às vezes não é possível ir de `map()` direto para `list_rbind()` porque os data frames são tão heterogêneos que `list_rbind()` falha ou resulta um data frame que não é muito útil.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Então, uma estratégia muito útil é capturar a estrutura dos quadros de dados para que você possa explorá-la usando suas habilidades em ciência de dados.
```suggestion
Então, uma estratégia muito útil é capturar a estrutura dos data frames para que você possa explorá-la usando suas habilidades em ciência de dados.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +[^iteração-6]: Não vamos explicar como funciona, mas se você olhar a documentação para as funções usadas, você conseguirá decifrar.
```suggestion
[^iteração-6]: Não vamos explicar como ela funciona, mas se você olhar a documentação para as funções usadas, você conseguirá decifrá-la.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Você pode então aplicar esta função a todos os arquivos e talvez fazer alguma pivotagem para facilitar a visualização de onde estão as diferenças.
Não achei como traduzir "pivoting" no glossário. EU já vi traduzirem como pivotamento ou pivoteamento, mas não pivotagem. hehehe Não sei como foi decidido aqui.

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +- Salvar vários *data frames* em um banco de dados.
```suggestion
- Salvar vários data frames em um banco de dados.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +- Salvar vários *data frames* em vários arquivos `.csv`.
```suggestion
- Salvar vários data frames em vários arquivos `.csv`.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +A maneira mais fácil de fazer isso é criando um modelo, um *data frame* fictício que contém todas as colunas desejadas, mas apenas uma amostra dos dados.
```suggestion
A maneira mais fácil de fazer isso é criando um modelo, um data frame fictício que contém todas as colunas desejadas, mas apenas uma amostra dos dados.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Mas não nos importamos com a saída de `adiciona_arquivo()`, então em vez de `map()` é um pouco melhor usar `walk()`.
```suggestion
Mas não nos importamos com a saída de `adiciona_arquivo()`, então em vez de `map()` é ligeiramente melhor usar `walk()`.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
>  Now we can see if we have all the data in our table:
```suggestion
Agora podemos verificar se temos todos os dados na nossa tabela:
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +`transparencia` é nossa variável de agrupamento e `data` é uma coluna de lista contendo um tibble para cada valor único de `transparencia`:
```suggestion
`transparencia` é nossa variável de agrupamento e `data` é uma coluna-lista contendo um tibble para cada valor único de `transparencia`:
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +Então, se quiséssemos salvar esses *data frames* manualmente, poderíamos escrever algo como:
```suggestion
Então, se quiséssemos salvar esses data frames manualmente, poderíamos escrever algo como:
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +sso é um pouco diferente dos nossos usos anteriores de `map()` porque há dois argumentos que estão mudando, não apenas um.
```suggestion
Isso é um pouco diferente dos nossos usos anteriores de `map()` porque há dois argumentos que estão mudando, não apenas um.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +#|   de aproximadamente 1 quilate.
```suggestion
#|   em torno de 1 quilate.
```

2024-01-29 22:43 UTC, cmusso86 commented on iteration.qmd
> +No entanto, você verá loops `for` em códigos por aí, então aprenderá sobre eles no próximo capítulo, onde discutiremos algumas ferramentas do R base importantes.
```suggestion
No entanto, você verá loops `for` em códigos por aí, então aprenderá sobre eles no próximo capítulo, onde discutiremos algumas ferramentas importantes do R base.
```

2024-04-02 01:27 UTC, cmusso86 commented
Pessoal, eu tava na expectativa de dar uma segunda vista d'olhos antes de passar para o segundo revisor, mas estou bastante ocupada nas próximas semanas.

2024-04-02 11:08 UTC, beatrizmilz commented
> Pessoal, eu tava na expectativa de dar uma segunda vista d'olhos antes de passar para o segundo revisor, mas estou bastante ocupada nas próximas semanas.

Fica tranquila!

2024-05-28 22:36 UTC, anacarolinamoreno commented on iteration.qmd
> +-   `group_by()` junto com a `summarize()` calcula estatísticas sumarizadas para cada subconjunto.
Concordo que "sumarizadas" não deve ser usado se temos a expressão "resumidas". No caso da sugestão, só acho que temos que trocar "resumo" por "resumidas", para efeito de concordância.

2024-06-26 14:33 UTC, debora-s commented
Olá @beatrizmilz  posso fazer a revisão desse também. Estou terminando o outro.

2024-06-26 21:16 UTC, beatrizmilz commented
> Olá @beatrizmilz posso fazer a revisão desse também. Estou terminando o outro.

Eba! Vou adicionar seu nome então!

2024-08-03 15:22 UTC, beatrizmilz commented
Oi @debora-s !
Se você precisar de alguma ajuda, me avisa.
Esse link pode ser útil: https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html
Atenção para a parte que comenta sobre esse botão: 
![imagem](https://github.com/user-attachments/assets/351db961-9309-4e22-a29b-e63a044e5ace)
Ele ajuda muito a deixar mais fácil para aceitar as sugestões depois!
<3

2024-09-14 10:18 UTC, beatrizmilz commented
Pessoal, falta super pouco. Vou fazer a revisão que falta desse capítulo!

2024-09-14 10:40 UTC, debora-s commented
> Pessoal, falta super pouco. Vou fazer a revisão que falta desse capítulo!

Oi @beatrizmilz  estava terminando a revisão outro capitulo, porem estive doente. tive que parar com tudo. Posso fazer essa revisão amanhã. beijos

2024-09-14 10:44 UTC, beatrizmilz commented
> > Pessoal, falta super pouco. Vou fazer a revisão que falta desse capítulo!
> 
> Oi @beatrizmilz estava terminando a revisão outro capitulo, porem estive doente. tive que parar com tudo. Posso fazer essa revisão amanhã. beijos

Oi Débora!!
Ah, eu não comecei, então vou manter seu nome.
Achei que você não tinha começado ainda!!

2024-09-14 10:50 UTC, debora-s commented
> > > Pessoal, falta super pouco. Vou fazer a revisão que falta desse capítulo!
> > 
> > 
> > Oi @beatrizmilz estava terminando a revisão outro capitulo, porem estive doente. tive que parar com tudo. Posso fazer essa revisão amanhã. beijos
> 
> Oi Débora!! Ah, eu não comecei, então vou manter seu nome. Achei que você não tinha começado ainda!!

estou terminando o rectangling. Amanhã pego esse aqui, tá bem?! abraços

2024-09-14 10:58 UTC, scopinho commented
@cmusso86 , muito obrigado pela 1a revisão.....(uffa..acho que eu não estava em um bom dia quando fiz esta kkk)
@beatrizmilz ...1a revisão feita.

2024-09-25 16:30 UTC, debora-s requested changes
Olá, revisão 2 finalizada

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Aprender programação funcional pode facilmente se tornar bastante abstrato, mas neste capítulo manteremos as coisas concretas, concentrando-nos em três tarefas comuns: modificar múltiplas colunas, le
```suggestion
Aprender programação funcional pode facilmente se tornar bastante abstrato, mas neste capítulo manteremos as coisas concretas, concentrando-nos em três tarefas comuns: modificar múltiplas colunas, ler vários arquivos e salvar vários objetos.
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Imagine que você tem esse problema simples e deseja contar o número de observações e calcular a mediana de cada coluna.
```suggestion
Imagine que você tem esse *tibble* simples e deseja contar o número de observações e calcular a mediana de cada coluna.
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Isso é um tanto verboso, então R vem com um atalho útil: para esse tipo de função descartável, ou **anônima**[^iteration-1], você pode substituir `function` por `\`[^iteration-2 ]:
```suggestion
Isso é um tanto detalhado ou longo demais, então R vem com um atalho útil: para esse tipo de função descartável, ou **anônima**[^iteration-1], você pode substituir `function` por `\`[^iteration-2 ]:
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +[^iteration-3]: Atualmente você não pode alterar a ordem das colunas, mas pode reordená-las posteriormente usando `relocate()` ou similar.
```suggestion
[^iteration-3]: Atualmente, você não pode alterar a ordem das colunas, mas pode reordená-las posteriormente usando `relocate()` ou similar.
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Atualmente não há como fazer isso com `across()`[^iteration-4], mas é relativamente simples com `pivot_longer()`:
```suggestion
Atualmente, não há como fazer isso com `across()`[^iteration-4], mas é relativamente simples com `pivot_longer()`:
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +    Você precisa abraçar algum argumento?
```suggestion
    Você precisa adotar algum argumento?
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +    Você precisa abraçar algum argumento?
Oie @cmusso86  pesquisei aqui e a palavra adotar parece fazer mais sentido nessa frase e se conecta com a anterior em termos de sentido. Mas é de fato, dificil..

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Para tornar concreto nosso exemplo motivador, este livro contém uma pasta com 12 planilhas Excel contendo dados do pacote gapminder.
```suggestion
Para tornar nosso exemplo motivador mais concreto, este livro contém uma pasta com 12 planilhas Excel contendo dados do pacote gapminder.
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Às vezes, o próprio nome do arquivo contém dados.
```suggestion
Às vezes, o nome do arquivo é o próprio dado .
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Em casos mais complicados, pode haver outras variáveis ​​armazenadas no nome do diretório ou talvez o nome do arquivo contenha outros dados.
```suggestion
Em casos mais complicados, pode haver outras variáveis ​​armazenadas no nome do diretório ou talvez o nome do arquivo contenha vários elementos de dados.
```

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Nesse caso, use `set_names()` (sem quaisquer argumentos) para registrar o caminho (*path*) completo e, em seguida, use a função `tidyr::separate_wider_delim()` e similares para transformá-los em colu
concordo com o questinamento. É no contexto do capítulo que a tradução pode fazer sentido, ou não.

2024-09-25 16:30 UTC, debora-s commented on iteration.qmd
> +Recomendamos essa abordagem porque ela evita que você se preocupe em acertar o primeiro arquivo antes de passar para o resto.
```suggestion
Recomendamos essa abordagem porque ela evita que você fique obcecado em acertar o primeiro arquivo antes de passar para os demais.
```

2024-09-25 16:34 UTC, beatrizmilz commented
Oi @debora-s ! Que ótimo, muito obrigada!
No final de semana pretendo aceitar as sugestões e incorporar a versão traduzida no livro!

2024-09-26 09:24 UTC, scopinho commented
> Oi @debora-s ! Que ótimo, muito obrigada! No final de semana pretendo aceitar as sugestões e incorporar a versão traduzida no livro!

oi @debora-s , muito obrigado pela revisão!
oi @beatrizmilz , já comitei as revisões da Debora. Mais um pro livro. ;-)

2024-11-04 17:45 UTC, merged

2024-11-04 18:28 UTC, beatrizmilz commented
Está lá! https://cienciadedatos.github.io/pt-r4ds/iteration.html