Tradução: layers.qmd
cienciadedatos/pt-r4ds pull request #77
Opened 2023-12-28 16:03 UTC by fernandaperes

Oi!
Tentei seguir o padrão de tradução utilizado no capítulo data-visualize:

- mapping: mapeamento
- aesthetics: atributos estéticos
- geometrical object: geometria
- the geom: a geometria

Outras decisões de tradução que tomei ao longo do capítulo (estou aberta a sugestões):
- facets: facetas
- stats: transformações estatísticas
- jittering: mantive como jittering, mas há uma explicação de que é a adição de um ruído aleatório

2023-12-28 17:16 UTC, beatrizmilz commented
@Luaaalex O capítulo está pronto para ser revisado!

https://github.com/cienciadedatos/pt-r4ds/issues/14#issuecomment-1858863744

2024-01-02 21:12 UTC, Luaaalex commented
Obrigada @beatrizmilz  
Ok, vou iniciar a revisão! Vou mantenho o meu andamento do capítulo por aqui =)

2024-01-06 00:59 UTC, Luaaalex requested changes
Revisão 1 de layers, finalizada!

2024-01-06 00:59 UTC, Luaaalex commented on layers.qmd
> +#|   1500 diamantes com corte Justo, 5000 Bom, 12000 Muito Bom, 14000 Premium e
Nesse contexto "Fair" seria mais próximo "aceitável ou regular" do que _"Justo"_.

2024-01-06 00:59 UTC, Luaaalex commented on layers.qmd
> +    #|   1500 diamantes com corte Justo, 5000 Bom, 12000 Muito Bom, 14000 Premium e
Faria alteração para "corte Aceitável ou Regular"

2024-01-06 00:59 UTC, Luaaalex commented on layers.qmd
> +    #|   os diamantes com corte Justo representam 0.03, Bom 0.09, Muito Bom 0.22,
Faria alteração para "corte Aceitável ou Regular"

2024-01-06 00:59 UTC, Luaaalex commented on layers.qmd
> +    #|   (com níveis justo, bom, muito bom, premium e ideal). Para cada tipo
(com níveis aceitável...)

2024-01-29 12:27 UTC, fernandaperes commented on layers.qmd
> +#|   de um círculo, 14 - triângulo com ponta para cima e quadrado,
Acho que esse é um erro da versão original. Apesar de eles descreverem como "triângulo para baixo" o desenho é com a ponta para cima...

2024-01-29 12:30 UTC, fernandaperes commented on layers.qmd
> +#|   1500 diamantes com corte Justo, 5000 Bom, 12000 Muito Bom, 14000 Premium e
"Justo" é o termo usado na base traduzida que estamos utilizando, do pacote "dados".

2024-01-29 12:31 UTC, fernandaperes commented on layers.qmd
> +#|   entre a eficiência de combustível na estrada e o tamanho do motor dos carros
De acordo!

2024-01-29 12:33 UTC, fernandaperes commented on layers.qmd
> +#|   20 - ponto (círculo menor), 21 - círculo preenchido em vermelho,
Apesar de estar escrito "azul" em inglês, a figura está em vermelho (https://r4ds.hadley.nz/layers)... Por isso troquei na tradução. Mas podemos trocar a cor, se vocês acharem melhor.

2024-02-17 21:10 UTC, cesar-galvao reviewed
Revisei até a linha 526! Amanhã reviso a segunda metade.

2024-02-17 21:10 UTC, cesar-galvao commented on layers.qmd
> +Uma linha escreve todos os pontos pertencentes à categoria `4`, outra linha descreve os pontos pertencentes à categoria `d`, e uma terceira linha descreve todos os pontos pertencentes à categoria `t`
```suggestion
Uma linha descreve todos os pontos pertencentes à categoria `4`, outra linha descreve os pontos pertencentes à categoria `d`, e uma terceira linha descreve todos os pontos pertencentes à categoria `t`.
```

2024-02-17 21:10 UTC, cesar-galvao commented on layers.qmd
> +#|   entre a eficiência de combustível na estrada e o tamanho do motor dos carros
```suggestion
#|   entre a eficiência de combustível na rodovia e o tamanho do motor dos carros
```

2024-02-17 21:10 UTC, cesar-galvao commented on layers.qmd
> +#|   entre a eficiência de combustível na estrada e o tamanho do motor dos carros
Mandei a sugestão de alteração como commit pra ficar mais fácil na composição da versão final.

2024-02-17 21:10 UTC, cesar-galvao commented on layers.qmd
> +No gráfico a seguir, não apenas nós utilizamos uma nova geometria (`geom_density_ridges()`), mas também mapeamos a mesma variável a múltiplos atributos estéticos (`tracao` foi mapeada em `y`, `fill`
```suggestion
No gráfico a seguir, nós não apenas utilizamos uma nova geometria (`geom_density_ridges()`), mas também mapeamos a mesma variável a múltiplos atributos estéticos (`tracao` foi mapeada em `y`, `fill` e `color`), além de definirmos um atributo estético (`alpha = 0.5`) para tornar as curvas de densidade transparentes.
```

2024-02-17 21:10 UTC, cesar-galvao commented on layers.qmd
> +    #|   suavizadas separadas, com diferentes tipos de linhas foram ajustadas a
```suggestion
    #|   suavizadas separadas, com diferentes tipos de linhas, foram ajustadas a
```

2024-02-18 18:18 UTC, cesar-galvao reviewed
A tradução ta muito boa mesmo, especialmente considerando o tamanho desse capítulo!

2024-02-18 18:18 UTC, cesar-galvao commented on layers.qmd
> +A essa altura, você teria um gráfico completo.
```suggestion
A essa altura, você teria um gráfico completo, mas poderia ir além e ajustar as posições das geoms no sistema de coordenadas (com ajustes de posição) ou dividir o gráfico em subgráficos (criando facetas).
```

2024-02-18 18:18 UTC, cesar-galvao commented on layers.qmd
> +Mas, você poderia ir além e ajustar as posições das geoms no sistema de coordenadas (com ajustes de posição) ou dividir o gráfico em subgráficos (criando facetas).
```suggestion
```

2024-02-18 18:18 UTC, cesar-galvao commented on layers.qmd
> +Mas, você poderia ir além e ajustar as posições das geoms no sistema de coordenadas (com ajustes de posição) ou dividir o gráfico em subgráficos (criando facetas).
Não se usa vírgula após a conjunção "mas" nesse caso. Além disso, parece fazer mais sentido tratar essa linha e a anterior como uma frase só, como no original.

2024-02-18 18:18 UTC, cesar-galvao commented on layers.qmd
> +Você pode usar esse método para construit *qualquer* gráfico que imaginar.
```suggestion
Você pode usar esse método para construir *qualquer* gráfico que imaginar.
```

2024-02-18 18:18 UTC, cesar-galvao commented
@fernandaperes acabei minha revisão. Está pronto para você revisar minhas sugestões e pedir o merge pra Beatriz!

2024-02-18 18:27 UTC, cesar-galvao commented on layers.qmd
> +No gráfico a seguir, não apenas nós utilizamos uma nova geometria (`geom_density_ridges()`), mas também mapeamos a mesma variável a múltiplos atributos estéticos (`tracao` foi mapeada em `y`, `fill`
Aqui foi só uma questão de paralelismo.

2024-02-23 14:22 UTC, fernandaperes commented on layers.qmd
> +-   *Smoothers* ajustam um modelo aos seus dados e, em seguida, representam as predições deste modelo.
Eu achei interessante adicionar, sim.

2024-02-27 21:56 UTC, fernandaperes commented
@beatrizmilz 
Eu preciso fechar o pull request para você conseguir atualizar?

2024-03-31 22:53 UTC, merged