Tradução: communication.qmd
cienciadedatos/pt-r4ds pull request #80
Opened 2024-01-08 21:17 UTC by scopinho

Tradução inicial do capítulo communication.qmd

Notas importantes:
1-) Uso do pacotes dados para diamantes, milhas e presidentes_eua ao invés das bases otiginais.
2-) Plots patchwork ficaram como gráficos *pacthword*
3-) Layout ficou layout mesmo

Liberado para revisão.
Qualquer sugestão é bem-vinda!

2024-01-09 10:18 UTC, scopinho commented on communication.qmd
> +No @sec-exploratory-data-análise, você aprendeu como usar gráficos como ferramentas para *exploração*.
```suggestion
No @sec-exploratory-data-analysis, você aprendeu como usar gráficos como ferramentas para *exploração*.
```

2024-01-09 10:19 UTC, scopinho commented on communication.qmd
> +    Como alternativa, consulte o [pacote ggforce](https://ggforce.data-imaginist.com/index.html), especificamente [`geom_mark_hull()`](https://ggforce.data-imaginist.com/reference/ geom_mark_hull.htm
```suggestion
    Como alternativa, consulte o [pacote ggforce](https://ggforce.data-imaginist.com/index.html), especificamente [`geom_mark_hull()`](https://ggforce.data-imaginist.com/reference/geom_mark_hull.html), que permite anotar subconjuntos de pontos.
```

2024-01-09 10:21 UTC, scopinho commented on communication.qmd
> +[^comunicação-2]: Muitas pessoas se perguntam por que o tema padrão tem um fundo cinza.
```suggestion
[^communication-2]: Muitas pessoas se perguntam por que o tema padrão tem um fundo cinza.
```

2024-01-27 17:40 UTC, cmusso86 commented
posso revisar :)

2024-02-01 02:04 UTC, cmusso86 requested changes
Fiz uma primeira revisão completa, mas acho que vou ar mais uma olhada porque fiz meio rápido. 
Eu corrigir lugares em que "plot" estava traduzido como "lote" e "enredo", alguns typos, e locais em que "highway" estava como "rodoviária" rsrs. 

Eu tentei manter a consistência com o capítulo de EDA que revisei antes. Pelo menos na estatística (ou onde eu fiz estatística hehe), eu vejo o "bin" com o sentido de classe (que é como chamamos as divisões , a discretização da variável contínua.

2024-02-09 20:22 UTC, scopinho commented
oi @cmusso86 ... estou um.pouco atrasado neste PR , mas espero fazer um catchup nos próximos dias. ;-)

2024-05-30 09:56 UTC, scopinho commented
Olá @cmusso86 , revisões aplicadas! Muito obrigado pela ajuda na 1a revisão!!!

2024-08-25 18:41 UTC, cesar-galvao reviewed
Excelente tradução. Fiz pouquissimas alterações.

2024-08-25 18:41 UTC, cesar-galvao commented on communication.qmd
> +Também usaremos um pouco do pacote dplyr para transformação de dados, **scales** para substituir quebras, rótulos, transformações e paletas padrão, e alguns pacotes de extensão ggplot2, incluindo **g
```suggestion
Também usaremos um pouco do pacote dplyr para transformação de dados, **scales** para substituir quebras, rótulos, transformações e paletas padrão, e alguns pacotes de extensão ggplot2, incluindo **ggrepel** ([https://ggrepel.slowkow.com](https://ggrepel.slowkow.com/)) de Kamil Slowikowski e o **patchwork** ([https://patchwork.data-imaginist.com](https://patchwork.data-imaginist .com/)) de Thomas Lin Pedersen.
```

2024-08-25 18:41 UTC, cesar-galvao commented on communication.qmd
> +Por exemplo, é mais fácil ver a relação precisa entre `quilate` e `preço` se aplicarmos o logaritimo:
```suggestion
Por exemplo, é mais fácil ver a relação precisa entre `quilate` e `preço` se aplicarmos o logaritmo:
```

2024-08-25 18:41 UTC, cesar-galvao commented on communication.qmd
> +#|   Três gráficos hexagonais onde a cor dos hexagonos mostram o número de observações
```suggestion
#|   Três gráficos hexagonais onde a cor dos hexágonos mostram o número de observações 
```

2024-08-25 18:41 UTC, cesar-galvao commented on communication.qmd
> +#|   À esquerda, gráfico de dispersão da eficiência de combustível nas rodovias versus cilindrada
```suggestion
#|   À esquerda, gráfico de dispersão da eficiência de combustível nas rodovias versus cilindrada. 
```

2024-08-25 18:41 UTC, cesar-galvao commented on communication.qmd
> +#|   10 to 25. A curva suave sobreposta mostra uma tendência ligeiramente
```suggestion
#|   10 a 25. A curva suave sobreposta mostra uma tendência ligeiramente 
```

2024-08-25 18:42 UTC, cesar-galvao commented
@beatrizmilz @scopinho 2a revisao encerrada!

2024-09-14 09:08 UTC, merged

2024-09-14 09:19 UTC, beatrizmilz commented
@scopinho @cmusso86 @cesar-galvao muuuuuito obrigada!!
Está no ar!
https://cienciadedatos.github.io/pt-r4ds/communication.html

Agora estou aceitando as sugestões de #85!

2024-09-14 10:44 UTC, scopinho commented
> @scopinho @cmusso86 @cesar-galvao muuuuuito obrigada!! Está no ar! https://cienciadedatos.github.io/pt-r4ds/communication.html
> 
> Agora estou aceitando as sugestões de #85!

Valeu pessoal!! Mais um pro livro!!! Obrigado pela ajuda!

@beatrizmilz , que ajuda precisa no #85 ? Pelo que vi já fez o merge? Qq coisa avisa que vejo se consigo ajudar.

2024-09-15 20:39 UTC, beatrizmilz commented
> > @scopinho @cmusso86 @cesar-galvao muuuuuito obrigada!! Está no ar! https://cienciadedatos.github.io/pt-r4ds/communication.html
> > Agora estou aceitando as sugestões de #85!
> 
> Valeu pessoal!! Mais um pro livro!!! Obrigado pela ajuda!
> 
> @beatrizmilz , que ajuda precisa no #85 ? Pelo que vi já fez o merge? Qq coisa avisa que vejo se consigo ajudar.

Oi @scopinho ! Sobre o #85, eu estava aceitando as sugestões feitas pelas pessoas que fizeram a revisão.. Mas deu certo! Já fiz o merge! Obrigada!