Traducao pt 2ed
cienciadedatos/pt-r4ds pull request #93
Opened 2024-04-03 02:25 UTC by MaximilianCF

2024-04-03 10:45 UTC, beatrizmilz commented
Uhul! Deu certo @MaximilianCF ! Muito obrigada. Agora precisamos de pessoas para revisar!

2024-04-03 11:04 UTC, beatrizmilz reviewed
Revisão 1 feita! Muito obrigda @MaximilianCF !
Agora vamos esperar alguém que quer fazer uma segunda revisão :D

2024-04-03 11:04 UTC, beatrizmilz commented on workflow-help.qmd
> +    Usualmente isto envolve a criação de um objeto R menor e mais simples do que aquele que você está criando de verdade ou até mesmo usar dados internos.
```suggestion
    Usualmente isto envolve a criação de um objeto R menor e mais simples do que aquele que você está criando de verdade ou até mesmo usar dados internos[^workflow-help-nt-1].
    
[^workflow-help-nt-1]: **Nota de tradução**: São dados que estão sempre disponíveis no R (ex. mtcars), e são bastante utilizados em exemplos, aulas, tutoriais, entre outros. Outra opção interessante é utilizar dados do pacote `{dados}` para criar exemplos reprodutíveis.
```

2024-04-03 11:04 UTC, beatrizmilz commented on workflow-help.qmd
>  When creating a reprex by hand, it's easy to accidentally miss something, meaning your code can't be run on someone else's computer.
```suggestion
Ao criar um reprex manualmente, é fácil esquecer de algo por acidente, o que significa que seu código pode não ser executado no computador de outra pessoa.
```

2024-04-03 11:04 UTC, beatrizmilz commented on workflow-help.qmd
>  Avoid this problem by using the reprex package, which is installed as part of the tidyverse.
```suggestion
Evite esse problema utilizando o pacote reprex, que é instalado como parte do tidyverse.
```

2024-04-03 11:05 UTC, beatrizmilz commented
Agora que eu vi que o @brunomioto e o @nextmarte escreveram que gostariam de revisar o capítulo!

2024-04-03 11:43 UTC, MaximilianCF commented
Bom Dia Beatriz,

UFFAAAAA...kkkkk
Dormi pensando na função do GITHUB, que bom que deu tudo certo e consegui enviar a tradução.
Posso escolher outro capítulo para traduzir?
Obrigado.
Abs.,

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
On abr 3 2024, at 7:46 am, Beatriz Milz ***@***.***> wrote:
>
>
> Uhul! Deu certo @MaximilianCF ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2FMaximilianCF&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D) ! Muito obrigada. Agora precisamos de pessoas para revisar!
> —
> Reply to this email directly, view it on GitHub ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F93%23issuecomment-2034226899&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/3?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOPIBB73GMHAXGNLH3TY3PMWVAVCNFSM6AAAAABFUN3TKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZUGIZDMOBZHE&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you were mentioned.
>

2024-04-04 00:42 UTC, beatrizmilz commented
> Bom Dia Beatriz, UFFAAAAA...kkkkk Dormi pensando na função do GITHUB, que bom que deu tudo certo e consegui enviar a tradução. Posso escolher outro capítulo para traduzir? Obrigado. Abs., Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
> […](#)
> On abr 3 2024, at 7:46 am, Beatriz Milz ***@***.***> wrote: Uhul! Deu certo @MaximilianCF ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2FMaximilianCF&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D) ! Muito obrigada. Agora precisamos de pessoas para revisar! — Reply to this email directly, view it on GitHub ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F93%23issuecomment-2034226899&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/3?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOPIBB73GMHAXGNLH3TY3PMWVAVCNFSM6AAAAABFUN3TKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZUGIZDMOBZHE&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you were mentioned.

Uhuuuu! 
Obrigada perseverança hahaha.
Então, não tem capítulos para traduzir mais, apenas capítulos para revisar!

https://github.com/cienciadedatos/pt-r4ds/pulls

2024-04-04 00:45 UTC, MaximilianCF commented
Sim, depois eu vi que para tradução não havia mais.

Recebi a confirmação da revisão. Vou olhar amanhã as instruções para revisão.
Obrigado

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPUE1LQ01JVkxLT0ZHMjI0WEdFREhNS1JFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
On abr 3 2024, at 9:43 pm, Beatriz Milz ***@***.***> wrote:
>
>
> > Bom Dia Beatriz, UFFAAAAA...kkkkk Dormi pensando na função do GITHUB, que bom que deu tudo certo e consegui enviar a tradução. Posso escolher outro capítulo para traduzir? Obrigado. Abs., Enviado do Mailspring @./0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
> > … (#)
> > On abr 3 2024, at 7:46 am, Beatriz Milz @.> wrote: Uhul! Deu certo @MaximilianCF ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2FMaximilianCF&recipient=cmVwbHkrQVdBUUhPUE1LQ01JVkxLT0ZHMjI0WEdFREhNS1JFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D) @./1?redirect=https%3A%2F%2Fgithub.com%2FMaximilianCF&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D) ! Muito obrigada. Agora precisamos de pessoas para revisar! — Reply to this email directly, view it on GitHub @./2?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F93%23issuecomment-2034226899&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe @.***/3?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOPIBB73GMHAXGNLH3TY3PMWVAVCNFSM6AAAAABFUN3TKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZUGIZDMOBZHE&recipient=cmVwbHkrQVdBUUhPTVdRWEFJNzZCUkFQQUhURE9FREVLR1ZFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you were mentioned.
> >
>
> Uhuuuu!
> Obrigada perseverança hahaha.
> Então, não tem capítulos para traduzir mais, apenas capítulos para revisar!
>
>
> https://github.com/cienciadedatos/pt-r4ds/pulls ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpulls&recipient=cmVwbHkrQVdBUUhPUE1LQ01JVkxLT0ZHMjI0WEdFREhNS1JFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D)
> —
> Reply to this email directly, view it on GitHub ***@***.***/3?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fpull%2F93%23issuecomment-2035872650&recipient=cmVwbHkrQVdBUUhPUE1LQ01JVkxLT0ZHMjI0WEdFREhNS1JFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/4?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHOISYLKMGRRFPIZICUTY3SO2RAVCNFSM6AAAAABFUN3TKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZVHA3TENRVGA&recipient=cmVwbHkrQVdBUUhPUE1LQ01JVkxLT0ZHMjI0WEdFREhNS1JFVkJOSEhJSTNMQU9BQHJlcGx5LmdpdGh1Yi5jb20%3D).
> You are receiving this because you were mentioned.
>

2024-04-22 17:21 UTC, brunomioto requested changes
Revisei, mas não encontrei a continuação da tradução...

2024-04-22 17:21 UTC, brunomioto commented on workflow-help.qmd
> +## Google é seu amigo
```suggestion
## O Google é seu amigo
```

2024-04-22 17:21 UTC, brunomioto commented on workflow-help.qmd
> +Se o Google não ajudar tente o Stack Overflow (https//stackoverflow.com).
```suggestion
Se o Google não ajudar tente o [Stack Overflow](https://stackoverflow.com).
```

2024-04-22 17:21 UTC, brunomioto commented on workflow-help.qmd
> +Comece reservando tempo para buscar uma resposta já existente, incluindo '[R]' para restringir sua busca por perguntas e respostas que usem R.
```suggestion
Comece reservando tempo para buscar uma resposta já existente, incluindo `[R]` para restringir sua busca por perguntas e respostas que usem R.
```

2024-04-22 17:21 UTC, brunomioto commented on workflow-help.qmd
> +-   Em 80% dos casos, criando um excelente reprex pode encontrar a raiz do seu problema.
```suggestion
-   Em 80% dos casos, a criação de um excelente reprex mostrará a raiz do seu problema.
```

2024-04-22 17:21 UTC, brunomioto commented on workflow-help.qmd
>  Let's say you copy this code onto your clipboard (or, on RStudio Server or Cloud, select it):
Não encontrei a tradução da linha 53 até 135

2024-04-22 19:01 UTC, beatrizmilz commented on workflow-help.qmd
>  Let's say you copy this code onto your clipboard (or, on RStudio Server or Cloud, select it):
Realmente, Bruno! Parece que está faltando uma parte! @MaximilianCF será que aconteceu algum erro? Você chegou a traduzir até o final?

2024-04-22 19:17 UTC, MaximilianCF commented on workflow-help.qmd
>  Let's say you copy this code onto your clipboard (or, on RStudio Server or Cloud, select it):
Oi @beatrizmilz Verdade, está faltando mesmo. Não sei o que houve, mas vou completar a tradução. Sorry...


> Realmente, Bruno! Parece que está faltando uma parte! @MaximilianCF será que aconteceu algum erro? Você chegou a traduzir até o final?

2024-04-22 19:34 UTC, MaximilianCF commented on workflow-help.qmd
>  Let's say you copy this code onto your clipboard (or, on RStudio Server or Cloud, select it):
Achei no meu RStudio a tradução completa. Acho que no momento de fazer a atualização no Github foi para o lugar errado.
Não quero mexer também muito para acabar não desorganizando o Github da tradução.
Alguma ideia? Tem como enviar a você @beatrizmilz e aí você atualiza?

2024-04-22 19:42 UTC, beatrizmilz commented on workflow-help.qmd
>  Let's say you copy this code onto your clipboard (or, on RStudio Server or Cloud, select it):
Sim! Poderia me enviar no email? Obrigada!!

milz.bea@gmail.com

2024-04-22 22:44 UTC, beatrizmilz commented
obrigada @MaximilianCF por enviar por email! Bruno, já podemos revisar o que faltou! Obrigada por perceber!! @brunomioto

2024-04-22 23:04 UTC, beatrizmilz commented on workflow-help.qmd
> +Este capítulo encerra a parte  Whole Game deste livro.
```suggestion
Este capítulo encerra a parte "Visão geral" deste livro.
```

2024-04-22 23:04 UTC, beatrizmilz commented on workflow-help.qmd
> +Você viu até agora as partes mais importantes do processo em ciência de dados: visualização, transformação, classificação e importação.
```suggestion
Você viu até agora as partes mais importantes do processo em ciência de dados: visualização, transformação, organização e importação.
```

2024-04-22 23:04 UTC, beatrizmilz commented on workflow-help.qmd
> +Agora você tem uma visão abrangente do processo como um todo e começamos a entrar nos detalhes pormenorizados.
```suggestion
Agora você tem uma visão abrangente do processo como um todo e começamos a entrar nos detalhes.
```

2024-04-22 23:04 UTC, beatrizmilz commented on workflow-help.qmd
> +A próxima parte do livro, Visualização, é um aprofundamento na estrutura dos gráficos e criação de visualização de dados com o ggplot2, exemplos de como usar as ferramentas que aprendeu até agora par
```suggestion
A próxima parte do livro, Visualização, é um aprofundamento na estrutura dos gráficos e criação de visualização de dados com o ggplot2, exemplos de como usar as ferramentas que aprendeu até agora para construir uma análise exploratória de dados e também introduzir boas práticas na criação de gráficos para comunicação.
```

2024-04-23 14:51 UTC, brunomioto commented on workflow-help.qmd
> +   - Use comentários para indicar aonde está o problema;
```suggestion
   - Use comentários para indicar onde está o problema;
```

2024-04-23 14:51 UTC, brunomioto commented on workflow-help.qmd
> +Então execute 'reprex()', aonde a saída padrão está formatada para o Github:
Eu trocaria "aonde" por "onde" aqui

2024-04-23 14:51 UTC, brunomioto commented on workflow-help.qmd
> +Para se manter conenctado de maneira geral com a comunidade do R, recomendamos a leitura do R weekly (https://rweekly.org): é um esforça da comunidade em agregar as notícias mais interessantes sobre
Para acompanhar de forma mais ampla a comunidade do R......

2024-04-23 14:54 UTC, brunomioto commented
Revisado @beatrizmilz ! Adicionei alguns comentários às suas sugestões se tinha algo a melhorar e dei um like se concordava. 

Obrigado e parabéns pela tradução @MaximilianCF !

2024-04-23 16:40 UTC, MaximilianCF commented
Maravilha. Obrigado @brunomioto

2024-04-27 01:45 UTC, nextmarte approved these changes

2024-04-27 21:20 UTC, beatrizmilz commented
Obrigada pessoal!! Vou aceitar essa tradução :D

2024-04-27 21:21 UTC, beatrizmilz commented on workflow-help.qmd
> +# Fluxo de trabalho: obtendo ajuda {#sec-workflow-getting-help}
```suggestion
# ✅ Fluxo de trabalho: obtendo ajuda {#sec-workflow-getting-help}
```

2024-04-27 21:21 UTC, merged