Tradução: data-transform.qmd
cienciadedatos/pt-r4ds pull request #97
Opened 2024-04-28 16:18 UTC by halian-vilela

## Nota aos revisores:
Achei a tradução de `summary` um tanto quanto chatinha. Eu tinha colocado "sumário" mesmo, ao pé da letra, mas depois, mais no final do capítulo, ele utiliza o termo `summary statistics` para englobar coisas como "média" e etc. Aí meio que quebou o uso de "sumário". Eu fui pesquisar e pelo menos na wikipedia o termo utilizado é "síntese estatística" eu achei ok e e voltei atrás aplicando para "summary" no restante do capítulo. Ainda acho um pouco estranho, mas achei OK na falta de algo melhor.

2024-05-07 00:29 UTC, Luaaalex commented
Oi @halian-vilela , tudo bem?
Nas minhas pesquisas encontrei o termo `summary statistics` em um livro de estatística em inglês - para fazer de média, histogram, desvio padrão, etc. Já em português encontrei mais frequentemente o termo `sumarização`. E menos frequente os seguintes termos 
 `Sumarização Estatística`,  `Sumário Estatístico`, [`Estatísticas de Sumarização`](https://www.ibm.com/docs/pt-br/spss-statistics/29.0.0?topic=summarize-statistics). Esse último é a tradução para pt (automática) de um material da IBM sobre estatística. Achei bem apropriado, pois era uma documentação aplicada a dados. Porém, não tenho conhecimento específicos de estatística.

2024-05-07 02:03 UTC, Luaaalex commented
Hoje acabei fazendo 1/3 da revisão, espero acabar amanhã com o restante :)

2024-05-07 13:23 UTC, Luaaalex requested changes
Revisão finalizada! @beatrizmilz 
O ponto que gerou um pouco mais de dúvida foi a tradução dos termos "summary statistic" e "summary". De resto, está tudo certo! Obrigado, @halian-vilela.

2024-05-07 13:23 UTC, Luaaalex commented on data-transform.qmd
> +    A forma do gráfico é muito característica: sempre que você plotar uma média (ou alguma outra síntese estatística)  vs. tamanho do grupo, você verá que a variação diminui à medida que o tamanho da
```suggestion
    A forma do gráfico é muito característica: sempre que você plotar uma média (ou alguma outra sumarização estatística)  vs. tamanho do grupo, você verá que a variação diminui à medida que o tamanho da amostra aumenta[^data-transform-4].
```

2024-05-10 01:01 UTC, halian-vilela commented on data-transform.qmd
> +Ele não modifica o conjunto de dados `flights` já existente, pois as funções do dplyr nunca modificam seus argumentos de entrada.
Oi @Luaaalex !

Creio que aqui usar apenas "entrada" pode ficar um pouco confuso em português. Acho que na versão originao, `inputs` cria um contexto que deixa pouca margem para ambiguidade, mas em português, só "entrada" fica meio vago, por isso optei por adicionar "argumentos" nesse caso para deixar mais claro que estamos falando sobre os argumentos da função.

O que acha?

2024-05-10 01:25 UTC, halian-vilela commented
@Luaaalex @beatrizmilz 

Boa noite!

Revisão feita, deixei só um comentário a respeito de uma sugestão, mas as demais já foram implementadas.

2024-05-10 18:47 UTC, cmusso86 commented
> ## Nota aos revisores:
> Achei a tradução de `summary` um tanto quanto chatinha. Eu tinha colocado "sumário" mesmo, ao pé da letra, mas depois, mais no final do capítulo, ele utiliza o termo `summary statistics` para englobar coisas como "média" e etc. Aí meio que quebou o uso de "sumário". Eu fui pesquisar e pelo menos na wikipedia o termo utilizado é "síntese estatística" eu achei ok e e voltei atrás aplicando para "summary" no restante do capítulo. Ainda acho um pouco estranho, mas achei OK na falta de algo melhor.

@halian-vilela  , na estatística eu vejo chamarem prevalentemente de estatísticas resumo

2024-05-10 19:09 UTC, halian-vilela commented
> > ## Nota aos revisores:
> > Achei a tradução de `summary` um tanto quanto chatinha. Eu tinha colocado "sumário" mesmo, ao pé da letra, mas depois, mais no final do capítulo, ele utiliza o termo `summary statistics` para englobar coisas como "média" e etc. Aí meio que quebou o uso de "sumário". Eu fui pesquisar e pelo menos na wikipedia o termo utilizado é "síntese estatística" eu achei ok e e voltei atrás aplicando para "summary" no restante do capítulo. Ainda acho um pouco estranho, mas achei OK na falta de algo melhor.
> 
> @halian-vilela , na estatística eu vejo chamarem prevalentemente de estatísticas resumo

Oi @cmusso86 pois é! Isso resolveria para a parte do `summary statistics` mas e qdo aparece só `summary`? Como vc resolveria? Só `resumo`? Acho meio estranho....

2024-06-09 14:46 UTC, cesar-galvao requested changes
Essa é uma parcial, fui até a seção do select() e devo continuar depois!

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +Ambas as funções afetam apenas as linhas, e as colunas permanecem intocadas.
```suggestion
Ambas as funções afetam apenas as linhas e as colunas permanecem intocadas.
```

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +Assim como `>` (maior que), você também pode usar `>=` (maior ou igual que), `<` (menor que), `<=` (menor ou igual que), `==` (igual), e `!=` (diferente que).
```suggestion
Assim como `>` (maior que), você também pode usar `>=` (maior ou igual a), `<` (menor que), `<=` (menor ou igual a), `==` (igual a), e `!=` (diferente de).
```

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +Ele não modifica o conjunto de dados `flights` já existente, pois as funções do dplyr nunca modificam seus argumentos de entrada.
Concordo, @halian-vilela

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +Isso até "funciona", no sentido de que não dará um erro, mas ele não vai fazer o que você esperaria, pois `|` primeiro vai avaliar a condição `month == 1` e depois a condição `2`, que não é uma condi
```suggestion
Isso até "funciona", no sentido de que não retornará um erro, mas ele não vai fazer o que você esperaria, pois `|` primeiro vai avaliar a condição `month == 1` e depois a condição `2`, que não é uma condição adequada para se avaliar nesse caso.
```

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +    Ache os vôos que saíram o mais cedo na manhã.
```suggestion
    Ache os vôos que saíram o mais cedo pela manhã. 
```

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +4.  Teve pelo menos um vôo em cada dia de 2013?
```suggestion
4.  Houve pelo menos um vôo em cada dia de 2013?
```

2024-06-09 14:46 UTC, cesar-galvao commented on data-transform.qmd
> +Por exemplo, a saída a seguir irá conter apenas as variáveis `dep_delay`, `arr_delay`, `air_time`, `gain`, `hours` e `gain_per_hour`.
```suggestion
Por exemplo, a saída a seguir conterá apenas as variáveis `dep_delay`, `arr_delay`, `air_time`, `gain`, `hours` e `gain_per_hour`.
```

2024-06-09 14:48 UTC, cesar-galvao commented
> > > ## Nota aos revisores:
> > > Achei a tradução de `summary` um tanto quanto chatinha. Eu tinha colocado "sumário" mesmo, ao pé da letra, mas depois, mais no final do capítulo, ele utiliza o termo `summary statistics` para englobar coisas como "média" e etc. Aí meio que quebou o uso de "sumário". Eu fui pesquisar e pelo menos na wikipedia o termo utilizado é "síntese estatística" eu achei ok e e voltei atrás aplicando para "summary" no restante do capítulo. Ainda acho um pouco estranho, mas achei OK na falta de algo melhor.
> > 
> > 
> > @halian-vilela , na estatística eu vejo chamarem prevalentemente de estatísticas resumo
> 
> Oi @cmusso86 pois é! Isso resolveria para a parte do `summary statistics` mas e qdo aparece só `summary`? Como vc resolveria? Só `resumo`? Acho meio estranho....

Pode parecer estranho mas acho que é algo de comunidade. Eu nao veria problema em usar apenas `resumo`.

2024-06-10 12:49 UTC, cesar-galvao requested changes
@halian-vilela revisão finalizada!

2024-06-10 12:49 UTC, cesar-galvao commented on data-transform.qmd
> +Quando plotamos a habilidade dos rebatedores (medidas pela média de acerto, `performance`) contra o número de oportunidades de acertar a bola (medidas pela númer de vezes ao bastão, `n`), é possível
Aqui eu tenho quase certeza de que a @beatrizmilz tinha uma sugestão para não usar esse verbo emprestado. Procurei, mas não achei no guia. Considere algo como

"Quando montamos um gráfico da habilidade dos rebatedores (...) contra o número de oportunidades (...)"  ou número de oportunidades em função da habilidade dos rebatedores.

2024-06-10 12:49 UTC, cesar-galvao commented on data-transform.qmd
> +    A forma do gráfico é muito característica: sempre que você plotar uma média (ou alguma outra sumarização estatística)  vs. tamanho do grupo, você verá que a variação diminui à medida que o tamanh
```suggestion
    A forma do gráfico é muito característica: sempre que você projetar no gráfico uma média (ou alguma outra sumarização estatística)  vs. tamanho do grupo, você verá que a variação diminui à medida que o tamanho da amostra aumenta[^data-transform-4].
```

2024-06-10 12:49 UTC, cesar-galvao commented on data-transform.qmd
> +#|   Um gráfico de dispersão do número de performance de rebatidas vs. oportunidades de rebatidas
```suggestion
#|   Um gráfico de dispersão do performance de rebatidas vs. oportunidades de rebatidas 
```

2024-06-10 12:49 UTC, cesar-galvao commented on data-transform.qmd
> +#|   continua crescendo linearmente em uma inclinação muito mais rasa atingindo
```suggestion
#|   continua crescendo linearmente em uma inclinação muito mais suave atingindo 
```

2024-06-10 12:51 UTC, cesar-galvao commented
@beatrizmilz me desculpe a demora, me enrolei muito com outras coisas no último mes. Mas saiu :D Ta com o Halian agora.

2024-06-10 23:15 UTC, halian-vilela commented
@cesar-galvao 

Sua revisão ficou excelente, ainda houve vou dar um double check e já commitar as sugestões! Valeu!

**PS:** eu acho que eu mesmo não usei muito o "plotar" no outro capítulo, heuahuae, nesse passou, achou q eu tava muito americanizado, heuaheuaue

2024-06-11 00:11 UTC, halian-vilela commented on data-transform.qmd
> +Quando plotamos a habilidade dos rebatedores (medidas pela média de acerto, `performance`) contra o número de oportunidades de acertar a bola (medidas pela númer de vezes ao bastão, `n`), é possível
```suggestion
Quando montamos um gráfico da habilidade dos rebatedores (medidas pela média de acerto, `performance`) contra o número de oportunidades de acertar a bola (medidas pela númer de vezes ao bastão, `n`), é possível ver dois padrões:
```

2024-06-11 00:25 UTC, halian-vilela commented
@beatrizmilz @cesar-galvao @Luaaalex @cmusso86 

Pessoal, para todos os fins, creio que está finalizada... ainda estou em dúvida em relação à questão do `summary` e todas as possibilidades, queria puxar uma discussão final aqui para a gente bater o martelo e matar o capítulo.

Eu acho que com exceção do termo que falei ali no final, "sumarizar" parece ter um significado em português que expressa bem o que a função faz, eu até fiquei com receio de ser um anglicismo, mas não é.

Mas eu não tenho muita vivência em relação ao melhor termo dentro da comunidade de estatística, queria ouvir melhor a opinião de vocês e aí finalizamos.

Valeu!

2024-06-11 17:13 UTC, beatrizmilz commented
> @beatrizmilz @cesar-galvao @Luaaalex @cmusso86
> 
> Pessoal, para todos os fins, creio que está finalizada... ainda estou em dúvida em relação à questão do `summary` e todas as possibilidades, queria puxar uma discussão final aqui para a gente bater o martelo e matar o capítulo.
> 
> Eu acho que com exceção do termo que falei ali no final, "sumarizar" parece ter um significado em português que expressa bem o que a função faz, eu até fiquei com receio de ser um anglicismo, mas não é.
> 
> Mas eu não tenho muita vivência em relação ao melhor termo dentro da comunidade de estatística, queria ouvir melhor a opinião de vocês e aí finalizamos.
> 
> Valeu!

Halian, geralmente eu uso "sumarizar" sem problemas!

2024-06-11 17:15 UTC, merged