data-import
cienciadedatos/pt-r4ds pull request #99
Opened 2024-05-03 01:17 UTC by albersonmiranda

Tradução capítulo 7

2024-05-06 22:42 UTC, beatrizmilz commented
Obrigada Alberto!!

2024-05-22 19:22 UTC, beatrizmilz commented
Para registrar: a Beatriz Colvara topou fazer a revisão desse capítulo 🎉 Ela ainda não tem uma conta no GitHub, por isso não marquei com o @ dela.

2024-05-27 14:31 UTC, beatrizmilz commented
Lembrete: após aceitar o PR, checar se os links estão funcionando como esperado!

2024-05-27 18:38 UTC, beatrizmilz reviewed
Obrigada @albersonmiranda ! Fiz a primeira revisão, mas tem algumas coisas pequenas que anotei no caminho e falta ainda checar.

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +-   `col_integer()` lê inteiros. Raramente distinguimos inteiros e duplos neste livro porque eles são funcionalmente equivalentes, mas ler inteiros explicitamente pode ocasionalmente ser útil porque
```suggestion
-   `col_integer()` lê números inteiros (*integer*). Raramente distinguimos os números inteiros (*integer*) e reais (*doubles*) neste livro porque eles são funcionalmente equivalentes, mas ler números inteiros explicitamente pode ocasionalmente ser útil porque ocupam metade da memória dos números reais.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +-   `col_character()` lê *strings*. Isso pode ser útil para especificar explicitamente quando você tem uma coluna que é um identificador numérico, ou seja, longas séries de dígitos que identificam um
```suggestion
-   `col_character()` lê textos (*strings*). Isso pode ser útil para especificar explicitamente quando você tem uma coluna que é um identificador numérico, ou seja, longas séries de dígitos que identificam um objeto, mas não faz sentido aplicar operações matemáticas a ele. Exemplos incluem números de telefone, números de seguro social, números de cartão de crédito, etc.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +readr também vem com duas funções úteis para escrever dados de volta para o disco: `write_csv()` e `write_tsv()`.
```suggestion
O pacote readr também vem com duas funções úteis para escrever dados de volta para o disco: `write_csv()` e `write_tsv()`.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +Você também pode especificar como os valores ausentes são escritos com `na`, e se você deseja acrescentar, via o argumento `append`, a um arquivo existente.
```suggestion
Você também pode especificar como os valores ausentes são escritos com `na`, e se você deseja acrescentar as linhas em um arquivo existente, utilizando o argumento `append`.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
>  This makes CSVs a little unreliable for caching interim results---you need to recreate the column specification every time you load in.
```suggestion

```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
>  There are two main alternatives:
```suggestion

```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +Isso faz arquivos CSVs um pouco não confiáveis para armazenar resultados intermediários --- você precisa recriar a especificação das colunas toda vez que carrega os dados.
```suggestion
Isso faz arquivos CSVs um pouco não confiáveis para armazenar resultados intermediários --- você precisa recriar a especificação das colunas toda vez que carrega os dados.
Existem duas formas principais:
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +    #| eval: true
```suggestion
    #| eval: false
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +    read_parquet("estudantes.parquet")
Lembrar de colocar o output aqui!

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +Inserir os dados por coluna pode dificultar a visualização de como as linhas estão relacionadas, então uma alternativa é `tribble()`, abreviação de _**tr**ansposed t**ibble**_, que permite organizar
```suggestion
Inserir os dados por coluna pode dificultar a visualização de como as linhas estão relacionadas, então uma alternativa é `tribble()`, abreviação de _**tr**ansposed t**ibble**_ (tibble transposta), que permite organizar seus dados linha por linha.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
>  `tribble()` is customized for data entry in code: column headings start with `~` and entries are separated by commas.
acho que isso não ficou traduzido

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
> +Então, no próximo capítulo, você aprenderá alguns bons lugares para procurar ajuda, como criar um reprex[^data-import-5] para maximizar suas chances de obter boa ajuda e alguns conselhos gerais sobre
```suggestion
Então, no próximo capítulo, você aprenderá alguns bons lugares para procurar ajuda, como criar um exemplo reprodutível (*reprex*)[^data-import-5] para maximizar suas chances de obter boa ajuda e alguns conselhos gerais sobre como acompanhar o mundo do R.
```

2024-05-27 18:38 UTC, beatrizmilz commented on data-import.qmd
>  This makes it possible to lay out small amounts of data in an easy to read form:
Acho que isso não ficou traduzido

2024-05-27 18:41 UTC, beatrizmilz commented on data-import.qmd
>  This makes it possible to lay out small amounts of data in an easy to read form:
```suggestion
Isso torna possível dispor pequenas quantidades de dados em uma forma fácil de ler:
```

2024-05-27 18:42 UTC, beatrizmilz commented on data-import.qmd
>  `tribble()` is customized for data entry in code: column headings start with `~` and entries are separated by commas.
```suggestion
`tribble()` é customizado para entrada de dados no código: os cabeçalhos das colunas começam com `~` e as entradas são separadas por vírgulas.
```

2024-06-11 18:30 UTC, beatrizmilz commented
Oi @beatrizccolvara! Se você tiver alguma dúvida sobre a revisão, me avise por favor!

2024-06-19 18:38 UTC, beatrizccolvara requested changes
Beatriz e Alberson, espero ter contribuído de forma útil com essa revisão! Grande abraço, fico à disposição.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Neste capítulo, você aprenderá o básico de como ler arquivos de dados no R.
```suggestion
Neste capítulo, você aprenderá o básico sobre como ler arquivos de dados no R.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Você então aprenderá sobre como ler dados de múltiplos arquivos de uma vez e exportar dados do R para um arquivo.
```suggestion
Você então aprenderá sobre como ler dados de múltiplos arquivos de uma única vez e exportar dados do R para um arquivo.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Neste capítulo, você irá aprender como importar arquivos planos no R com o pacote **readr**, que faz parte do tidyverse.
Eu acho que arquivos de texto ainda não é exatamente a ideia. Talvez arquivos flat sejam arquivos **simples**?

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +## Importando dados de um arquivo
```suggestion
## Lendo dados de um arquivo
```

Me parece que é feita uma distinção dos autores do original entre _import_ e _read_. Talvez seja interessante manter essa diferença no português também.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Podemos importar esse arquivo para o R usando `read_csv()`.
```suggestion
Podemos ler esse arquivo em R usando `read_csv()`.
```

Mesma ideia do comentário anterior sobre manter distinção entre _import_ e _read_.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> -This is something we can address using the `na` argument.
Algum motivo especial para essa linha não ter sido traduzida?

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Por padrão, `read_csv()` reconhece apenas strings vazias (`""`) como `NA`s, mas, para esse conjunto de dados, também queremos que ele reconheça a *string* de caracteres `"N/A"`.
```suggestion
Por padrão, `read_csv()` reconhece apenas strings não preenchidos (`""`) como `NA`s, mas, para esse conjunto de dados, também queremos que ele reconheça os caracteres `"N/A"`.
```
A _string_ ou O _string_?
Pensei nessa alternativa de escrita para não precisarmos definir gênero para essa palavra.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Para se referir a essas variáveis, você precisa cercá-las com crases, `` ` ``:
```suggestion
Para se referir a essas variáveis, você precisa usar crases, `` ` ``:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> -[^data-import-1]: The [janitor](http://sfirke.github.io/janitor/) package is not part of the tidyverse, but it offers handy functions for data cleaning and works well within data pipelines that use `
Esse trecho também não está traduzido.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Outra tarefa comum após a importação dos dados é a correção dos tipos de variáveis.
```suggestion
Outra tarefa comum após a leitura dos dados é examinar os tipos de variáveis.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Atualmente, `idade` é uma variável de caractere porque uma das observações é digitada como `cinco` em vez de um `5` numérico.
```suggestion
Atualmente, `idade` é uma variável de caractere porque uma das observações está digitada como `cinco` em vez de um `5` numérico.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Aqui estamos dizendo que se `idade` é a *string* de caracteres `"cinco"`, faça-a `"5"`, e se não, mantenha-a como `idade`.
```suggestion
Aqui estamos dizendo que se `idade` for o *string* de caracteres `"cinco"`, faça-o `"5"`, e se não, mantenha-o como `idade`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Você pode usar `skip = n` para pular as primeiras `n` linhas ou usar `comment = "#"` para descartar todas as linhas que começam com `#`, por exemplo:
```suggestion
Você pode usar `skip = n` para pular as primeiras `n` linhas ou usar `comment = "#"` para ignorar todas as linhas que começam com `#`, por exemplo:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Você pode usar `col_names = FALSE` para dizer ao `read_csv()` para não tratar a primeira linha como cabeçalhos e, em vez disso, rotulá-los sequencialmente de `X1` a `Xn`:
```suggestion
Você pode usar `col_names = FALSE` para dizer ao `read_csv()` para não tratar a primeira linha como cabeçalho e, em vez disso, rotular as colunas sequencialmente de `X1` a `Xn`:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Alternativamente, você pode passar a `col_names` um vetor de caracteres que será usado como os nomes das colunas:
```suggestion
Alternativamente, você pode fornecer à `col_names` um vetor de caracteres que será usado como os nomes das colunas:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    Usa `;` ao invés de `,` para separar os campos e são comuns em países que usam `,` como marcador decimal.
```suggestion
    Usa `;` ao invés de `,` para separar os campos, e são comuns em países que usam `,` como marcador decimal.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +-   `read_delim()` lê arquivos com qualquer delimitador, tentando adivinhar automaticamente o delimitador se você não o especificar.
```suggestion
-   `read_delim()` lê arquivos com qualquer delimitador, tentando supor automaticamente o delimitador se você não o especificar.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +1.  Que função você usaria para ler um arquivo onde os campos são separados por `|`?
```suggestion
1.  Que função você usaria para ler um arquivo onde os campos são separados por `\|`?
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +4.  Às vezes, as *strings* em um arquivo CSV contêm vírgulas.
```suggestion
4.  Às vezes, *strings* em um arquivo CSV contêm vírgulas.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    Para evitar que elas causem problemas, elas precisam ser cercadas por um caractere de citação, como `"` ou `'`. Por padrão, `read_csv()` assume que o caractere de citação será `"`.
```suggestion
    Para evitar que causem problemas, elas precisam ser acompanhadas por caracteres de citação, como `"` ou `'`. Por padrão, `read_csv()` assume que o carácter de citação será `"`.
```

Me parece que caracteres é o plural de carácter.

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +6.  Pratique se referir a nomes não-sintáticos no seguinte data frame por:
```suggestion
6.  Pratique se referir a nomes não-sintáticos no seguinte data frame:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    a.  Extrair a variável chamada `1`.
```suggestion
    a.  Extraindo a variável chamada `1`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    b.  Plotar um gráfico de dispersão de `1` vs. `2`.
```suggestion
    b.  Plotando um gráfico de dispersão de `1` vs. `2`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    c.  Criar uma nova coluna chamada `3`, que é `2` dividido por `1`.
```suggestion
    c.  Criando uma nova coluna chamada `3`, que é `2` dividido por `1`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    d.  Renomear as colunas para `um`, `dois` e `três`.
```suggestion
    d.  Renomeando as colunas para `um`, `dois` e `três`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Um arquivo CSV não contém informações sobre o tipo de cada variável (ou seja, se é um lógico, número, *string*, etc.), então o readr tentará adivinhar o tipo.
```suggestion
Um arquivo CSV não contém informações sobre o tipo de cada variável (ou seja, se é lógico, número, *string*, etc.), então readr tentará adivinhar o tipo.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Uma das causas mais comuns para isso é um valor ausente, registrado usando algo diferente do `NA` que o readr espera.
```suggestion
Uma das causas mais comuns para isso é um valor ausente registrado usando algo diferente do `NA` que o readr espera.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +-   `col_logical()` e `col_double()` leem lógicos e números reais. Eles são relativamente raramente necessários (exceto como acima), já que o readr geralmente os adivinhará para você.
```suggestion
-   `col_logical()` e `col_double()` leem lógicos e números reais. É relativamente raro serem necessários (exceto como acima), já que o readr geralmente os adivinhará para você.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +-   `col_character()` lê *strings*. Isso pode ser útil para especificar explicitamente quando você tem uma coluna que é um identificador numérico, ou seja, longas séries de dígitos que identificam um
```suggestion
-   `col_character()` lê *strings*. Isso pode ser útil para especificar explicitamente quando você tem uma coluna que é um identificador numérico, ou seja, longas séries de dígitos que identificam um objeto, mas onde não faz sentido aplicar operações matemáticas. Exemplos incluem números de telefone, números de seguro social, números de cartão de crédito, etc.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +-   `col_factor()`, `col_date()` e `col_datetime()` criam fatores, datas e data-horas, respectivamente; você aprenderá mais sobre esses tipos de dados quando chegarmos a eles em @sec-factors e @sec-d
Talvez _times_ necessite de uma tradução temporal mais genérica do que horas. Talvez **tempo**?

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Outra função auxiliar é `cols_only()`, que lerá apenas as colunas que você especificar:
```suggestion
Outro auxiliar útil é `cols_only()`, que lerá apenas as colunas que você especificar:
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Às vezes seus dados estão divididos em vários arquivos em vez de estarem contidos em um único arquivo.
```suggestion
Às vezes seus dados estão divididos em vários arquivos em vez de estarem contidos em um único.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +arquivos_vendas <- c("data/01-vendas.csv", "data/02-vendas.csv", "data/03-vendas.csv")
```suggestion
arquivos_vendas <- c("dados/01-vendas.csv", "dados/02-vendas.csv", "dados/03-vendas.csv")
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +read_csv(arquivos_vendas, id = "file")
```suggestion
read_csv(arquivos_vendas, id = "arquivo")
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Mais uma vez, o código acima funcionará apenas se você tiver os arquivos CSV em uma pasta chamada `data` no seu projeto.
```suggestion
Mais uma vez, o código acima funcionará apenas se você tiver os arquivos CSV em uma pasta chamada `dados` no seu projeto.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +arquivos_vendas <- list.files("data", pattern = "vendas\\.csv$", full.names = TRUE)
```suggestion
arquivos_vendas <- list.files("dados", pattern = "vendas\\.csv$", full.names = TRUE)
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Agora, vamos ler esse arquivo CSV de volta.
```suggestion
Agora, vamos ler esse arquivo CSV novamente.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +    Isso significa que quando você recarrega o objeto, você está carregando o *mesmo* objeto R que você armazenou.
```suggestion
    Isso significa que quando você recarrega o objeto, você está carregando *exatamente o mesmo* objeto R que você armazenou.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Neste capítulo, você aprendeu a como carregar arquivos CSV com `read_csv()` e a como inserir seus próprios dados com `tibble()` e `tribble()`.
```suggestion
Neste capítulo, você aprendeu como carregar arquivos CSV com `read_csv()` e como inserir seus próprios dados com `tibble()` e `tribble()`.
```

2024-06-19 18:38 UTC, beatrizccolvara commented on data-import.qmd
> +Voltaremos à importação de dados algumas vezes neste livro: @sec-import-spreadsheets do Excel e Google Planilhas, @sec-import-databases mostrará como carregar dados de bancos de dados, @sec-arrow de
```suggestion
Voltaremos à importação de dados algumas vezes neste livro: @sec-import-spreadsheets do Excel e do Google Planilhas, @sec-import-databases mostrará para você como carregar dados de bancos de dados, @sec-arrow de arquivos parquet, @sec-rectangling de JSON e @sec-scraping de sites.
```

2024-06-21 17:28 UTC, beatrizmilz commented on data-import.qmd
> +Neste capítulo, você irá aprender como importar arquivos planos no R com o pacote **readr**, que faz parte do tidyverse.
Eu fiz a sugestão pensando mais no formato que o readr lê mesmo... ele lê apenas arquivos de texto!

2024-06-21 17:29 UTC, beatrizmilz commented on data-import.qmd
> +Por padrão, `read_csv()` reconhece apenas strings vazias (`""`) como `NA`s, mas, para esse conjunto de dados, também queremos que ele reconheça a *string* de caracteres `"N/A"`.
Geralmente eu ouço chamarem string no feminino (e acabo falando assim também)!

2024-06-21 17:30 UTC, beatrizmilz commented on data-import.qmd
> -[^data-import-1]: The [janitor](http://sfirke.github.io/janitor/) package is not part of the tidyverse, but it offers handy functions for data cleaning and works well within data pipelines that use `
pelo que eu entendi, os trechos de nota de rodapé ficaram ao final do arquivo!

2024-06-21 17:34 UTC, beatrizmilz commented on data-import.qmd
> +Na coluna `comida.favorita`, há uma série de itens de comida, e o texto (*string*) `"N/A"`, que deveria ter sido um `NA` real que o R reconheceria como um dado faltante (*not available*).
```suggestion
Na coluna `comida.favorita`, há uma série de itens de comida, e o texto (*string*) `"N/A"`, que deveria ter sido um `NA` real que o R reconheceria como um dado faltante (*not available*).
Isso é algo que podemos resolver usando o argumento `na`.
```

2024-06-21 17:34 UTC, beatrizmilz commented on data-import.qmd
> -This is something we can address using the `na` argument.
Verdade! Não tinha reparado. fiz uma sugestão com a tradução dela

2024-06-21 17:36 UTC, beatrizmilz commented on data-import.qmd
> +    Para evitar que elas causem problemas, elas precisam ser cercadas por um caractere de citação, como `"` ou `'`. Por padrão, `read_csv()` assume que o caractere de citação será `"`.
Dei uma pesquisada, e os dois estariam corretos! Mas em programação, é usado "caractere".

2024-06-21 17:44 UTC, beatrizmilz commented on data-import.qmd
> +-   `col_factor()`, `col_date()` e `col_datetime()` criam fatores, datas e data-horas, respectivamente; você aprenderá mais sobre esses tipos de dados quando chegarmos a eles em @sec-factors e @sec-d
A forma usada é data-hora mesmo!

2024-06-21 17:46 UTC, beatrizmilz commented
> Beatriz e Alberson, espero ter contribuído de forma útil com essa revisão! Grande abraço, fico à disposição.

Muito obrigada!! foi muito útil sim!

2024-06-21 17:52 UTC, merged

2024-06-21 18:01 UTC, beatrizmilz commented
Gente, aceitei o PR! Está aqui: https://cienciadedatos.github.io/pt-r4ds/data-import.html